In [ ]:
import pandas as pd

In [ ]:
data=pd.read_csv("/content/Orders_2024_Jan_Jun.csv")

In [ ]:
data

,OrderID,OrderDate,CustomerID,CustomerName,Region,ProductID,ProductName,Category,Quantity,Price,TotalAmount,PaymentMethod
0,1001,5/21/2024,2,Customer_2,E,9,Product_9,Grocery,9,1047,9423,UPI
1,1002,1/18/2024,37,Customer_37,North,19,Product_19,Home Decor,1,1563,1563,NetBanking
2,1003,3/28/2024,9,Customer_9,South,12,Product_12,Home Decor,4,1539,6156,COD
3,1004,3/29/2024,40,Customer_40,West,14,Product_14,Grocery,3,204,612,NetBanking
4,1005,5/25/2024,40,Customer_40,West,14,Product_14,Grocery,9,204,1836,COD
...,...,...,...,...,...,...,...,...,...,...,...,...
265,1020,4/5/2024,31,Customer_31,South,2,Product_2,Home Decor,7,481,3367,NetBanking
266,1021,3/15/2024,38,Customer_38,North,8,Product_8,Home Decor,1,1924,1924,UPI
267,1022,3/3/2024,28,Customer_28,North,4,Product_4,Grocery,10,1380,13800,COD
268,1023,6/24/2024,35,Customer_35,East,9,Product_9,Grocery,2,1047,2094,Card
269,1024,1/5/2024,46,Customer_46,South,16,Product_16,Electronics,10,1948,19480,UPI

In [ ]:
data.query("(CustomerID>45 & Region=='East') & Category in ['Home Decor','Fashion']")

,OrderID,OrderDate,CustomerID,CustomerName,Region,ProductID,ProductName,Category,Quantity,Price,TotalAmount,PaymentMethod
34,1035,6/12/2024,48,Customer_48,East,2,Product_2,Home Decor,3,481,1443,Card
89,1090,5/7/2024,48,Customer_48,East,10,Product_10,Fashion,4,273,1092,Card
91,1092,3/17/2024,48,Customer_48,East,6,Product_6,Fashion,7,1421,9947,UPI
131,1132,6/5/2024,48,Customer_48,East,8,Product_8,Home Decor,6,1924,11544,Card

In [ ]:
data[(data['CustomerID']>45) & (data['Region']=='East') & ((data['Category']=='Fashion') | (data['Category']=='Home Decor'))]

,OrderID,OrderDate,CustomerID,CustomerName,Region,ProductID,ProductName,Category,Quantity,Price,TotalAmount,PaymentMethod
34,1035,6/12/2024,48,Customer_48,East,2,Product_2,Home Decor,3,481,1443,Card
89,1090,5/7/2024,48,Customer_48,East,10,Product_10,Fashion,4,273,1092,Card
91,1092,3/17/2024,48,Customer_48,East,6,Product_6,Fashion,7,1421,9947,UPI
131,1132,6/5/2024,48,Customer_48,East,8,Product_8,Home Decor,6,1924,11544,Card

In [ ]:
data

,OrderID,OrderDate,CustomerID,CustomerName,Region,ProductID,ProductName,Category,Quantity,Price,TotalAmount,PaymentMethod
0,1001,5/21/2024,2,Customer_2,E,9,Product_9,Grocery,9,1047,9423,UPI
1,1002,1/18/2024,37,Customer_37,North,19,Product_19,Home Decor,1,1563,1563,NetBanking
2,1003,3/28/2024,9,Customer_9,South,12,Product_12,Home Decor,4,1539,6156,COD
3,1004,3/29/2024,40,Customer_40,West,14,Product_14,Grocery,3,204,612,NetBanking
4,1005,5/25/2024,40,Customer_40,West,14,Product_14,Grocery,9,204,1836,COD
...,...,...,...,...,...,...,...,...,...,...,...,...
265,1020,4/5/2024,31,Customer_31,South,2,Product_2,Home Decor,7,481,3367,NetBanking
266,1021,3/15/2024,38,Customer_38,North,8,Product_8,Home Decor,1,1924,1924,UPI
267,1022,3/3/2024,28,Customer_28,North,4,Product_4,Grocery,10,1380,13800,COD
268,1023,6/24/2024,35,Customer_35,East,9,Product_9,Grocery,2,1047,2094,Card
269,1024,1/5/2024,46,Customer_46,South,16,Product_16,Electronics,10,1948,19480,UPI

In [ ]:
data.groupby(data['Region']).groups

{'E': [0, 5, 6, 9, 12, 15, 16, 22, 25], 'East': [34, 53, 56, 59, 68, 73, 86, 87, 89, 91, 94, 97, 100, 102, 106, 120, 124, 131, 153, 155, 160, 161, 198, 205, 206, 213, 216, 222, 225, 230, 233, 235, 238, 246, 251, 252, 255, 258, 261, 262, 268], 'North': [1, 13, 18, 20, 21, 26, 33, 35, 42, 43, 45, 51, 54, 61, 62, 64, 65, 66, 67, 70, 77, 98, 99, 104, 111, 112, 114, 117, 125, 128, 137, 144, 148, 156, 157, 158, 162, 170, 175, 179, 180, 181, 186, 188, 194, 195, 197, 203, 209, 223, 226, 229, 237, 242, 247, 259, 264, 266, 267], 'S': [71, 78, 80, 82, 83, 84, 88, 92, 93, 95], 'South': [2, 17, 19, 23, 24, 29, 39, 44, 46, 47, 49, 50, 55, 107, 108, 110, 115, 121, 122, 126, 129, 138, 139, 141, 142, 145, 149, 151, 152, 154, 163, 164, 168, 169, 177, 183, 187, 189, 190, 191, 193, 199, 207, 208, 210, 212, 215, 218, 221, 224, 239, 240, 241, 244, 245, 248, 263, 265, 269], 'W': [113, 116, 118, 119, 123], 'West': [3, 4, 7, 8, 10, 11, 14, 27, 28, 30, 31, 32, 36, 37, 38, 40, 41, 48, 52, 57, 58, 60, 63, 69, 72, 74, 75, 76, 79, 81, 85, 90, 96, 101, 103, 105, 109, 127, 130, 132, 133, 134, 135, 136, 140, 143, 146, 147, 150, 159, 165, 166, 167, 171, 172, 173, 174, 176, 178, 182, 184, 185, 192, 196, 200, 201, 202, 204, 211, 214, 217, 219, 220, 227, 228, 231, 232, 234, 236, 243, 249, 250, 253, 254, 256, 257, 260]}

In [ ]:
data.groupby(data['Region']).size()

Region
E         9
East     41
North    59
S        10
South    59
W         5
West     87
dtype: int64

In [ ]:
data['Price'].groupby(data['Region']).sum()

Region
E        11491
East     51027
North    66546
S        11548
South    74416
W         6416
West     96828
Name: Price, dtype: int64

In [ ]:
data['Price'].groupby(data['Region']).mean()

Region
E        1276.777778
East     1244.560976
North    1127.898305
S        1154.800000
South    1261.288136
W        1283.200000
West     1112.965517
Name: Price, dtype: float64

In [ ]:
data1=data[['Quantity','Price','TotalAmount']].groupby(data['ProductName']).sum()

In [ ]:
data1

   ProductName  Quantity  Price  TotalAmount
0    Product_1        69   7462        39606
1   Product_10        80   3549        21840
2   Product_11        19   5465        20767
3   Product_12        97  24624       149283
4   Product_13        96  19005       121632
5   Product_14       122   3876        24888
6   Product_15        59  10736        57584
7   Product_16        98  38960       190904
8   Product_17        97  23760       128040
9   Product_18        57  14287        62643
10  Product_19        50  17193        78150
11   Product_2        76   7215        36556
12  Product_20        59  17138        91922
13   Product_3        62  14568        75268
14   Product_4        43  12420        59340
15   Product_5        67   7584        42344
16   Product_6        28   7105        39788
17   Product_7        46  14625        74750
18   Product_8       153  51948       294372
19   Product_9        88  16752        92136

In [ ]:
data1=data1.reset_index()

In [ ]:
data1

    index ProductName  Quantity  Price  TotalAmount
0       0   Product_1        69   7462        39606
1       1  Product_10        80   3549        21840
2       2  Product_11        19   5465        20767
3       3  Product_12        97  24624       149283
4       4  Product_13        96  19005       121632
5       5  Product_14       122   3876        24888
6       6  Product_15        59  10736        57584
7       7  Product_16        98  38960       190904
8       8  Product_17        97  23760       128040
9       9  Product_18        57  14287        62643
10     10  Product_19        50  17193        78150
11     11   Product_2        76   7215        36556
12     12  Product_20        59  17138        91922
13     13   Product_3        62  14568        75268
14     14   Product_4        43  12420        59340
15     15   Product_5        67   7584        42344
16     16   Product_6        28   7105        39788
17     17   Product_7        46  14625        74750
18     18   Product_8       153  51948       294372
19     19   Product_9        88  16752        92136

In [ ]:
data1.sort_index(ascending=False)

    index ProductName  Quantity  Price  TotalAmount
19     19   Product_9        88  16752        92136
18     18   Product_8       153  51948       294372
17     17   Product_7        46  14625        74750
16     16   Product_6        28   7105        39788
15     15   Product_5        67   7584        42344
14     14   Product_4        43  12420        59340
13     13   Product_3        62  14568        75268
12     12  Product_20        59  17138        91922
11     11   Product_2        76   7215        36556
10     10  Product_19        50  17193        78150
9       9  Product_18        57  14287        62643
8       8  Product_17        97  23760       128040
7       7  Product_16        98  38960       190904
6       6  Product_15        59  10736        57584
5       5  Product_14       122   3876        24888
4       4  Product_13        96  19005       121632
3       3  Product_12        97  24624       149283
2       2  Product_11        19   5465        20767
1       1  Product_10        80   3549        21840
0       0   Product_1        69   7462        39606

In [ ]:
data1

    index ProductName  Quantity  Price  TotalAmount
0       0   Product_1        69   7462        39606
1       1  Product_10        80   3549        21840
2       2  Product_11        19   5465        20767
3       3  Product_12        97  24624       149283
4       4  Product_13        96  19005       121632
5       5  Product_14       122   3876        24888
6       6  Product_15        59  10736        57584
7       7  Product_16        98  38960       190904
8       8  Product_17        97  23760       128040
9       9  Product_18        57  14287        62643
10     10  Product_19        50  17193        78150
11     11   Product_2        76   7215        36556
12     12  Product_20        59  17138        91922
13     13   Product_3        62  14568        75268
14     14   Product_4        43  12420        59340
15     15   Product_5        67   7584        42344
16     16   Product_6        28   7105        39788
17     17   Product_7        46  14625        74750
18     18   Product_8       153  51948       294372
19     19   Product_9        88  16752        92136

In [ ]:
data

,OrderID,OrderDate,CustomerID,CustomerName,Region,ProductID,ProductName,Category,Quantity,Price,TotalAmount,PaymentMethod
0,1001,5/21/2024,2,Customer_2,E,9,Product_9,Grocery,9,1047,9423,UPI
1,1002,1/18/2024,37,Customer_37,North,19,Product_19,Home Decor,1,1563,1563,NetBanking
2,1003,3/28/2024,9,Customer_9,South,12,Product_12,Home Decor,4,1539,6156,COD
3,1004,3/29/2024,40,Customer_40,West,14,Product_14,Grocery,3,204,612,NetBanking
4,1005,5/25/2024,40,Customer_40,West,14,Product_14,Grocery,9,204,1836,COD
...,...,...,...,...,...,...,...,...,...,...,...,...
265,1020,4/5/2024,31,Customer_31,South,2,Product_2,Home Decor,7,481,3367,NetBanking
266,1021,3/15/2024,38,Customer_38,North,8,Product_8,Home Decor,1,1924,1924,UPI
267,1022,3/3/2024,28,Customer_28,North,4,Product_4,Grocery,10,1380,13800,COD
268,1023,6/24/2024,35,Customer_35,East,9,Product_9,Grocery,2,1047,2094,Card
269,1024,1/5/2024,46,Customer_46,South,16,Product_16,Electronics,10,1948,19480,UPI

In [ ]:
data.query("Region=='E'").groupby(data['CustomerID']).sum()

,OrderID,OrderDate,CustomerID,CustomerName,Region,ProductID,ProductName,Category,Quantity,Price,TotalAmount,PaymentMethod
CustomerID,,,,,,,,,,,,
2,1001,5/21/2024,2,Customer_2,E,9,Product_9,Grocery,9,1047,9423,UPI
25,2024,2/14/20244/26/2024,50,Customer_25Customer_25,EE,26,Product_18Product_8,Home DecorHome Decor,7,3023,12643,CardCard
26,1016,5/29/2024,26,Customer_26,E,8,Product_8,Home Decor,8,1924,15392,COD
35,1023,6/24/2024,35,Customer_35,E,9,Product_9,Grocery,2,1047,2094,Card
39,1010,2/11/2024,39,Customer_39,E,5,Product_5,Electronics,1,632,632,NetBanking
45,1013,5/22/2024,45,Customer_45,E,1,Product_1,Grocery,1,574,574,Card
48,2032,6/28/20245/15/2024,96,Customer_48Customer_48,EE,25,Product_17Product_8,ElectronicsHome Decor,10,3244,16824,CODNetBanking

In [ ]:
data[data['Region']=='E'].groupby(data['CustomerID']).sum()

,OrderID,OrderDate,CustomerID,CustomerName,Region,ProductID,ProductName,Category,Quantity,Price,TotalAmount,PaymentMethod
CustomerID,,,,,,,,,,,,
2,1001,5/21/2024,2,Customer_2,E,9,Product_9,Grocery,9,1047,9423,UPI
25,2024,2/14/20244/26/2024,50,Customer_25Customer_25,EE,26,Product_18Product_8,Home DecorHome Decor,7,3023,12643,CardCard
26,1016,5/29/2024,26,Customer_26,E,8,Product_8,Home Decor,8,1924,15392,COD
35,1023,6/24/2024,35,Customer_35,E,9,Product_9,Grocery,2,1047,2094,Card
39,1010,2/11/2024,39,Customer_39,E,5,Product_5,Electronics,1,632,632,NetBanking
45,1013,5/22/2024,45,Customer_45,E,1,Product_1,Grocery,1,574,574,Card
48,2032,6/28/20245/15/2024,96,Customer_48Customer_48,EE,25,Product_17Product_8,ElectronicsHome Decor,10,3244,16824,CODNetBanking

In [ ]:
data

,OrderID,OrderDate,CustomerID,CustomerName,Region,ProductID,ProductName,Category,Quantity,Price,TotalAmount,PaymentMethod
0,1001,5/21/2024,2,Customer_2,E,9,Product_9,Grocery,9,1047,9423,UPI
1,1002,1/18/2024,37,Customer_37,North,19,Product_19,Home Decor,1,1563,1563,NetBanking
2,1003,3/28/2024,9,Customer_9,South,12,Product_12,Home Decor,4,1539,6156,COD
3,1004,3/29/2024,40,Customer_40,West,14,Product_14,Grocery,3,204,612,NetBanking
4,1005,5/25/2024,40,Customer_40,West,14,Product_14,Grocery,9,204,1836,COD
...,...,...,...,...,...,...,...,...,...,...,...,...
265,1020,4/5/2024,31,Customer_31,South,2,Product_2,Home Decor,7,481,3367,NetBanking
266,1021,3/15/2024,38,Customer_38,North,8,Product_8,Home Decor,1,1924,1924,UPI
267,1022,3/3/2024,28,Customer_28,North,4,Product_4,Grocery,10,1380,13800,COD
268,1023,6/24/2024,35,Customer_35,East,9,Product_9,Grocery,2,1047,2094,Card
269,1024,1/5/2024,46,Customer_46,South,16,Product_16,Electronics,10,1948,19480,UPI

In [ ]:
data['Price'].groupby(data['Region']).mean()

Region
E        1276.777778
East     1244.560976
North    1127.898305
S        1154.800000
South    1261.288136
W        1283.200000
West     1112.965517
Name: Price, dtype: float64

In [ ]:
data['Region'].unique()

array(['E', 'North', 'South', 'West', 'East', 'S', 'W'], dtype=object)

In [ ]:
data['Region'].nunique()

7

In [ ]:
data['Region'].value_counts()

Region
West     87
South    59
North    59
East     41
S        10
E         9
W         5
Name: count, dtype: int64

In [ ]:
data.value_counts()

OrderID  OrderDate   CustomerID  CustomerName  Region  ProductID  ProductName  Category    Quantity  Price  TotalAmount  PaymentMethod
1003     3/28/2024   9           Customer_9    South   12         Product_12   Home Decor  4         1539   6156         COD              2
1002     1/18/2024   37          Customer_37   North   19         Product_19   Home Decor  1         1563   1563         NetBanking       2
1004     3/29/2024   40          Customer_40   West    14         Product_14   Grocery     3         204    612          NetBanking       2
1005     5/25/2024   40          Customer_40   West    14         Product_14   Grocery     9         204    1836         COD              2
1008     4/13/2024   30          Customer_30   West    12         Product_12   Home Decor  10        1539   15390        NetBanking       2
                                                                                                                                         ..
2078     8/16/2024   1           Customer_1    South   2          Product_2    Home Decor  8         481    3848         COD              1
2079     12/13/2024  3           Customer_3    North   4          Product_4    Grocery     3         1380   4140         NetBanking       1
2080     10/13/2024  6           Customer_6    West    13         Product_13   Home Decor  2         1267   2534         Card             1
2081     12/9/2024   18          Customer_18   South   6          Product_6    Fashion     3         1421   4263         NetBanking       1
2082     7/5/2024    9           Customer_9    South   18         Product_18   Home Decor  5         1099   5495         Card             1
Name: count, Length: 254, dtype: int64