In [42]:
import pandas as pd

In [43]:
data=pd.read_csv("/content/Orders_2024_Jan_Jun.csv")

In [44]:
data

,OrderID,OrderDate,CustomerID,CustomerName,Region,ProductID,ProductName,Category,Quantity,Price,TotalAmount,PaymentMethod
0,1001,5/21/2024,2,Customer_2,E,9,Product_9,Grocery,9,1047,9423,UPI
1,1002,1/18/2024,37,Customer_37,North,19,Product_19,Home Decor,1,1563,1563,NetBanking
2,1003,3/28/2024,9,Customer_9,South,12,Product_12,Home Decor,4,1539,6156,COD
3,1004,3/29/2024,40,Customer_40,West,14,Product_14,Grocery,3,204,612,NetBanking
4,1005,5/25/2024,40,Customer_40,West,14,Product_14,Grocery,9,204,1836,COD
...,...,...,...,...,...,...,...,...,...,...,...,...
265,1020,4/5/2024,31,Customer_31,South,2,Product_2,Home Decor,7,481,3367,NetBanking
266,1021,3/15/2024,38,Customer_38,North,8,Product_8,Home Decor,1,1924,1924,UPI
267,1022,3/3/2024,28,Customer_28,North,4,Product_4,Grocery,10,1380,13800,COD
268,1023,6/24/2024,35,Customer_35,East,9,Product_9,Grocery,2,1047,2094,Card
269,1024,1/5/2024,46,Customer_46,South,16,Product_16,Electronics,10,1948,19480,UPI

In [45]:
data['concat']=data['CustomerName'].str.cat(data['Region'],'--')

In [46]:
data

,OrderID,OrderDate,CustomerID,CustomerName,Region,ProductID,ProductName,Category,Quantity,Price,TotalAmount,PaymentMethod,concat
0,1001,5/21/2024,2,Customer_2,E,9,Product_9,Grocery,9,1047,9423,UPI,Customer_2--E
1,1002,1/18/2024,37,Customer_37,North,19,Product_19,Home Decor,1,1563,1563,NetBanking,Customer_37--North
2,1003,3/28/2024,9,Customer_9,South,12,Product_12,Home Decor,4,1539,6156,COD,Customer_9--South
3,1004,3/29/2024,40,Customer_40,West,14,Product_14,Grocery,3,204,612,NetBanking,Customer_40--West
4,1005,5/25/2024,40,Customer_40,West,14,Product_14,Grocery,9,204,1836,COD,Customer_40--West
...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,1020,4/5/2024,31,Customer_31,South,2,Product_2,Home Decor,7,481,3367,NetBanking,Customer_31--South
266,1021,3/15/2024,38,Customer_38,North,8,Product_8,Home Decor,1,1924,1924,UPI,Customer_38--North
267,1022,3/3/2024,28,Customer_28,North,4,Product_4,Grocery,10,1380,13800,COD,Customer_28--North
268,1023,6/24/2024,35,Customer_35,East,9,Product_9,Grocery,2,1047,2094,Card,Customer_35--East
269,1024,1/5/2024,46,Customer_46,South,16,Product_16,Electronics,10,1948,19480,UPI,Customer_46--South

In [47]:
data['cusname']=data['Category']+" "+data['PaymentMethod']

In [48]:
data

,OrderID,OrderDate,CustomerID,CustomerName,Region,ProductID,ProductName,Category,Quantity,Price,TotalAmount,PaymentMethod,concat,cusname
0,1001,5/21/2024,2,Customer_2,E,9,Product_9,Grocery,9,1047,9423,UPI,Customer_2--E,Grocery UPI
1,1002,1/18/2024,37,Customer_37,North,19,Product_19,Home Decor,1,1563,1563,NetBanking,Customer_37--North,Home Decor NetBanking
2,1003,3/28/2024,9,Customer_9,South,12,Product_12,Home Decor,4,1539,6156,COD,Customer_9--South,Home Decor COD
3,1004,3/29/2024,40,Customer_40,West,14,Product_14,Grocery,3,204,612,NetBanking,Customer_40--West,Grocery NetBanking
4,1005,5/25/2024,40,Customer_40,West,14,Product_14,Grocery,9,204,1836,COD,Customer_40--West,Grocery COD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,1020,4/5/2024,31,Customer_31,South,2,Product_2,Home Decor,7,481,3367,NetBanking,Customer_31--South,Home Decor NetBanking
266,1021,3/15/2024,38,Customer_38,North,8,Product_8,Home Decor,1,1924,1924,UPI,Customer_38--North,Home Decor UPI
267,1022,3/3/2024,28,Customer_28,North,4,Product_4,Grocery,10,1380,13800,COD,Customer_28--North,Grocery COD
268,1023,6/24/2024,35,Customer_35,East,9,Product_9,Grocery,2,1047,2094,Card,Customer_35--East,Grocery Card
269,1024,1/5/2024,46,Customer_46,South,16,Product_16,Electronics,10,1948,19480,UPI,Customer_46--South,Electronics UPI

In [49]:
data['new_column']=data['Category'].str.cat(data['Quantity'])

TypeError: Concatenation requires list-likes containing only strings (or missing values). Offending values found in column integer

In [61]:
print(type(data))

<class 'pandas.core.frame.DataFrame'>

In [62]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270 entries, 0 to 269
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   OrderID        270 non-null    int64
 1   OrderDate      270 non-null    object
 2   CustomerID     270 non-null    int64
 3   CustomerName   270 non-null    object
 4   Region         270 non-null    object
 5   ProductID      270 non-null    int64
 6   ProductName    270 non-null    object
 7   Category       270 non-null    object
 8   Quantity       270 non-null    int64
 9   Price          270 non-null    int64
 10  TotalAmount    270 non-null    int64
 11  PaymentMethod  270 non-null    object
 12  concat         270 non-null    object
 13  cusname        270 non-null    object
dtypes: int64(6), object(8)
memory usage: 29.7+ KB
None

In [63]:
data['Price']=data['Price'].astype(str)

In [64]:
data

,OrderID,OrderDate,CustomerID,CustomerName,Region,ProductID,ProductName,Category,Quantity,Price,TotalAmount,PaymentMethod,concat,cusname
0,1001,5/21/2024,2,customer_2,E,9,Product_9,Grocery,9,1047,9423,UPI,Customer_2--E,Grocery UPI
1,1002,1/18/2024,37,customer_37,North,19,Product_19,Home Decor,1,1563,1563,NetBanking,Customer_37--North,Home Decor NetBanking
2,1003,3/28/2024,9,customer_9,South,12,Product_12,Home Decor,4,1539,6156,COD,Customer_9--South,Home Decor COD
3,1004,3/29/2024,40,customer_40,West,14,Product_14,Grocery,3,204,612,NetBanking,Customer_40--West,Grocery NetBanking
4,1005,5/25/2024,40,customer_40,West,14,Product_14,Grocery,9,204,1836,COD,Customer_40--West,Grocery COD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,1020,4/5/2024,31,customer_31,South,2,Product_2,Home Decor,7,481,3367,NetBanking,Customer_31--South,Home Decor NetBanking
266,1021,3/15/2024,38,customer_38,North,8,Product_8,Home Decor,1,1924,1924,UPI,Customer_38--North,Home Decor UPI
267,1022,3/3/2024,28,customer_28,North,4,Product_4,Grocery,10,1380,13800,COD,Customer_28--North,Grocery COD
268,1023,6/24/2024,35,customer_35,East,9,Product_9,Grocery,2,1047,2094,Card,Customer_35--East,Grocery Card
269,1024,1/5/2024,46,customer_46,South,16,Product_16,Electronics,10,1948,19480,UPI,Customer_46--South,Electronics UPI

In [65]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270 entries, 0 to 269
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   OrderID        270 non-null    int64
 1   OrderDate      270 non-null    object
 2   CustomerID     270 non-null    int64
 3   CustomerName   270 non-null    object
 4   Region         270 non-null    object
 5   ProductID      270 non-null    int64
 6   ProductName    270 non-null    object
 7   Category       270 non-null    object
 8   Quantity       270 non-null    int64
 9   Price          270 non-null    object
 10  TotalAmount    270 non-null    int64
 11  PaymentMethod  270 non-null    object
 12  concat         270 non-null    object
 13  cusname        270 non-null    object
dtypes: int64(5), object(9)
memory usage: 29.7+ KB

In [66]:
data['new_column']=data['Category'].str.cat(data['Quantity'])

TypeError: Concatenation requires list-likes containing only strings (or missing values). Offending values found in column integer

In [67]:
data['Quantity']=data['Quantity'].astype(str)

In [68]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270 entries, 0 to 269
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   OrderID        270 non-null    int64
 1   OrderDate      270 non-null    object
 2   CustomerID     270 non-null    int64
 3   CustomerName   270 non-null    object
 4   Region         270 non-null    object
 5   ProductID      270 non-null    int64
 6   ProductName    270 non-null    object
 7   Category       270 non-null    object
 8   Quantity       270 non-null    object
 9   Price          270 non-null    object
 10  TotalAmount    270 non-null    int64
 11  PaymentMethod  270 non-null    object
 12  concat         270 non-null    object
 13  cusname        270 non-null    object
dtypes: int64(4), object(10)
memory usage: 29.7+ KB

In [69]:
data['new_column']=data['Category'].str.cat(data['Quantity'])

In [70]:
data

,OrderID,OrderDate,CustomerID,CustomerName,Region,ProductID,ProductName,Category,Quantity,Price,TotalAmount,PaymentMethod,concat,cusname,new_column
0,1001,5/21/2024,2,customer_2,E,9,Product_9,Grocery,9,1047,9423,UPI,Customer_2--E,Grocery UPI,Grocery9
1,1002,1/18/2024,37,customer_37,North,19,Product_19,Home Decor,1,1563,1563,NetBanking,Customer_37--North,Home Decor NetBanking,Home Decor1
2,1003,3/28/2024,9,customer_9,South,12,Product_12,Home Decor,4,1539,6156,COD,Customer_9--South,Home Decor COD,Home Decor4
3,1004,3/29/2024,40,customer_40,West,14,Product_14,Grocery,3,204,612,NetBanking,Customer_40--West,Grocery NetBanking,Grocery3
4,1005,5/25/2024,40,customer_40,West,14,Product_14,Grocery,9,204,1836,COD,Customer_40--West,Grocery COD,Grocery9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,1020,4/5/2024,31,customer_31,South,2,Product_2,Home Decor,7,481,3367,NetBanking,Customer_31--South,Home Decor NetBanking,Home Decor7
266,1021,3/15/2024,38,customer_38,North,8,Product_8,Home Decor,1,1924,1924,UPI,Customer_38--North,Home Decor UPI,Home Decor1
267,1022,3/3/2024,28,customer_28,North,4,Product_4,Grocery,10,1380,13800,COD,Customer_28--North,Grocery COD,Grocery10
268,1023,6/24/2024,35,customer_35,East,9,Product_9,Grocery,2,1047,2094,Card,Customer_35--East,Grocery Card,Grocery2
269,1024,1/5/2024,46,customer_46,South,16,Product_16,Electronics,10,1948,19480,UPI,Customer_46--South,Electronics UPI,Electronics10

In [71]:
data['new']=data['Category'].str.cat(data['TotalAmount'].astype(str))

In [72]:
data

,OrderID,OrderDate,CustomerID,CustomerName,Region,ProductID,ProductName,Category,Quantity,Price,TotalAmount,PaymentMethod,concat,cusname,new_column,new
0,1001,5/21/2024,2,customer_2,E,9,Product_9,Grocery,9,1047,9423,UPI,Customer_2--E,Grocery UPI,Grocery9,Grocery9423
1,1002,1/18/2024,37,customer_37,North,19,Product_19,Home Decor,1,1563,1563,NetBanking,Customer_37--North,Home Decor NetBanking,Home Decor1,Home Decor1563
2,1003,3/28/2024,9,customer_9,South,12,Product_12,Home Decor,4,1539,6156,COD,Customer_9--South,Home Decor COD,Home Decor4,Home Decor6156
3,1004,3/29/2024,40,customer_40,West,14,Product_14,Grocery,3,204,612,NetBanking,Customer_40--West,Grocery NetBanking,Grocery3,Grocery612
4,1005,5/25/2024,40,customer_40,West,14,Product_14,Grocery,9,204,1836,COD,Customer_40--West,Grocery COD,Grocery9,Grocery1836
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,1020,4/5/2024,31,customer_31,South,2,Product_2,Home Decor,7,481,3367,NetBanking,Customer_31--South,Home Decor NetBanking,Home Decor7,Home Decor3367
266,1021,3/15/2024,38,customer_38,North,8,Product_8,Home Decor,1,1924,1924,UPI,Customer_38--North,Home Decor UPI,Home Decor1,Home Decor1924
267,1022,3/3/2024,28,customer_28,North,4,Product_4,Grocery,10,1380,13800,COD,Customer_28--North,Grocery COD,Grocery10,Grocery13800
268,1023,6/24/2024,35,customer_35,East,9,Product_9,Grocery,2,1047,2094,Card,Customer_35--East,Grocery Card,Grocery2,Grocery2094
269,1024,1/5/2024,46,customer_46,South,16,Product_16,Electronics,10,1948,19480,UPI,Customer_46--South,Electronics UPI,Electronics10,Electronics19480

In [73]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270 entries, 0 to 269
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   OrderID        270 non-null    int64
 1   OrderDate      270 non-null    object
 2   CustomerID     270 non-null    int64
 3   CustomerName   270 non-null    object
 4   Region         270 non-null    object
 5   ProductID      270 non-null    int64
 6   ProductName    270 non-null    object
 7   Category       270 non-null    object
 8   Quantity       270 non-null    object
 9   Price          270 non-null    object
 10  TotalAmount    270 non-null    int64
 11  PaymentMethod  270 non-null    object
 12  concat         270 non-null    object
 13  cusname        270 non-null    object
 14  new_column     270 non-null    object
 15  new            270 non-null    object
dtypes: int64(4), object(12)
memory usage: 33.9+ KB

In [74]:
data

,OrderID,OrderDate,CustomerID,CustomerName,Region,ProductID,ProductName,Category,Quantity,Price,TotalAmount,PaymentMethod,concat,cusname,new_column,new
0,1001,5/21/2024,2,customer_2,E,9,Product_9,Grocery,9,1047,9423,UPI,Customer_2--E,Grocery UPI,Grocery9,Grocery9423
1,1002,1/18/2024,37,customer_37,North,19,Product_19,Home Decor,1,1563,1563,NetBanking,Customer_37--North,Home Decor NetBanking,Home Decor1,Home Decor1563
2,1003,3/28/2024,9,customer_9,South,12,Product_12,Home Decor,4,1539,6156,COD,Customer_9--South,Home Decor COD,Home Decor4,Home Decor6156
3,1004,3/29/2024,40,customer_40,West,14,Product_14,Grocery,3,204,612,NetBanking,Customer_40--West,Grocery NetBanking,Grocery3,Grocery612
4,1005,5/25/2024,40,customer_40,West,14,Product_14,Grocery,9,204,1836,COD,Customer_40--West,Grocery COD,Grocery9,Grocery1836
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,1020,4/5/2024,31,customer_31,South,2,Product_2,Home Decor,7,481,3367,NetBanking,Customer_31--South,Home Decor NetBanking,Home Decor7,Home Decor3367
266,1021,3/15/2024,38,customer_38,North,8,Product_8,Home Decor,1,1924,1924,UPI,Customer_38--North,Home Decor UPI,Home Decor1,Home Decor1924
267,1022,3/3/2024,28,customer_28,North,4,Product_4,Grocery,10,1380,13800,COD,Customer_28--North,Grocery COD,Grocery10,Grocery13800
268,1023,6/24/2024,35,customer_35,East,9,Product_9,Grocery,2,1047,2094,Card,Customer_35--East,Grocery Card,Grocery2,Grocery2094
269,1024,1/5/2024,46,customer_46,South,16,Product_16,Electronics,10,1948,19480,UPI,Customer_46--South,Electronics UPI,Electronics10,Electronics19480

In [75]:
data['CustomerName']=data['CustomerName'].str.upper()

In [76]:
data

,OrderID,OrderDate,CustomerID,CustomerName,Region,ProductID,ProductName,Category,Quantity,Price,TotalAmount,PaymentMethod,concat,cusname,new_column,new
0,1001,5/21/2024,2,CUSTOMER_2,E,9,Product_9,Grocery,9,1047,9423,UPI,Customer_2--E,Grocery UPI,Grocery9,Grocery9423
1,1002,1/18/2024,37,CUSTOMER_37,North,19,Product_19,Home Decor,1,1563,1563,NetBanking,Customer_37--North,Home Decor NetBanking,Home Decor1,Home Decor1563
2,1003,3/28/2024,9,CUSTOMER_9,South,12,Product_12,Home Decor,4,1539,6156,COD,Customer_9--South,Home Decor COD,Home Decor4,Home Decor6156
3,1004,3/29/2024,40,CUSTOMER_40,West,14,Product_14,Grocery,3,204,612,NetBanking,Customer_40--West,Grocery NetBanking,Grocery3,Grocery612
4,1005,5/25/2024,40,CUSTOMER_40,West,14,Product_14,Grocery,9,204,1836,COD,Customer_40--West,Grocery COD,Grocery9,Grocery1836
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,1020,4/5/2024,31,CUSTOMER_31,South,2,Product_2,Home Decor,7,481,3367,NetBanking,Customer_31--South,Home Decor NetBanking,Home Decor7,Home Decor3367
266,1021,3/15/2024,38,CUSTOMER_38,North,8,Product_8,Home Decor,1,1924,1924,UPI,Customer_38--North,Home Decor UPI,Home Decor1,Home Decor1924
267,1022,3/3/2024,28,CUSTOMER_28,North,4,Product_4,Grocery,10,1380,13800,COD,Customer_28--North,Grocery COD,Grocery10,Grocery13800
268,1023,6/24/2024,35,CUSTOMER_35,East,9,Product_9,Grocery,2,1047,2094,Card,Customer_35--East,Grocery Card,Grocery2,Grocery2094
269,1024,1/5/2024,46,CUSTOMER_46,South,16,Product_16,Electronics,10,1948,19480,UPI,Customer_46--South,Electronics UPI,Electronics10,Electronics19480

In [77]:
data1=data['Region']

In [78]:
data1

0          E
1      North
2      South
3       West
4       West
       ...
265    South
266    North
267    North
268     East
269    South
Name: Region, Length: 270, dtype: object

In [79]:
data

,OrderID,OrderDate,CustomerID,CustomerName,Region,ProductID,ProductName,Category,Quantity,Price,TotalAmount,PaymentMethod,concat,cusname,new_column,new
0,1001,5/21/2024,2,CUSTOMER_2,E,9,Product_9,Grocery,9,1047,9423,UPI,Customer_2--E,Grocery UPI,Grocery9,Grocery9423
1,1002,1/18/2024,37,CUSTOMER_37,North,19,Product_19,Home Decor,1,1563,1563,NetBanking,Customer_37--North,Home Decor NetBanking,Home Decor1,Home Decor1563
2,1003,3/28/2024,9,CUSTOMER_9,South,12,Product_12,Home Decor,4,1539,6156,COD,Customer_9--South,Home Decor COD,Home Decor4,Home Decor6156
3,1004,3/29/2024,40,CUSTOMER_40,West,14,Product_14,Grocery,3,204,612,NetBanking,Customer_40--West,Grocery NetBanking,Grocery3,Grocery612
4,1005,5/25/2024,40,CUSTOMER_40,West,14,Product_14,Grocery,9,204,1836,COD,Customer_40--West,Grocery COD,Grocery9,Grocery1836
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,1020,4/5/2024,31,CUSTOMER_31,South,2,Product_2,Home Decor,7,481,3367,NetBanking,Customer_31--South,Home Decor NetBanking,Home Decor7,Home Decor3367
266,1021,3/15/2024,38,CUSTOMER_38,North,8,Product_8,Home Decor,1,1924,1924,UPI,Customer_38--North,Home Decor UPI,Home Decor1,Home Decor1924
267,1022,3/3/2024,28,CUSTOMER_28,North,4,Product_4,Grocery,10,1380,13800,COD,Customer_28--North,Grocery COD,Grocery10,Grocery13800
268,1023,6/24/2024,35,CUSTOMER_35,East,9,Product_9,Grocery,2,1047,2094,Card,Customer_35--East,Grocery Card,Grocery2,Grocery2094
269,1024,1/5/2024,46,CUSTOMER_46,South,16,Product_16,Electronics,10,1948,19480,UPI,Customer_46--South,Electronics UPI,Electronics10,Electronics19480

In [80]:
data['CustomerName']=data['CustomerName'].str.lower()

In [81]:
data

,OrderID,OrderDate,CustomerID,CustomerName,Region,ProductID,ProductName,Category,Quantity,Price,TotalAmount,PaymentMethod,concat,cusname,new_column,new
0,1001,5/21/2024,2,customer_2,E,9,Product_9,Grocery,9,1047,9423,UPI,Customer_2--E,Grocery UPI,Grocery9,Grocery9423
1,1002,1/18/2024,37,customer_37,North,19,Product_19,Home Decor,1,1563,1563,NetBanking,Customer_37--North,Home Decor NetBanking,Home Decor1,Home Decor1563
2,1003,3/28/2024,9,customer_9,South,12,Product_12,Home Decor,4,1539,6156,COD,Customer_9--South,Home Decor COD,Home Decor4,Home Decor6156
3,1004,3/29/2024,40,customer_40,West,14,Product_14,Grocery,3,204,612,NetBanking,Customer_40--West,Grocery NetBanking,Grocery3,Grocery612
4,1005,5/25/2024,40,customer_40,West,14,Product_14,Grocery,9,204,1836,COD,Customer_40--West,Grocery COD,Grocery9,Grocery1836
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,1020,4/5/2024,31,customer_31,South,2,Product_2,Home Decor,7,481,3367,NetBanking,Customer_31--South,Home Decor NetBanking,Home Decor7,Home Decor3367
266,1021,3/15/2024,38,customer_38,North,8,Product_8,Home Decor,1,1924,1924,UPI,Customer_38--North,Home Decor UPI,Home Decor1,Home Decor1924
267,1022,3/3/2024,28,customer_28,North,4,Product_4,Grocery,10,1380,13800,COD,Customer_28--North,Grocery COD,Grocery10,Grocery13800
268,1023,6/24/2024,35,customer_35,East,9,Product_9,Grocery,2,1047,2094,Card,Customer_35--East,Grocery Card,Grocery2,Grocery2094
269,1024,1/5/2024,46,customer_46,South,16,Product_16,Electronics,10,1948,19480,UPI,Customer_46--South,Electronics UPI,Electronics10,Electronics19480

In [83]:
data['Cate']=data['Category'].str.len()

In [84]:
data

,OrderID,OrderDate,CustomerID,CustomerName,Region,ProductID,ProductName,Category,Quantity,Price,TotalAmount,PaymentMethod,concat,cusname,new_column,new,Cate
0,1001,5/21/2024,2,customer_2,E,9,Product_9,Grocery,9,1047,9423,UPI,Customer_2--E,Grocery UPI,Grocery9,Grocery9423,7
1,1002,1/18/2024,37,customer_37,North,19,Product_19,Home Decor,1,1563,1563,NetBanking,Customer_37--North,Home Decor NetBanking,Home Decor1,Home Decor1563,10
2,1003,3/28/2024,9,customer_9,South,12,Product_12,Home Decor,4,1539,6156,COD,Customer_9--South,Home Decor COD,Home Decor4,Home Decor6156,10
3,1004,3/29/2024,40,customer_40,West,14,Product_14,Grocery,3,204,612,NetBanking,Customer_40--West,Grocery NetBanking,Grocery3,Grocery612,7
4,1005,5/25/2024,40,customer_40,West,14,Product_14,Grocery,9,204,1836,COD,Customer_40--West,Grocery COD,Grocery9,Grocery1836,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,1020,4/5/2024,31,customer_31,South,2,Product_2,Home Decor,7,481,3367,NetBanking,Customer_31--South,Home Decor NetBanking,Home Decor7,Home Decor3367,10
266,1021,3/15/2024,38,customer_38,North,8,Product_8,Home Decor,1,1924,1924,UPI,Customer_38--North,Home Decor UPI,Home Decor1,Home Decor1924,10
267,1022,3/3/2024,28,customer_28,North,4,Product_4,Grocery,10,1380,13800,COD,Customer_28--North,Grocery COD,Grocery10,Grocery13800,7
268,1023,6/24/2024,35,customer_35,East,9,Product_9,Grocery,2,1047,2094,Card,Customer_35--East,Grocery Card,Grocery2,Grocery2094,7
269,1024,1/5/2024,46,customer_46,South,16,Product_16,Electronics,10,1948,19480,UPI,Customer_46--South,Electronics UPI,Electronics10,Electronics19480,11

In [87]:
data['Region']=data['Region'].str.replace("North",'N')

In [88]:
data

,OrderID,OrderDate,CustomerID,CustomerName,Region,ProductID,ProductName,Category,Quantity,Price,TotalAmount,PaymentMethod,concat,cusname,new_column,new,Cate
0,1001,5/21/2024,2,customer_2,East,9,Product_9,Grocery,9,1047,9423,UPI,Customer_2--E,Grocery UPI,Grocery9,Grocery9423,7
1,1002,1/18/2024,37,customer_37,N,19,Product_19,Home Decor,1,1563,1563,NetBanking,Customer_37--North,Home Decor NetBanking,Home Decor1,Home Decor1563,10
2,1003,3/28/2024,9,customer_9,South,12,Product_12,Home Decor,4,1539,6156,COD,Customer_9--South,Home Decor COD,Home Decor4,Home Decor6156,10
3,1004,3/29/2024,40,customer_40,West,14,Product_14,Grocery,3,204,612,NetBanking,Customer_40--West,Grocery NetBanking,Grocery3,Grocery612,7
4,1005,5/25/2024,40,customer_40,West,14,Product_14,Grocery,9,204,1836,COD,Customer_40--West,Grocery COD,Grocery9,Grocery1836,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,1020,4/5/2024,31,customer_31,South,2,Product_2,Home Decor,7,481,3367,NetBanking,Customer_31--South,Home Decor NetBanking,Home Decor7,Home Decor3367,10
266,1021,3/15/2024,38,customer_38,N,8,Product_8,Home Decor,1,1924,1924,UPI,Customer_38--North,Home Decor UPI,Home Decor1,Home Decor1924,10
267,1022,3/3/2024,28,customer_28,N,4,Product_4,Grocery,10,1380,13800,COD,Customer_28--North,Grocery COD,Grocery10,Grocery13800,7
268,1023,6/24/2024,35,customer_35,Eastast,9,Product_9,Grocery,2,1047,2094,Card,Customer_35--East,Grocery Card,Grocery2,Grocery2094,7
269,1024,1/5/2024,46,customer_46,South,16,Product_16,Electronics,10,1948,19480,UPI,Customer_46--South,Electronics UPI,Electronics10,Electronics19480,11

In [90]:
print("        pranay       ".strip())

pranay

In [91]:
print("        pranay       ".lstrip())

pranay

In [92]:
print("        pranay       ".rstrip())

        pranay

In [93]:
data['Category']=data['Category'].str.strip()

In [94]:
data

,OrderID,OrderDate,CustomerID,CustomerName,Region,ProductID,ProductName,Category,Quantity,Price,TotalAmount,PaymentMethod,concat,cusname,new_column,new,Cate
0,1001,5/21/2024,2,customer_2,East,9,Product_9,Grocery,9,1047,9423,UPI,Customer_2--E,Grocery UPI,Grocery9,Grocery9423,7
1,1002,1/18/2024,37,customer_37,N,19,Product_19,Home Decor,1,1563,1563,NetBanking,Customer_37--North,Home Decor NetBanking,Home Decor1,Home Decor1563,10
2,1003,3/28/2024,9,customer_9,South,12,Product_12,Home Decor,4,1539,6156,COD,Customer_9--South,Home Decor COD,Home Decor4,Home Decor6156,10
3,1004,3/29/2024,40,customer_40,West,14,Product_14,Grocery,3,204,612,NetBanking,Customer_40--West,Grocery NetBanking,Grocery3,Grocery612,7
4,1005,5/25/2024,40,customer_40,West,14,Product_14,Grocery,9,204,1836,COD,Customer_40--West,Grocery COD,Grocery9,Grocery1836,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,1020,4/5/2024,31,customer_31,South,2,Product_2,Home Decor,7,481,3367,NetBanking,Customer_31--South,Home Decor NetBanking,Home Decor7,Home Decor3367,10
266,1021,3/15/2024,38,customer_38,N,8,Product_8,Home Decor,1,1924,1924,UPI,Customer_38--North,Home Decor UPI,Home Decor1,Home Decor1924,10
267,1022,3/3/2024,28,customer_28,N,4,Product_4,Grocery,10,1380,13800,COD,Customer_28--North,Grocery COD,Grocery10,Grocery13800,7
268,1023,6/24/2024,35,customer_35,Eastast,9,Product_9,Grocery,2,1047,2094,Card,Customer_35--East,Grocery Card,Grocery2,Grocery2094,7
269,1024,1/5/2024,46,customer_46,South,16,Product_16,Electronics,10,1948,19480,UPI,Customer_46--South,Electronics UPI,Electronics10,Electronics19480,11

In [95]:
print("PraNaY".swapcase())

pRAnAy

In [96]:
print("pranay vishnu sudeesh".title())

Pranay Vishnu Sudeesh

In [97]:
print("pranay vishnu sudeesh".capitalize())

Pranay vishnu sudeesh

In [98]:
data

,OrderID,OrderDate,CustomerID,CustomerName,Region,ProductID,ProductName,Category,Quantity,Price,TotalAmount,PaymentMethod,concat,cusname,new_column,new,Cate
0,1001,5/21/2024,2,customer_2,East,9,Product_9,Grocery,9,1047,9423,UPI,Customer_2--E,Grocery UPI,Grocery9,Grocery9423,7
1,1002,1/18/2024,37,customer_37,N,19,Product_19,Home Decor,1,1563,1563,NetBanking,Customer_37--North,Home Decor NetBanking,Home Decor1,Home Decor1563,10
2,1003,3/28/2024,9,customer_9,South,12,Product_12,Home Decor,4,1539,6156,COD,Customer_9--South,Home Decor COD,Home Decor4,Home Decor6156,10
3,1004,3/29/2024,40,customer_40,West,14,Product_14,Grocery,3,204,612,NetBanking,Customer_40--West,Grocery NetBanking,Grocery3,Grocery612,7
4,1005,5/25/2024,40,customer_40,West,14,Product_14,Grocery,9,204,1836,COD,Customer_40--West,Grocery COD,Grocery9,Grocery1836,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,1020,4/5/2024,31,customer_31,South,2,Product_2,Home Decor,7,481,3367,NetBanking,Customer_31--South,Home Decor NetBanking,Home Decor7,Home Decor3367,10
266,1021,3/15/2024,38,customer_38,N,8,Product_8,Home Decor,1,1924,1924,UPI,Customer_38--North,Home Decor UPI,Home Decor1,Home Decor1924,10
267,1022,3/3/2024,28,customer_28,N,4,Product_4,Grocery,10,1380,13800,COD,Customer_28--North,Grocery COD,Grocery10,Grocery13800,7
268,1023,6/24/2024,35,customer_35,Eastast,9,Product_9,Grocery,2,1047,2094,Card,Customer_35--East,Grocery Card,Grocery2,Grocery2094,7
269,1024,1/5/2024,46,customer_46,South,16,Product_16,Electronics,10,1948,19480,UPI,Customer_46--South,Electronics UPI,Electronics10,Electronics19480,11

In [101]:
data['Category']=data['Category'].str.title()

In [102]:
data

,OrderID,OrderDate,CustomerID,CustomerName,Region,ProductID,ProductName,Category,Quantity,Price,TotalAmount,PaymentMethod,concat,cusname,new_column,new,Cate
0,1001,5/21/2024,2,customer_2,East,9,Product_9,Grocery,9,1047,9423,UPI,Customer_2--E,Grocery UPI,Grocery9,Grocery9423,7
1,1002,1/18/2024,37,customer_37,N,19,Product_19,Home Decor,1,1563,1563,NetBanking,Customer_37--North,Home Decor NetBanking,Home Decor1,Home Decor1563,10
2,1003,3/28/2024,9,customer_9,South,12,Product_12,Home Decor,4,1539,6156,COD,Customer_9--South,Home Decor COD,Home Decor4,Home Decor6156,10
3,1004,3/29/2024,40,customer_40,West,14,Product_14,Grocery,3,204,612,NetBanking,Customer_40--West,Grocery NetBanking,Grocery3,Grocery612,7
4,1005,5/25/2024,40,customer_40,West,14,Product_14,Grocery,9,204,1836,COD,Customer_40--West,Grocery COD,Grocery9,Grocery1836,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,1020,4/5/2024,31,customer_31,South,2,Product_2,Home Decor,7,481,3367,NetBanking,Customer_31--South,Home Decor NetBanking,Home Decor7,Home Decor3367,10
266,1021,3/15/2024,38,customer_38,N,8,Product_8,Home Decor,1,1924,1924,UPI,Customer_38--North,Home Decor UPI,Home Decor1,Home Decor1924,10
267,1022,3/3/2024,28,customer_28,N,4,Product_4,Grocery,10,1380,13800,COD,Customer_28--North,Grocery COD,Grocery10,Grocery13800,7
268,1023,6/24/2024,35,customer_35,Eastast,9,Product_9,Grocery,2,1047,2094,Card,Customer_35--East,Grocery Card,Grocery2,Grocery2094,7
269,1024,1/5/2024,46,customer_46,South,16,Product_16,Electronics,10,1948,19480,UPI,Customer_46--South,Electronics UPI,Electronics10,Electronics19480,11

In [104]:
print('123a'.isalpha())

False

In [106]:
print('123'.isalnum())

True

In [109]:
print('1'.isdigit())

True

In [114]:
print(int(str(1))+int(str(2)))

3