In [ ]:
import pandas as pd

In [ ]:
data=pd.read_csv("/content/Orders_2024_Jan_Jun.csv")

In [ ]:
print(data.to_string())

     OrderID   OrderDate  CustomerID CustomerName Region  ProductID ProductName     Category  Quantity  Price  TotalAmount PaymentMethod
0       1001   5/21/2024           2   Customer_2      E          9   Product_9      Grocery         9   1047         9423           UPI
1       1002   1/18/2024          37  Customer_37  North         19  Product_19   Home Decor         1   1563         1563    NetBanking
2       1003   3/28/2024           9   Customer_9  South         12  Product_12   Home Decor         4   1539         6156           COD
3       1004   3/29/2024          40  Customer_40   West         14  Product_14      Grocery         3    204          612    NetBanking
4       1005   5/25/2024          40  Customer_40   West         14  Product_14      Grocery         9    204         1836           COD
5       1006   6/28/2024          48  Customer_48      E         17  Product_17  Electronics         4   1320         5280           COD
6       1007   2/14/2024          25  Customer_25      E         18  Product_18   Home Decor         1   1099         1099          Card
7       1008   4/13/2024          30  Customer_30   West         12  Product_12   Home Decor        10   1539        15390    NetBanking
8       1009   4/22/2024           5   Customer_5   West         13  Product_13   Home Decor         6   1267         7602    NetBanking
9       1010   2/11/2024          39  Customer_39      E          5   Product_5  Electronics         1    632          632    NetBanking
10      1011   3/26/2024           7   Customer_7   West         17  Product_17  Electronics         6   1320         7920           COD
11      1012    4/5/2024          29  Customer_29   West          9   Product_9      Grocery         5   1047         5235           UPI
12      1013   5/22/2024          45  Customer_45      E          1   Product_1      Grocery         1    574          574          Card
13      1014   6/15/2024          16  Customer_16  North          8   Product_8   Home Decor         9   1924        17316           COD
14      1015   2/20/2024          17  Customer_17   West         17  Product_17  Electronics         2   1320         2640           COD
15      1016   5/29/2024          26  Customer_26      E          8   Product_8   Home Decor         8   1924        15392           COD
16      1017   4/26/2024          25  Customer_25      E          8   Product_8   Home Decor         6   1924        11544          Card
17      1018    5/5/2024           1   Customer_1  South          8   Product_8   Home Decor        10   1924        19240           UPI
18      1019   3/23/2024          16  Customer_16  North         14  Product_14      Grocery         3    204          612    NetBanking
19      1020    4/5/2024          31  Customer_31  South          2   Product_2   Home Decor         7    481         3367    NetBanking
20      1021   3/15/2024          38  Customer_38  North          8   Product_8   Home Decor         1   1924         1924           UPI
21      1022    3/3/2024          28  Customer_28  North          4   Product_4      Grocery        10   1380        13800           COD
22      1023   6/24/2024          35  Customer_35      E          9   Product_9      Grocery         2   1047         2094          Card
23      1024    1/5/2024          46  Customer_46  South         16  Product_16  Electronics        10   1948        19480           UPI
24      1025   3/11/2024          12  Customer_12  South          9   Product_9      Grocery         6   1047         6282           COD
25      1026   5/15/2024          48  Customer_48      E          8   Product_8   Home Decor         6   1924        11544    NetBanking
26      1027   4/18/2024           4   Customer_4  North          2   Product_2   Home Decor         4    481         1924           UPI
27      1028   2/16/2024          21  Customer_21   West         14  Product_14      Grocery         7    204         1428          Card
28      1029    2/4/2024          27  Customer_27   West         16  Product_16  Electronics         5   1948         9740          Card
29      1030    3/6/2024          36  Customer_36  South         19  Product_19   Home Decor         4   1563         6252    NetBanking
30      1031   4/12/2024           5   Customer_5   West         10  Product_10      Fashion         8    273         2184    NetBanking
31      1032   5/20/2024           5   Customer_5   West         14  Product_14      Grocery         9    204         1836    NetBanking
32      1033   2/28/2024          40  Customer_40   West         13  Product_13   Home Decor         6   1267         7602    NetBanking
33      1034   1/24/2024          16  Customer_16  North         14  Product_14      Grocery         2    204          408           UPI
34      1035   6/12/2024          48  Customer_48   East          2   Product_2   Home Decor         3    481         1443          Card
35      1036   6/27/2024          10  Customer_10  North         15  Product_15      Grocery        10    976         9760    NetBanking
36      1037   5/24/2024          49  Customer_49   West          7   Product_7      Fashion         3   1625         4875    NetBanking
37      1038    5/2/2024          23  Customer_23   West          8   Product_8   Home Decor         4   1924         7696          Card
38      1039   5/23/2024           7   Customer_7   West          5   Product_5  Electronics         1    632          632           COD
39      1040    1/5/2024          22  Customer_22  South         17  Product_17  Electronics         2   1320         2640    NetBanking
40      1041   5/28/2024           6   Customer_6   West          6   Product_6      Fashion        10   1421        14210           COD
41      1042   5/16/2024          15  Customer_15   West          8   Product_8   Home Decor         4   1924         7696          Card
42      1043   5/15/2024          44  Customer_44  North         15  Product_15      Grocery         3    976         2928           COD
43      1044   3/30/2024           8   Customer_8  North         12  Product_12   Home Decor        10   1539        15390    NetBanking
44      1045   6/11/2024          46  Customer_46  South         19  Product_19   Home Decor         2   1563         3126           COD
45      1046    3/6/2024          34  Customer_34  North         15  Product_15      Grocery         5    976         4880          Card
46      1047    1/7/2024          46  Customer_46  South         13  Product_13   Home Decor         7   1267         8869           UPI
47      1048    3/3/2024          43  Customer_43  South          9   Product_9      Grocery         2   1047         2094           COD
48      1049   6/13/2024           6   Customer_6   West         11  Product_11      Grocery         5   1093         5465    NetBanking
49      1050   1/15/2024          36  Customer_36  South          4   Product_4      Grocery         4   1380         5520          Card
50      1051   5/15/2024          43  Customer_43  South         16  Product_16  Electronics         6   1948        11688          Card
51      1052    6/3/2024          38  Customer_38  North         11  Product_11      Grocery         4   1093         4372          Card
52      1053   5/28/2024          49  Customer_49   West         12  Product_12   Home Decor         1   1539         1539          Card
53      1054   1/20/2024          45  Customer_45   East          2   Product_2   Home Decor         8    481         3848          Card
54      1055   1/11/2024           8   Customer_8  North          5   Product_5  Electronics         2    632         1264           COD
55      1056    4/8/2024          22  Customer_22  South          1   Product_1      Grocery         5    574         2870           COD
56      1057   1/26/2024          35  Customer_35   East         16  Product_16  Electronics         1   1948         1948    NetBanking
57      1058   4/19/2024          32  Customer_32   West         15  Product_15      Grocery         4    976         3904    NetBanking
58      1059   6/10/2024           6   Customer_6   West         12  Product_12   Home Decor         5   1539         7695           COD
59      1060   2/15/2024          26  Customer_26   East         16  Product_16  Electronics         6   1948        11688    NetBanking
60      1061   3/11/2024          23  Customer_23   West          8   Product_8   Home Decor         7   1924        13468           UPI
61      1062   5/31/2024          33  Customer_33  North          5   Product_5  Electronics        10    632         6320           UPI
62      1063   6/30/2024          44  Customer_44  North         20  Product_20  Electronics         5   1558         7790           COD
63      1064   6/26/2024          21  Customer_21   West          3   Product_3  Electronics        10   1214        12140    NetBanking
64      1065    5/3/2024          16  Customer_16  North         10  Product_10      Fashion         3    273          819          Card
65      1066   5/16/2024          28  Customer_28  North         13  Product_13   Home Decor         6   1267         7602           COD
66      1067    6/6/2024          38  Customer_38  North          8   Product_8   Home Decor         6   1924        11544    NetBanking
67      1068   4/20/2024          38  Customer_38  North         18  Product_18   Home Decor         3   1099         3297    NetBanking
68      1069    4/2/2024          39  Customer_39   East         15  Product_15      Grocery         5    976         4880    NetBanking
69      1070   3/15/2024          24  Customer_24   West         12  Product_12   Home Decor         6   1539         9234          Card
70      1071    2/4/2024           8   Customer_8  North         13  Product_13   Home Decor        10   1267        12670          Card
71      1072   1/27/2024          19  Customer_19      S          2   Product_2   Home Decor         1    481          481          Card
72      1073    4/7/2024          47  Customer_47   West          3   Product_3  Electronics         5   1214         6070           COD
73      1074   3/18/2024          26  Customer_26   East          7   Product_7      Fashion         6   1625         9750          Card
74      1075   4/28/2024          23  Customer_23   West         18  Product_18   Home Decor         8   1099         8792           COD
75      1076   4/27/2024          49  Customer_49   West          3   Product_3  Electronics         8   1214         9712          Card
76      1077    2/7/2024          40  Customer_40   West         12  Product_12   Home Decor         6   1539         9234           UPI
77      1078   3/31/2024           8   Customer_8  North         20  Product_20  Electronics         8   1558        12464           UPI
78      1079    5/1/2024          19  Customer_19      S         16  Product_16  Electronics         2   1948         3896          Card
79      1080   2/20/2024          15  Customer_15   West          1   Product_1      Grocery         5    574         2870          Card
80      1081    6/5/2024          12  Customer_12      S         12  Product_12   Home Decor         1   1539         1539          Card
81      1082   6/19/2024           5   Customer_5   West          2   Product_2   Home Decor         1    481          481           UPI
82      1083   4/27/2024           1   Customer_1      S          5   Product_5  Electronics        10    632         6320    NetBanking
83      1084   2/13/2024          36  Customer_36      S          4   Product_4      Grocery         5   1380         6900          Card
84      1085   3/19/2024          50  Customer_50      S          3   Product_3  Electronics         6   1214         7284          Card
85      1086   3/25/2024          47  Customer_47   West         16  Product_16  Electronics         5   1948         9740          Card
86      1087   2/16/2024          26  Customer_26   East          2   Product_2   Home Decor         2    481          962           COD
87      1088   5/14/2024           2   Customer_2   East          1   Product_1      Grocery        10    574         5740           COD
88      1089   5/12/2024          43  Customer_43      S         13  Product_13   Home Decor        10   1267        12670    NetBanking
89      1090    5/7/2024          48  Customer_48   East         10  Product_10      Fashion         4    273         1092          Card
90      1091   2/29/2024          47  Customer_47   West          9   Product_9      Grocery         4   1047         4188           COD
91      1092   3/17/2024          48  Customer_48   East          6   Product_6      Fashion         7   1421         9947           UPI
92      1093   3/13/2024          19  Customer_19      S         17  Product_17  Electronics         4   1320         5280          Card
93      1094    1/4/2024          46  Customer_46      S         19  Product_19   Home Decor        10   1563        15630          Card
94      1095   3/16/2024          39  Customer_39   East          1   Product_1      Grocery         9    574         5166    NetBanking
95      1096   1/20/2024          19  Customer_19      S         14  Product_14      Grocery         9    204         1836    NetBanking
96      1097   6/26/2024          15  Customer_15   West          4   Product_4      Grocery         2   1380         2760           COD
97      1098   3/16/2024          13  Customer_13   East         14  Product_14      Grocery         2    204          408    NetBanking
98      1099   2/15/2024          44  Customer_44  North          2   Product_2   Home Decor         9    481         4329           UPI
99      1100   2/10/2024           3   Customer_3  North         14  Product_14      Grocery         4    204          816           UPI
100     1101   2/17/2024          39  Customer_39   East          8   Product_8   Home Decor         2   1924         3848           COD
101     1102    3/2/2024          23  Customer_23   West          8   Product_8   Home Decor         8   1924        15392           UPI
102     1103   5/12/2024          26  Customer_26   East         17  Product_17  Electronics         7   1320         9240           COD
103     1104    2/9/2024          17  Customer_17   West         19  Product_19   Home Decor         5   1563         7815          Card
104     1105    4/8/2024          44  Customer_44  North          2   Product_2   Home Decor         9    481         4329    NetBanking
105     1106   1/28/2024           5   Customer_5   West          4   Product_4      Grocery         1   1380         1380           COD
106     1107    4/7/2024          25  Customer_25   East         19  Product_19   Home Decor         7   1563        10941           COD
107     1108    3/1/2024          43  Customer_43  South          1   Product_1      Grocery         5    574         2870    NetBanking
108     1109   1/23/2024          50  Customer_50  South         16  Product_16  Electronics         1   1948         1948           COD
109     1110   4/30/2024          27  Customer_27   West         10  Product_10      Fashion         8    273         2184    NetBanking
110     1111   4/27/2024          19  Customer_19  South         13  Product_13   Home Decor        10   1267        12670           UPI
111     1112   1/21/2024          10  Customer_10  North         14  Product_14      Grocery         9    204         1836           UPI
112     1113   3/28/2024          44  Customer_44  North          8   Product_8   Home Decor         8   1924        15392          Card
113     1114   5/18/2024          21  Customer_21      W          3   Product_3  Electronics         2   1214         2428    NetBanking
114     1115   5/14/2024          33  Customer_33  North         12  Product_12   Home Decor         7   1539        10773    NetBanking
115     1116    2/4/2024           1   Customer_1  South          9   Product_9      Grocery         9   1047         9423           COD
116     1117    5/4/2024          24  Customer_24      W          7   Product_7      Fashion         3   1625         4875           UPI
117     1118   6/12/2024          38  Customer_38  North          1   Product_1      Grocery         3    574         1722           COD
118     1119   2/15/2024          23  Customer_23      W          8   Product_8   Home Decor         2   1924         3848          Card
119     1120    3/2/2024          29  Customer_29      W         10  Product_10      Fashion        10    273         2730           UPI
120     1121    3/7/2024          45  Customer_45   East         17  Product_17  Electronics        10   1320        13200           UPI
121     1122   5/26/2024          43  Customer_43  South         16  Product_16  Electronics         3   1948         5844          Card
122     1123    2/5/2024          50  Customer_50  South         15  Product_15      Grocery        10    976         9760           UPI
123     1124    4/9/2024          47  Customer_47      W          4   Product_4      Grocery         1   1380         1380    NetBanking
124     1125   4/27/2024          39  Customer_39   East         16  Product_16  Electronics         5   1948         9740    NetBanking
125     1126   6/21/2024           3   Customer_3  North         17  Product_17  Electronics         8   1320        10560           UPI
126     1127    3/4/2024          46  Customer_46  South          5   Product_5  Electronics         5    632         3160           UPI
127     1128   1/10/2024          29  Customer_29   West          9   Product_9      Grocery         7   1047         7329           COD
128     1129   1/11/2024          16  Customer_16  North         14  Product_14      Grocery         7    204         1428          Card
129     1130    4/2/2024          14  Customer_14  South         15  Product_15      Grocery         5    976         4880           COD
130     1131   5/22/2024          11  Customer_11   West          1   Product_1      Grocery         9    574         5166          Card
131     1132    6/5/2024          48  Customer_48   East          8   Product_8   Home Decor         6   1924        11544          Card
132     1133    6/6/2024          32  Customer_32   West         15  Product_15      Grocery         1    976          976           UPI
133     1134   2/22/2024          30  Customer_30   West          5   Product_5  Electronics         4    632         2528          Card
134     1135   5/10/2024          40  Customer_40   West          2   Product_2   Home Decor         4    481         1924          Card
135     1136   3/14/2024          24  Customer_24   West         12  Product_12   Home Decor         7   1539        10773          Card
136     1137   5/29/2024          32  Customer_32   West         16  Product_16  Electronics        10   1948        19480           COD
137     1138    2/2/2024          38  Customer_38  North          2   Product_2   Home Decor         2    481          962           COD
138     1139   4/15/2024           1   Customer_1  South          7   Product_7      Fashion         6   1625         9750    NetBanking
139     1140   1/20/2024          43  Customer_43  South         17  Product_17  Electronics         4   1320         5280          Card
140     1141   2/28/2024          15  Customer_15   West          3   Product_3  Electronics         4   1214         4856           COD
141     1142    4/1/2024          50  Customer_50  South          1   Product_1      Grocery         1    574          574          Card
142     1143   5/31/2024          14  Customer_14  South          6   Product_6      Fashion         1   1421         1421           UPI
143     1144   5/23/2024          21  Customer_21   West         20  Product_20  Electronics         9   1558        14022    NetBanking

In [ ]:
print(data.head(2))

   OrderID  OrderDate  CustomerID CustomerName Region  ProductID ProductName  \
0     1001  5/21/2024           2   Customer_2      E          9   Product_9
1     1002  1/18/2024          37  Customer_37  North         19  Product_19

     Category  Quantity  Price  TotalAmount PaymentMethod
0     Grocery         9   1047         9423           UPI
1  Home Decor         1   1563         1563    NetBanking

In [ ]:
print(data.tail(2))

     OrderID  OrderDate  CustomerID CustomerName Region  ProductID  \
268     1023  6/24/2024          35  Customer_35   East          9
269     1024   1/5/2024          46  Customer_46  South         16

    ProductName     Category  Quantity  Price  TotalAmount PaymentMethod
268   Product_9      Grocery         2   1047         2094          Card
269  Product_16  Electronics        10   1948        19480           UPI

In [ ]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270 entries, 0 to 269
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   OrderID        270 non-null    int64
 1   OrderDate      270 non-null    object
 2   CustomerID     270 non-null    int64
 3   CustomerName   270 non-null    object
 4   Region         270 non-null    object
 5   ProductID      270 non-null    int64
 6   ProductName    270 non-null    object
 7   Category       270 non-null    object
 8   Quantity       270 non-null    int64
 9   Price          270 non-null    int64
 10  TotalAmount    270 non-null    int64
 11  PaymentMethod  270 non-null    object
dtypes: int64(6), object(6)
memory usage: 25.4+ KB
None

In [ ]:
print(data.describe())

           OrderID  CustomerID   ProductID    Quantity        Price  \
count   270.000000   270.00000  270.000000  270.000000   270.000000
mean   1254.618519    26.02963   10.814815    5.429630  1178.785185
std     365.981187    14.91684    5.634051    2.883205   546.247216
min    1001.000000     1.00000    1.000000    1.000000   204.000000
25%    1044.250000    14.00000    7.000000    3.000000   632.000000
50%    1111.500000    26.00000   11.000000    5.000000  1267.000000
75%    1178.750000    39.00000   16.000000    8.000000  1558.000000
max    2082.000000    50.00000   20.000000   10.000000  1948.000000

        TotalAmount
count    270.000000
mean    6303.011111
std     4655.061789
min      273.000000
25%     2184.000000
50%     5280.000000
75%     9699.000000
max    19480.000000

In [ ]:
print(data.shape)

(270, 12)

In [ ]:
print(data.dtypes)

OrderID           int64
OrderDate        object
CustomerID        int64
CustomerName     object
Region           object
ProductID         int64
ProductName      object
Category         object
Quantity          int64
Price             int64
TotalAmount       int64
PaymentMethod    object
dtype: object

In [ ]:
print(data.memory_usage())

Index             132
OrderID          2160
OrderDate        2160
CustomerID       2160
CustomerName     2160
Region           2160
ProductID        2160
ProductName      2160
Category         2160
Quantity         2160
Price            2160
TotalAmount      2160
PaymentMethod    2160
dtype: int64

cleaning methods

In [ ]:
print(data.isnull().sum())

OrderID          0
OrderDate        0
CustomerID       0
CustomerName     0
Region           0
ProductID        0
ProductName      0
Category         0
Quantity         0
Price            0
TotalAmount      0
PaymentMethod    0
dtype: int64

In [ ]:
data1=pd.read_csv("/content/ecommerce_dirty_data.csv")

In [ ]:
data1

,order_id,firstname,lastname,email,product,quantity,price,city,state,pincode,order_date,payment_method,status
0,1001,Sita,Reddy,sita.reddy@email.com,Camera,2.0,1500.0,Chennai,WB,500001.0,1/15/2025,Credit Card,Cancelled
1,1002,Sita,Nair,NaN,Mouse,1.0,2000.0,Bangalore,DL,600001.0,1/12/2025,NaN,Cancelled
2,1003,Kiran,Mehta,kiran.mehta@email.com,Keyboard,1.0,55000.0,Delhi,TS,500001.0,1/19/2025,COD,Cancelled
3,1004,Kiran,Singh,kiran.singh@email.com,Camera,2.0,2000.0,Kolkata,MH,380001.0,1/18/2025,COD,Pending
4,1005,Rahul,Nair,rahul.nair@email.com,Keyboard,2.0,NaN,Ahmedabad,GJ,380001.0,1/18/2025,NetBanking,Cancelled
...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,1048,Anil,Kumar,anil.kumar@email.com,Headphones,3.0,55000.0,Hyd,WB,500001.0,1/20/2025,UPI,Returned
211,1055,Priya,Das,priya.das@email.com,Mouse,2.0,1500.0,Pune,WB,600001.0,1/16/2025,NaN,Cancelled
212,1059,Kiran,Das,kiran.das@email.com,Keyboard,NaN,30000.0,Pune,TS,110001.0,1/11/2025,COD,Delivered
213,1060,Rahul,Kumar,rahul.kumar@email.com,Laptop,1.0,30000.0,Bangalore,GJ,400001.0,1/11/2025,UPI,Delivered
214,1061,Ravi,Das,ravi.das@email.com,Camera,3.0,2000.0,Mumbai,GJ,500001.0,1/20/2025,Credit card,Pending

In [ ]:
print(data1.isnull().sum())

order_id           0
firstname          0
lastname           0
email             23
product            0
quantity          43
price             40
city              20
state              0
pincode           20
order_date         0
payment_method    35
status             0
dtype: int64

In [ ]:
data1['email']=data1['email'].fillna('eswar@gmail.com')

In [ ]:
print(data1.isnull().sum())

order_id           0
firstname          0
lastname           0
email              0
product            0
quantity          43
price             40
city              20
state              0
pincode           20
order_date         0
payment_method    35
status             0
dtype: int64

In [ ]:
print(data1.to_string())

     order_id firstname lastname                   email     product  quantity    price       city state   pincode order_date payment_method     status
0        1001      Sita    Reddy    sita.reddy@email.com      Camera       2.0   1500.0    Chennai    WB  500001.0  1/15/2025    Credit Card  Cancelled
1        1002      Sita     Nair         eswar@gmail.com       Mouse       1.0   2000.0  Bangalore    DL  600001.0  1/12/2025            NaN  Cancelled
2        1003     Kiran    Mehta   kiran.mehta@email.com    Keyboard       1.0  55000.0      Delhi    TS  500001.0  1/19/2025            COD  Cancelled
3        1004     Kiran    Singh   kiran.singh@email.com      Camera       2.0   2000.0    Kolkata    MH  380001.0  1/18/2025            COD    Pending
4        1005     Rahul     Nair    rahul.nair@email.com    Keyboard       2.0      NaN  Ahmedabad    GJ  380001.0  1/18/2025     NetBanking  Cancelled
5        1006     Pooja    Verma   pooja.verma@email.com      Mobile       1.0  30000.0     Mumbai    TN  110001.0  1/16/2025     NetBanking    Pending
6        1007     Rahul      Das     rahul.das@email.com     Charger       1.0   1500.0     Mumbai    TN  400001.0  1/18/2025            NaN   Returned
7        1008     Sneha    Verma   sneha.verma@email.com      Laptop       NaN      NaN  Hyderabad    MH  380001.0  1/20/2025            Upi    Pending
8        1009      Anil      Das      anil.das@email.com     Charger       NaN  30000.0    Kolkata    WB  560001.0  1/11/2025            NaN   Returned
9        1010      Sita     Nair     sita.nair@email.com  Headphones       1.0   2000.0     Mumbai    TN       NaN  1/14/2025     NetBanking  Delivered
10       1011     Vikas    Patel   vikas.patel@email.com      Tablet       2.0   2000.0    Kolkata    GJ  380001.0  1/13/2025            NaN  Delivered
11       1012     Priya    Kumar   priya.kumar@email.com  Headphones       2.0  30000.0     Mumbai    MH  500001.0  1/16/2025     NetBanking   Returned
12       1013      Sita    Singh    sita.singh@email.com       Mouse       1.0  30000.0      Delhi    GJ  600001.0  1/14/2025            COD  Delivered
13       1014     Priya    Reddy   priya.reddy@email.com      Camera       1.0      NaN        NaN    TN  110001.0  1/18/2025            COD   Returned
14       1015     Sneha    Verma   sneha.verma@email.com       Mouse       2.0  30000.0       Pune    TS  110001.0  1/10/2025            NaN   Returned
15       1016      Amit   Sharma   amit.sharma@email.com    Keyboard       NaN  55000.0  Bangalore    MH  400001.0  1/17/2025    Credit Card  Delivered
16       1017     Kiran   Sharma  kiran.sharma@email.com    Keyboard       3.0   1500.0    Chennai    WB  560001.0  1/10/2025            Upi    Pending
17       1018     Rahul    Verma   rahul.verma@email.com     Charger       3.0  55000.0  Bangalore    MH  110001.0  1/20/2025            Upi   Returned
18       1019     Pooja   Sharma  pooja.sharma@email.com  Headphones       1.0   2000.0        NaN    WB  380001.0  1/17/2025     NetBanking  Delivered
19       1020      Anil    Singh    anil.singh@email.com      Laptop       3.0   1500.0      Delhi    KA  560001.0  1/11/2025     NetBanking   Returned
20       1021     Rahul    Kumar   rahul.kumar@email.com      Mobile       3.0   2000.0        Hyd    GJ  380001.0  1/17/2025    Credit Card  Delivered
21       1022      Amit    Verma    amit.verma@email.com    Keyboard       2.0  30000.0     Mumbai    GJ  110001.0  1/13/2025            Upi    Pending
22       1023     Sneha    Verma         eswar@gmail.com      Tablet       NaN  30000.0       Pune    KA  400001.0  1/15/2025            Upi    Pending
23       1024     Pooja   Sharma  pooja.sharma@email.com      Camera       1.0      NaN    Chennai    KA  560001.0  1/18/2025            Upi  Delivered
24       1025     Kiran    Mehta   kiran.mehta@email.com      Tablet       3.0  30000.0     Mumbai    GJ  500001.0  1/15/2025            COD  Delivered
25       1026      Anil    Reddy    anil.reddy@email.com  Headphones       2.0   2000.0    Kolkata    GJ  400001.0  1/15/2025     NetBanking  Delivered
26       1027      Sita   Sharma   sita.sharma@email.com      Laptop       2.0  55000.0       Pune    DL       NaN  1/15/2025            COD  Cancelled
27       1028      Sita    Mehta    sita.mehta@email.com     Charger       1.0   1500.0  Bangalore    WB  380001.0  1/14/2025            Upi  Delivered
28       1029     Sneha    Reddy   sneha.reddy@email.com      Laptop       1.0   1500.0       Pune    TS       NaN  1/18/2025     NetBanking  Delivered
29       1030      Amit    Patel         eswar@gmail.com     Charger       1.0      NaN  Ahmedabad    TS  560001.0  1/10/2025    Credit Card  Cancelled
30       1031     Vikas    Kumar   vikas.kumar@email.com      Tablet       3.0  55000.0     Mumbai    DL  500001.0  1/16/2025            COD    Pending
31       1032     Priya     Nair    priya.nair@email.com       Mouse       2.0      NaN    Kolkata    TS  600001.0  1/16/2025            NaN   Returned
32       1033     Priya    Patel   priya.patel@email.com    Keyboard       NaN   1500.0      Delhi    TS  380001.0  1/19/2025            COD  Delivered
33       1034     Rahul    Kumar   rahul.kumar@email.com     Charger       NaN   2000.0      Delhi    GJ  560001.0  1/13/2025            Upi  Delivered
34       1035     Priya    Gupta         eswar@gmail.com      Tablet       3.0  30000.0       Pune    KA  380001.0  1/19/2025    Credit Card  Delivered
35       1036      Anil    Gupta    anil.gupta@email.com      Camera       3.0  30000.0      Delhi    MH       NaN  1/11/2025            COD    Pending
36       1037      Amit    Verma    amit.verma@email.com      Tablet       1.0      NaN      Delhi    TS  110001.0  1/14/2025            NaN   Returned
37       1038      Ravi    Mehta    ravi.mehta@email.com    Keyboard       3.0  30000.0  Ahmedabad    TN  560001.0  1/15/2025     NetBanking   Returned
38       1039      Amit      Das      amit.das@email.com      Camera       2.0  30000.0  Ahmedabad    TN  560001.0  1/18/2025            COD  Delivered
39       1040      Anil    Gupta    anil.gupta@email.com      Mobile       NaN  30000.0      Delhi    GJ  600001.0  1/14/2025            Upi  Cancelled
40       1041      Sita    Singh    sita.singh@email.com  Headphones       1.0   1500.0        Hyd    TS  560001.0  1/11/2025    Credit card    Pending
41       1042     Sneha      Das     sneha.das@email.com  Headphones       1.0   1500.0    Chennai    KA  400001.0  1/15/2025    Credit card  Cancelled
42       1043      Amit     Nair     amit.nair@email.com      Mobile       2.0   2000.0        NaN    TS  600001.0  1/15/2025            COD    Pending
43       1044     Kiran    Gupta   kiran.gupta@email.com      Tablet       3.0  55000.0        NaN    KA  110001.0  1/14/2025    Credit card   Returned
44       1045     Pooja   Sharma  pooja.sharma@email.com    Keyboard       NaN  30000.0  Ahmedabad    TS  500001.0  1/10/2025    Credit card  Cancelled
45       1046      Amit    Kumar    amit.kumar@email.com  Headphones       NaN      NaN      Delhi    TS  500001.0  1/16/2025     NetBanking    Pending
46       1047     Priya      Das     priya.das@email.com      Mobile       1.0   2000.0     Mumbai    WB  380001.0  1/16/2025     NetBanking  Delivered
47       1048      Anil    Kumar    anil.kumar@email.com  Headphones       3.0  55000.0        Hyd    WB  500001.0  1/20/2025            UPI   Returned
48       1049      Amit      Das      amit.das@email.com     Charger       NaN      NaN  Ahmedabad    MH  600001.0  1/19/2025    Credit card  Delivered
49       1050      Anil    Mehta    anil.mehta@email.com      Laptop       3.0      NaN    Kolkata    WB  600001.0  1/18/2025     NetBanking  Cancelled
50       1051      Anil     Nair     anil.nair@email.com     Charger       NaN  30000.0     Mumbai    MH  560001.0  1/15/2025            NaN  Delivered
51       1052      Sita    Gupta         eswar@gmail.com       Mouse       2.0      NaN     Mumbai    MH  110001.0  1/14/2025     NetBanking   Returned
52       1053      Ravi    Singh    ravi.singh@email.com     Charger       3.0  55000.0      Delhi    WB       NaN  1/18/2025    Credit card    Pending
53       1054     Rahul    Patel         eswar@gmail.com      Tablet       3.0      NaN        NaN    GJ  560001.0  1/20/2025     NetBanking   Returned
54       1055     Priya      Das     priya.das@email.com       Mouse       2.0   1500.0       Pune    WB  600001.0  1/16/2025            NaN  Cancelled
55       1056      Amit     Nair         eswar@gmail.com    Keyboard       3.0  55000.0  Bangalore    GJ  500001.0  1/10/2025    Credit card  Cancelled
56       1057      Anil    Verma         eswar@gmail.com  Headphones       NaN  30000.0      Delhi    KA  400001.0  1/16/2025            COD  Cancelled
57       1058      Sita    Mehta    sita.mehta@email.com  Headphones       2.0   1500.0      Delhi    MH  380001.0  1/19/2025     NetBanking   Returned
58       1059     Kiran      Das     kiran.das@email.com    Keyboard       NaN  30000.0       Pune    TS  110001.0  1/11/2025            COD  Delivered
59       1060     Rahul    Kumar   rahul.kumar@email.com      Laptop       1.0  30000.0  Bangalore    GJ  400001.0  1/11/2025            UPI  Delivered
60       1061      Ravi      Das      ravi.das@email.com      Camera       3.0   2000.0     Mumbai    GJ  500001.0  1/20/2025    Credit card    Pending
61       1062      Ravi    Kumar         eswar@gmail.com      Camera       3.0   1500.0  Hyderabad    MH  400001.0  1/14/2025    Credit Card    Pending
62       1063     Vikas    Singh   vikas.singh@email.com      Mobile       NaN      NaN    Chennai    DL  110001.0  1/13/2025            COD    Pending
63       1064      Anil    Gupta    anil.gupta@email.com      Laptop       1.0  30000.0      Delhi    TS  110001.0  1/12/2025            COD  Cancelled
64       1065     Pooja    Singh   pooja.singh@email.com       Mouse       1.0   1500.0  Bangalore    WB  500001.0  1/18/2025            COD    Pending
65       1066     Pooja    Verma   pooja.verma@email.com      Mobile       2.0      NaN       Pune    MH       NaN  1/12/2025    Credit Card  Delivered
66       1067     Priya    Singh         eswar@gmail.com      Camera       3.0  30000.0       Pune    GJ  560001.0  1/12/2025     NetBanking  Delivered
67       1068      Sita    Kumar    sita.kumar@email.com      Camera       1.0  30000.0    Kolkata    GJ  380001.0  1/11/2025            NaN  Delivered
68       1069     Vikas   Sharma  vikas.sharma@email.com       Mouse       3.0  55000.0  Hyderabad    MH  560001.0  1/16/2025     NetBanking   Returned
69       1070      Ravi    Reddy    ravi.reddy@email.com      Laptop       1.0  55000.0  Ahmedabad    KA  560001.0  1/17/2025     NetBanking   Returned
70       1071     Kiran    Kumar   kiran.kumar@email.com       Mouse       3.0  30000.0  Ahmedabad    DL  500001.0  1/10/2025            UPI  Cancelled
71       1072      Ravi    Mehta    ravi.mehta@email.com      Camera       3.0  30000.0      Delhi    TN  560001.0  1/15/2025     NetBanking  Delivered
72       1073      Ravi     Nair     ravi.nair@email.com     Charger       2.0  55000.0       Pune    MH  560001.0  1/18/2025            COD    Pending
73       1074      Sita      Das      sita.das@email.com      Mobile       NaN      NaN        NaN    MH  560001.0  1/10/2025     NetBanking  Delivered
74       1075     Vikas    Kumar   vikas.kumar@email.com    Keyboard       2.0  30000.0        NaN    KA  560001.0  1/15/2025            COD    Pending
75       1076      Amit    Patel    amit.patel@email.com      Laptop       3.0  30000.0  Bangalore    TS  500001.0  1/10/2025    Credit Card   Returned
76       1077     Priya    Patel   priya.patel@email.com  Headphones       2.0  30000.0        NaN    TN  560001.0  1/14/2025     NetBanking  Delivered
77       1078     Priya    Singh   priya.singh@email.com    Keyboard       NaN  30000.0       Pune    MH  560001.0  1/16/2025    Credit Card   Returned
78       1079     Pooja    Patel   pooja.patel@email.com      Mobile       3.0   1500.0     Mumbai    DL  500001.0  1/15/2025            NaN  Cancelled
79       1080      Amit    Mehta    amit.mehta@email.com      Camera       2.0   1500.0    Chennai    TN  400001.0  1/17/2025            COD  Cancelled
80       1081      Anil    Mehta    anil.mehta@email.com      Camera       NaN  55000.0  Ahmedabad    TN  400001.0  1/17/2025     NetBanking  Delivered
81       1082     Vikas    Mehta   vikas.mehta@email.com      Laptop       NaN   1500.0  Hyderabad    GJ  600001.0  1/20/2025            NaN   Returned
82       1083     Rahul   Sharma  rahul.sharma@email.com    Keyboard       2.0   2000.0     Mumbai    TS  380001.0  1/17/2025            NaN   Returned
83       1084     Pooja    Singh   pooja.singh@email.com  Headphones       3.0      NaN       Bang    TN  400001.0  1/19/2025    Credit Card    Pending
84       1085      Anil    Patel    anil.patel@email.com      Mobile       3.0  30000.0       Bang    DL  600001.0  1/11/2025    Credit Card   Returned
85       1086     Pooja    Patel   pooja.patel@email.com    Keyboard       1.0  55000.0    Chennai    MH  110001.0  1/15/2025            COD    Pending
86       1087     Kiran    Verma   kiran.verma@email.com      Mobile       NaN   1500.0       Bang    WB  560001.0  1/20/2025            UPI   Returned
87       1088      Sita    Kumar    sita.kumar@email.com      Mobile       1.0  55000.0  Hyderabad    MH  380001.0  1/11/2025    Credit Card   Returned
88       1089     Sneha    Singh         eswar@gmail.com    Keyboard       NaN  30000.0      Delhi    MH  600001.0  1/16/2025            COD   Returned
89       1090      Amit    Mehta    amit.mehta@email.com     Charger       2.0      NaN  Ahmedabad    TS  380001.0  1/15/2025    Credit Card  Cancelled
90       1091     Pooja    Kumar   pooja.kumar@email.com       Mouse       2.0      NaN    Kolkata    TN  560001.0  1/15/2025            COD  Delivered
91       1092      Anil    Mehta    anil.mehta@email.com  Headphones       2.0   1500.0        NaN    KA  380001.0  1/20/2025            UPI  Cancelled
92       1093     Kiran   Sharma  kiran.sharma@email.com     Charger       NaN   1500.0       Bang    DL  110001.0  1/17/2025            COD    Pending
93       1094     Kiran    Kumar   kiran.kumar@email.com      Tablet       1.0  30000.0       Pune    TN  110001.0  1/19/2025            COD  Delivered
94       1095      Sita    Kumar    sita.kumar@email.com      Tablet       NaN   2000.0        NaN    KA  400001.0  1/14/2025            NaN   Returned
95       1096     Kiran    Reddy   kiran.reddy@email.com    Keyboard       NaN  30000.0  Hyderabad    WB  500001.0  1/14/2025            COD    Pending
96       1097     Kiran    Kumar         eswar@gmail.com      Tablet       1.0  55000.0    Kolkata    TS  560001.0  1/20/2025            COD    Pending
97       1098     Kiran    Reddy   kiran.reddy@email.com     Charger       3.0  55000.0  Ahmedabad    MH       NaN  1/17/2025            NaN    Pending
98       1099      Amit    Verma    amit.verma@email.com      Camera       1.0  30000.0       Bang    WB  380001.0  1/20/2025            UPI  Delivered
99       1100     Sneha   Sharma  sneha.sharma@email.com      Laptop       3.0  55000.0  Bangalore    GJ  600001.0  1/11/2025     NetBanking   Returned
100      1101     Priya    Patel   priya.patel@email.com      Tablet       NaN   2000.0     Mumbai    DL  110001.0  1/10/2025            NaN   Returned
101      1102     Pooja    Reddy   pooja.reddy@email.com       Mouse       1.0      NaN        NaN    TN  560001.0  1/13/2025            COD  Cancelled
102      1103     Sneha    Mehta   sneha.mehta@email.com    Keyboard       3.0   1500.0  Bangalore    WB  500001.0  1/12/2025            UPI  Delivered
103      1104      Sita    Verma    sita.verma@email.com      Laptop       3.0  55000.0  Hyderabad    KA       NaN  1/13/2025    Credit Card    Pending
104      1105      Anil   Sharma   anil.sharma@email.com      Laptop       1.0   1500.0  Bangalore    MH  400001.0  1/11/2025            COD    Pending
105      1106     Vikas    Kumar   vikas.kumar@email.com      Laptop       3.0      NaN    Kolkata    TN  500001.0  1/12/2025     NetBanking  Delivered
106      1107     Kiran   Sharma         eswar@gmail.com      Camera       2.0   2000.0    Kolkata    TN  600001.0  1/20/2025            NaN    Pending
107      1108     Vikas      Das     vikas.das@email.com      Camera       3.0  55000.0    Chennai    KA  380001.0  1/19/2025     NetBanking    Pending
108      1109      Amit   Sharma   amit.sharma@email.com      Laptop       3.0      NaN  Bangalore    TN  400001.0  1/14/2025     NetBanking   Returned
109      1110      Amit    Patel    amit.patel@email.com      Mobile       NaN   2000.0    Kolkata    MH  380001.0  1/11/2025            NaN  Delivered
110      1111     Pooja    Patel   pooja.patel@email.com     Charger       3.0   2000.0  Hyderabad    DL  560001.0  1/14/2025            NaN    Pending
111      1112     Rahul    Mehta   rahul.mehta@email.com    Keyboard       3.0   2000.0        NaN    KA  380001.0  1/14/2025            COD  Cancelled
112      1113     Kiran      Das     kiran.das@email.com      Tablet       1.0   1500.0  Hyderabad    GJ  500001.0  1/15/2025            COD    Pending
113      1114      Anil    Patel    anil.patel@email.com      Laptop       2.0      NaN  Ahmedabad    TN  110001.0  1/10/2025     NetBanking  Delivered
114      1115     Pooja    Patel   pooja.patel@email.com  Headphones       1.0      NaN    Kolkata    TN  500001.0  1/10/2025            UPI   Returned
115      1116     Pooja      Das     pooja.das@email.com       Mouse       NaN      NaN       Pune    GJ  380001.0  1/10/2025    Credit Card    Pending
116      1117     Pooja    Singh   pooja.singh@email.com      Tablet       3.0   2000.0  Hyderabad    WB  560001.0  1/10/2025            UPI    Pending
117      1118      Amit    Reddy         eswar@gmail.com      Tablet       NaN  30000.0       Pune    MH  500001.0  1/19/2025            NaN    Pending
118      1119      Amit    Reddy    amit.reddy@email.com       Mouse       2.0   2000.0        NaN    KA  400001.0  1/20/2025    Credit Card    Pending
119      1120      Ravi      Das      ravi.das@email.com      Mobile       3.0   1500.0  Ahmedabad    GJ  500001.0  1/20/2025            UPI    Pending
120      1121     Pooja      Das     pooja.das@email.com  Headphones       3.0      NaN      Delhi    MH  110001.0  1/17/2025            NaN   Returned
121      1122      Ravi    Gupta    ravi.gupta@email.com  Headphones       1.0      NaN     Mumbai    TN  110001.0  1/18/2025     NetBanking    Pending
122      1123     Vikas    Patel   vikas.patel@email.com    Keyboard       3.0   1500.0  Hyderabad    TN  560001.0  1/17/2025     NetBanking   Returned
123      1124     Sneha    Kumar   sneha.kumar@email.com      Laptop       2.0  30000.0    Kolkata    MH       NaN  1/17/2025            UPI  Delivered
124      1125      Sita   Sharma   sita.sharma@email.com      Camera       2.0  55000.0     Mumbai    TN  110001.0  1/15/2025            COD  Delivered
125      1126     Rahul    Reddy   rahul.reddy@email.com  Headphones       3.0   1500.0      Delhi    TN  600001.0  1/20/2025    Credit Card  Delivered
126      1127      Anil      Das      anil.das@email.com    Keyboard       3.0      NaN  Hyderabad    DL  400001.0  1/18/2025            UPI  Cancelled
127      1128     Pooja    Reddy   pooja.reddy@email.com      Laptop       2.0   2000.0      Delhi    TN  560001.0  1/13/2025            COD    Pending
128      1129     Kiran    Mehta   kiran.mehta@email.com     Charger       1.0   1500.0    Chennai    TN  560001.0  1/20/2025     NetBanking   Returned
129      1130     Rahul    Verma   rahul.verma@email.com  Headphones       3.0      NaN        NaN    WB  560001.0  1/14/2025            UPI  Cancelled

In [ ]:
print(data1.isnull().sum())

order_id           0
firstname          0
lastname           0
email              0
product            0
quantity          43
price             40
city              20
state              0
pincode           20
order_date         0
payment_method    35
status             0
dtype: int64

In [ ]:
data1['quantity']=data1['quantity'].ffill()

In [ ]:
print(data1.isnull().sum())

order_id           0
firstname          0
lastname           0
email              0
product            0
quantity           0
price             40
city              20
state              0
pincode           20
order_date         0
payment_method    35
status             0
dtype: int64

In [ ]:
data1['city']=data1['city'].bfill()

In [ ]:
print(data1.isnull().sum())

order_id           0
firstname          0
lastname           0
email              0
product            0
quantity           0
price             40
city               0
state              0
pincode           20
order_date         0
payment_method    35
status             0
dtype: int64

In [ ]:
data1['price']=data1['price'].bfill()

In [ ]:
data1['pincode']=data1['pincode'].ffill()

In [ ]:
print(data1.isnull().sum())

order_id           0
firstname          0
lastname           0
email              0
product            0
quantity           0
price              0
city               0
state              0
pincode            0
order_date         0
payment_method    35
status             0
dtype: int64

In [ ]:
print(data1.shape)

(215, 13)

In [ ]:
data1=data1.dropna()

In [ ]:
print(data1.isnull().sum())

order_id          0
firstname         0
lastname          0
email             0
product           0
quantity          0
price             0
city              0
state             0
pincode           0
order_date        0
payment_method    0
status            0
dtype: int64

In [ ]:
print(data1.shape)

(180, 13)

In [ ]:
print(data1.duplicated().sum())

11

In [ ]:
data1=data1.drop_duplicates()

In [ ]:
print(data1.shape)

(169, 13)

In [ ]:
print(data1.dtypes)

order_id            int64
firstname          object
lastname           object
email              object
product            object
quantity          float64
price             float64
city               object
state              object
pincode           float64
order_date         object
payment_method     object
status             object
dtype: object

In [ ]:
data1['order_id']=data1['order_id'].astype(str)

In [ ]:
print(data1.dtypes)

order_id           object
firstname          object
lastname           object
email              object
product            object
quantity          float64
price             float64
city               object
state              object
pincode           float64
order_date         object
payment_method     object
status             object
dtype: object

In [ ]:
print(data1)

    order_id firstname lastname                  email     product  quantity  \
0       1001      Sita    Reddy   sita.reddy@email.com      Camera       2.0
2       1003     Kiran    Mehta  kiran.mehta@email.com    Keyboard       1.0
3       1004     Kiran    Singh  kiran.singh@email.com      Camera       2.0
4       1005     Rahul     Nair   rahul.nair@email.com    Keyboard       2.0
5       1006     Pooja    Verma  pooja.verma@email.com      Mobile       1.0
..       ...       ...      ...                    ...         ...       ...
197     1198     Vikas    Kumar        eswar@gmail.com      Camera       1.0
198     1199      Amit    Reddy   amit.reddy@email.com      Camera       2.0
199     1200     Pooja    Gupta  pooja.gupta@email.com      Tablet       2.0
201     1042     Sneha      Das    sneha.das@email.com  Headphones       1.0
204     1028      Sita    Mehta   sita.mehta@email.com     Charger       1.0

       price       city state   pincode order_date payment_method     status
0     1500.0    Chennai    WB  500001.0  1/15/2025    Credit Card  Cancelled
2    55000.0      Delhi    TS  500001.0  1/19/2025            COD  Cancelled
3     2000.0    Kolkata    MH  380001.0  1/18/2025            COD    Pending
4    30000.0  Ahmedabad    GJ  380001.0  1/18/2025     NetBanking  Cancelled
5    30000.0     Mumbai    TN  110001.0  1/16/2025     NetBanking    Pending
..       ...        ...   ...       ...        ...            ...        ...
197  55000.0  Hyderabad    KA  560001.0  1/16/2025     NetBanking  Delivered
198  30000.0  Hyderabad    KA  600001.0  1/11/2025            COD    Pending
199  30000.0  Ahmedabad    KA  600001.0  1/15/2025            UPI  Delivered
201   1500.0    Chennai    KA  400001.0  1/15/2025    Credit Card  Cancelled
204   1500.0  Bangalore    WB  380001.0  1/14/2025            UPI  Delivered

[169 rows x 13 columns]

In [ ]:
data1['firstname']=data1['firstname'].replace("Sita","Eswar")

In [ ]:
print(data1)

    order_id firstname lastname                  email     product  quantity  \
0       1001     Eswar    Reddy   sita.reddy@email.com      Camera       2.0
2       1003     Kiran    Mehta  kiran.mehta@email.com    Keyboard       1.0
3       1004     Kiran    Singh  kiran.singh@email.com      Camera       2.0
4       1005     Rahul     Nair   rahul.nair@email.com    Keyboard       2.0
5       1006     Pooja    Verma  pooja.verma@email.com      Mobile       1.0
..       ...       ...      ...                    ...         ...       ...
197     1198     Vikas    Kumar        eswar@gmail.com      Camera       1.0
198     1199      Amit    Reddy   amit.reddy@email.com      Camera       2.0
199     1200     Pooja    Gupta  pooja.gupta@email.com      Tablet       2.0
201     1042     Sneha      Das    sneha.das@email.com  Headphones       1.0
204     1028     Eswar    Mehta   sita.mehta@email.com     Charger       1.0

       price       city state   pincode order_date payment_method     status
0     1500.0    Chennai    WB  500001.0  1/15/2025    Credit Card  Cancelled
2    55000.0      Delhi    TS  500001.0  1/19/2025            COD  Cancelled
3     2000.0    Kolkata    MH  380001.0  1/18/2025            COD    Pending
4    30000.0  Ahmedabad    GJ  380001.0  1/18/2025     NetBanking  Cancelled
5    30000.0     Mumbai    TN  110001.0  1/16/2025     NetBanking    Pending
..       ...        ...   ...       ...        ...            ...        ...
197  55000.0  Hyderabad    KA  560001.0  1/16/2025     NetBanking  Delivered
198  30000.0  Hyderabad    KA  600001.0  1/11/2025            COD    Pending
199  30000.0  Ahmedabad    KA  600001.0  1/15/2025            UPI  Delivered
201   1500.0    Chennai    KA  400001.0  1/15/2025    Credit Card  Cancelled
204   1500.0  Bangalore    WB  380001.0  1/14/2025            UPI  Delivered

[169 rows x 13 columns]

In [ ]:
data1['email']=data1['email'].replace("sita.reddy@email.com",'e@gmail.com')

In [ ]:
print(data1)

    order_id firstname lastname                  email     product  quantity  \
0       1001     Eswar    Reddy            e@gmail.com      Camera       2.0
2       1003     Kiran    Mehta  kiran.mehta@email.com    Keyboard       1.0
3       1004     Kiran    Singh  kiran.singh@email.com      Camera       2.0
4       1005     Rahul     Nair   rahul.nair@email.com    Keyboard       2.0
5       1006     Pooja    Verma  pooja.verma@email.com      Mobile       1.0
..       ...       ...      ...                    ...         ...       ...
197     1198     Vikas    Kumar        eswar@gmail.com      Camera       1.0
198     1199      Amit    Reddy   amit.reddy@email.com      Camera       2.0
199     1200     Pooja    Gupta  pooja.gupta@email.com      Tablet       2.0
201     1042     Sneha      Das    sneha.das@email.com  Headphones       1.0
204     1028     Eswar    Mehta   sita.mehta@email.com     Charger       1.0

       price       city state   pincode order_date payment_method     status
0     1500.0    Chennai    WB  500001.0  1/15/2025    Credit Card  Cancelled
2    55000.0      Delhi    TS  500001.0  1/19/2025            COD  Cancelled
3     2000.0    Kolkata    MH  380001.0  1/18/2025            COD    Pending
4    30000.0  Ahmedabad    GJ  380001.0  1/18/2025     NetBanking  Cancelled
5    30000.0     Mumbai    TN  110001.0  1/16/2025     NetBanking    Pending
..       ...        ...   ...       ...        ...            ...        ...
197  55000.0  Hyderabad    KA  560001.0  1/16/2025     NetBanking  Delivered
198  30000.0  Hyderabad    KA  600001.0  1/11/2025            COD    Pending
199  30000.0  Ahmedabad    KA  600001.0  1/15/2025            UPI  Delivered
201   1500.0    Chennai    KA  400001.0  1/15/2025    Credit Card  Cancelled
204   1500.0  Bangalore    WB  380001.0  1/14/2025            UPI  Delivered

[169 rows x 13 columns]

In [ ]:
data1.columns

Index(['order_id', 'firstname', 'lastname', 'email', 'product', 'quantity',
       'price', 'city', 'state', 'pincode', 'order_date', 'payment_method',
       'status'],
      dtype='object')

In [ ]:
print(data1[['product','order_id','email','quantity']])

        product order_id                  email  quantity
0        Camera     1001            e@gmail.com       2.0
2      Keyboard     1003  kiran.mehta@email.com       1.0
3        Camera     1004  kiran.singh@email.com       2.0
4      Keyboard     1005   rahul.nair@email.com       2.0
5        Mobile     1006  pooja.verma@email.com       1.0
..          ...      ...                    ...       ...
197      Camera     1198        eswar@gmail.com       1.0
198      Camera     1199   amit.reddy@email.com       2.0
199      Tablet     1200  pooja.gupta@email.com       2.0
201  Headphones     1042    sneha.das@email.com       1.0
204     Charger     1028   sita.mehta@email.com       1.0

[169 rows x 4 columns]

In [ ]:
print(data1.to_string())

    order_id firstname lastname                   email     product  quantity    price       city state   pincode order_date payment_method     status
0       1001     Eswar    Reddy             e@gmail.com      Camera       2.0   1500.0    Chennai    WB  500001.0  1/15/2025    Credit Card  Cancelled
2       1003     Kiran    Mehta   kiran.mehta@email.com    Keyboard       1.0  55000.0      Delhi    TS  500001.0  1/19/2025            COD  Cancelled
3       1004     Kiran    Singh   kiran.singh@email.com      Camera       2.0   2000.0    Kolkata    MH  380001.0  1/18/2025            COD    Pending
4       1005     Rahul     Nair    rahul.nair@email.com    Keyboard       2.0  30000.0  Ahmedabad    GJ  380001.0  1/18/2025     NetBanking  Cancelled
5       1006     Pooja    Verma   pooja.verma@email.com      Mobile       1.0  30000.0     Mumbai    TN  110001.0  1/16/2025     NetBanking    Pending
7       1008     Sneha    Verma   sneha.verma@email.com      Laptop       1.0  30000.0  Hyderabad    MH  380001.0  1/20/2025            Upi    Pending
9       1010     Eswar     Nair     sita.nair@email.com  Headphones       1.0   2000.0     Mumbai    TN  560001.0  1/14/2025     NetBanking  Delivered
11      1012     Priya    Kumar   priya.kumar@email.com  Headphones       2.0  30000.0     Mumbai    MH  500001.0  1/16/2025     NetBanking   Returned
12      1013     Eswar    Singh    sita.singh@email.com       Mouse       1.0  30000.0      Delhi    GJ  600001.0  1/14/2025            COD  Delivered
13      1014     Priya    Reddy   priya.reddy@email.com      Camera       1.0  30000.0       Pune    TN  110001.0  1/18/2025            COD   Returned
15      1016      Amit   Sharma   amit.sharma@email.com    Keyboard       2.0  55000.0  Bangalore    MH  400001.0  1/17/2025    Credit Card  Delivered
16      1017     Kiran   Sharma  kiran.sharma@email.com    Keyboard       3.0   1500.0    Chennai    WB  560001.0  1/10/2025            Upi    Pending
17      1018     Rahul    Verma   rahul.verma@email.com     Charger       3.0  55000.0  Bangalore    MH  110001.0  1/20/2025            Upi   Returned
18      1019     Pooja   Sharma  pooja.sharma@email.com  Headphones       1.0   2000.0      Delhi    WB  380001.0  1/17/2025     NetBanking  Delivered
19      1020      Anil    Singh    anil.singh@email.com      Laptop       3.0   1500.0      Delhi    KA  560001.0  1/11/2025     NetBanking   Returned
20      1021     Rahul    Kumar   rahul.kumar@email.com      Mobile       3.0   2000.0        Hyd    GJ  380001.0  1/17/2025    Credit Card  Delivered
21      1022      Amit    Verma    amit.verma@email.com    Keyboard       2.0  30000.0     Mumbai    GJ  110001.0  1/13/2025            Upi    Pending
22      1023     Sneha    Verma         eswar@gmail.com      Tablet       2.0  30000.0       Pune    KA  400001.0  1/15/2025            Upi    Pending
23      1024     Pooja   Sharma  pooja.sharma@email.com      Camera       1.0  30000.0    Chennai    KA  560001.0  1/18/2025            Upi  Delivered
24      1025     Kiran    Mehta   kiran.mehta@email.com      Tablet       3.0  30000.0     Mumbai    GJ  500001.0  1/15/2025            COD  Delivered
25      1026      Anil    Reddy    anil.reddy@email.com  Headphones       2.0   2000.0    Kolkata    GJ  400001.0  1/15/2025     NetBanking  Delivered
26      1027     Eswar   Sharma   sita.sharma@email.com      Laptop       2.0  55000.0       Pune    DL  400001.0  1/15/2025            COD  Cancelled
27      1028     Eswar    Mehta    sita.mehta@email.com     Charger       1.0   1500.0  Bangalore    WB  380001.0  1/14/2025            Upi  Delivered
28      1029     Sneha    Reddy   sneha.reddy@email.com      Laptop       1.0   1500.0       Pune    TS  380001.0  1/18/2025     NetBanking  Delivered
29      1030      Amit    Patel         eswar@gmail.com     Charger       1.0  55000.0  Ahmedabad    TS  560001.0  1/10/2025    Credit Card  Cancelled
30      1031     Vikas    Kumar   vikas.kumar@email.com      Tablet       3.0  55000.0     Mumbai    DL  500001.0  1/16/2025            COD    Pending
32      1033     Priya    Patel   priya.patel@email.com    Keyboard       2.0   1500.0      Delhi    TS  380001.0  1/19/2025            COD  Delivered
33      1034     Rahul    Kumar   rahul.kumar@email.com     Charger       2.0   2000.0      Delhi    GJ  560001.0  1/13/2025            Upi  Delivered
34      1035     Priya    Gupta         eswar@gmail.com      Tablet       3.0  30000.0       Pune    KA  380001.0  1/19/2025    Credit Card  Delivered
35      1036      Anil    Gupta    anil.gupta@email.com      Camera       3.0  30000.0      Delhi    MH  380001.0  1/11/2025            COD    Pending
37      1038      Ravi    Mehta    ravi.mehta@email.com    Keyboard       3.0  30000.0  Ahmedabad    TN  560001.0  1/15/2025     NetBanking   Returned
38      1039      Amit      Das      amit.das@email.com      Camera       2.0  30000.0  Ahmedabad    TN  560001.0  1/18/2025            COD  Delivered
39      1040      Anil    Gupta    anil.gupta@email.com      Mobile       2.0  30000.0      Delhi    GJ  600001.0  1/14/2025            Upi  Cancelled
40      1041     Eswar    Singh    sita.singh@email.com  Headphones       1.0   1500.0        Hyd    TS  560001.0  1/11/2025    Credit card    Pending
41      1042     Sneha      Das     sneha.das@email.com  Headphones       1.0   1500.0    Chennai    KA  400001.0  1/15/2025    Credit card  Cancelled
42      1043      Amit     Nair     amit.nair@email.com      Mobile       2.0   2000.0  Ahmedabad    TS  600001.0  1/15/2025            COD    Pending
43      1044     Kiran    Gupta   kiran.gupta@email.com      Tablet       3.0  55000.0  Ahmedabad    KA  110001.0  1/14/2025    Credit card   Returned
44      1045     Pooja   Sharma  pooja.sharma@email.com    Keyboard       3.0  30000.0  Ahmedabad    TS  500001.0  1/10/2025    Credit card  Cancelled
45      1046      Amit    Kumar    amit.kumar@email.com  Headphones       3.0   2000.0      Delhi    TS  500001.0  1/16/2025     NetBanking    Pending
46      1047     Priya      Das     priya.das@email.com      Mobile       1.0   2000.0     Mumbai    WB  380001.0  1/16/2025     NetBanking  Delivered
47      1048      Anil    Kumar    anil.kumar@email.com  Headphones       3.0  55000.0        Hyd    WB  500001.0  1/20/2025            UPI   Returned
48      1049      Amit      Das      amit.das@email.com     Charger       3.0  30000.0  Ahmedabad    MH  600001.0  1/19/2025    Credit card  Delivered
49      1050      Anil    Mehta    anil.mehta@email.com      Laptop       3.0  30000.0    Kolkata    WB  600001.0  1/18/2025     NetBanking  Cancelled
51      1052     Eswar    Gupta         eswar@gmail.com       Mouse       2.0  55000.0     Mumbai    MH  110001.0  1/14/2025     NetBanking   Returned
52      1053      Ravi    Singh    ravi.singh@email.com     Charger       3.0  55000.0      Delhi    WB  110001.0  1/18/2025    Credit card    Pending
53      1054     Rahul    Patel         eswar@gmail.com      Tablet       3.0   1500.0       Pune    GJ  560001.0  1/20/2025     NetBanking   Returned
55      1056      Amit     Nair         eswar@gmail.com    Keyboard       3.0  55000.0  Bangalore    GJ  500001.0  1/10/2025    Credit card  Cancelled
56      1057      Anil    Verma         eswar@gmail.com  Headphones       3.0  30000.0      Delhi    KA  400001.0  1/16/2025            COD  Cancelled
57      1058     Eswar    Mehta    sita.mehta@email.com  Headphones       2.0   1500.0      Delhi    MH  380001.0  1/19/2025     NetBanking   Returned
58      1059     Kiran      Das     kiran.das@email.com    Keyboard       2.0  30000.0       Pune    TS  110001.0  1/11/2025            COD  Delivered
59      1060     Rahul    Kumar   rahul.kumar@email.com      Laptop       1.0  30000.0  Bangalore    GJ  400001.0  1/11/2025            UPI  Delivered
60      1061      Ravi      Das      ravi.das@email.com      Camera       3.0   2000.0     Mumbai    GJ  500001.0  1/20/2025    Credit card    Pending
61      1062      Ravi    Kumar         eswar@gmail.com      Camera       3.0   1500.0  Hyderabad    MH  400001.0  1/14/2025    Credit Card    Pending
62      1063     Vikas    Singh   vikas.singh@email.com      Mobile       3.0  30000.0    Chennai    DL  110001.0  1/13/2025            COD    Pending
63      1064      Anil    Gupta    anil.gupta@email.com      Laptop       1.0  30000.0      Delhi    TS  110001.0  1/12/2025            COD  Cancelled
64      1065     Pooja    Singh   pooja.singh@email.com       Mouse       1.0   1500.0  Bangalore    WB  500001.0  1/18/2025            COD    Pending
65      1066     Pooja    Verma   pooja.verma@email.com      Mobile       2.0  30000.0       Pune    MH  500001.0  1/12/2025    Credit Card  Delivered
66      1067     Priya    Singh         eswar@gmail.com      Camera       3.0  30000.0       Pune    GJ  560001.0  1/12/2025     NetBanking  Delivered
68      1069     Vikas   Sharma  vikas.sharma@email.com       Mouse       3.0  55000.0  Hyderabad    MH  560001.0  1/16/2025     NetBanking   Returned
69      1070      Ravi    Reddy    ravi.reddy@email.com      Laptop       1.0  55000.0  Ahmedabad    KA  560001.0  1/17/2025     NetBanking   Returned
70      1071     Kiran    Kumar   kiran.kumar@email.com       Mouse       3.0  30000.0  Ahmedabad    DL  500001.0  1/10/2025            UPI  Cancelled
71      1072      Ravi    Mehta    ravi.mehta@email.com      Camera       3.0  30000.0      Delhi    TN  560001.0  1/15/2025     NetBanking  Delivered
72      1073      Ravi     Nair     ravi.nair@email.com     Charger       2.0  55000.0       Pune    MH  560001.0  1/18/2025            COD    Pending
73      1074     Eswar      Das      sita.das@email.com      Mobile       2.0  30000.0  Bangalore    MH  560001.0  1/10/2025     NetBanking  Delivered
74      1075     Vikas    Kumar   vikas.kumar@email.com    Keyboard       2.0  30000.0  Bangalore    KA  560001.0  1/15/2025            COD    Pending
75      1076      Amit    Patel    amit.patel@email.com      Laptop       3.0  30000.0  Bangalore    TS  500001.0  1/10/2025    Credit Card   Returned
76      1077     Priya    Patel   priya.patel@email.com  Headphones       2.0  30000.0       Pune    TN  560001.0  1/14/2025     NetBanking  Delivered
77      1078     Priya    Singh   priya.singh@email.com    Keyboard       2.0  30000.0       Pune    MH  560001.0  1/16/2025    Credit Card   Returned
79      1080      Amit    Mehta    amit.mehta@email.com      Camera       2.0   1500.0    Chennai    TN  400001.0  1/17/2025            COD  Cancelled
80      1081      Anil    Mehta    anil.mehta@email.com      Camera       2.0  55000.0  Ahmedabad    TN  400001.0  1/17/2025     NetBanking  Delivered
83      1084     Pooja    Singh   pooja.singh@email.com  Headphones       3.0  30000.0       Bang    TN  400001.0  1/19/2025    Credit Card    Pending
84      1085      Anil    Patel    anil.patel@email.com      Mobile       3.0  30000.0       Bang    DL  600001.0  1/11/2025    Credit Card   Returned
85      1086     Pooja    Patel   pooja.patel@email.com    Keyboard       1.0  55000.0    Chennai    MH  110001.0  1/15/2025            COD    Pending
86      1087     Kiran    Verma   kiran.verma@email.com      Mobile       1.0   1500.0       Bang    WB  560001.0  1/20/2025            UPI   Returned
87      1088     Eswar    Kumar    sita.kumar@email.com      Mobile       1.0  55000.0  Hyderabad    MH  380001.0  1/11/2025    Credit Card   Returned
88      1089     Sneha    Singh         eswar@gmail.com    Keyboard       1.0  30000.0      Delhi    MH  600001.0  1/16/2025            COD   Returned
89      1090      Amit    Mehta    amit.mehta@email.com     Charger       2.0   1500.0  Ahmedabad    TS  380001.0  1/15/2025    Credit Card  Cancelled
90      1091     Pooja    Kumar   pooja.kumar@email.com       Mouse       2.0   1500.0    Kolkata    TN  560001.0  1/15/2025            COD  Delivered
91      1092      Anil    Mehta    anil.mehta@email.com  Headphones       2.0   1500.0       Bang    KA  380001.0  1/20/2025            UPI  Cancelled
92      1093     Kiran   Sharma  kiran.sharma@email.com     Charger       2.0   1500.0       Bang    DL  110001.0  1/17/2025            COD    Pending
93      1094     Kiran    Kumar   kiran.kumar@email.com      Tablet       1.0  30000.0       Pune    TN  110001.0  1/19/2025            COD  Delivered
95      1096     Kiran    Reddy   kiran.reddy@email.com    Keyboard       1.0  30000.0  Hyderabad    WB  500001.0  1/14/2025            COD    Pending
96      1097     Kiran    Kumar         eswar@gmail.com      Tablet       1.0  55000.0    Kolkata    TS  560001.0  1/20/2025            COD    Pending
98      1099      Amit    Verma    amit.verma@email.com      Camera       1.0  30000.0       Bang    WB  380001.0  1/20/2025            UPI  Delivered
99      1100     Sneha   Sharma  sneha.sharma@email.com      Laptop       3.0  55000.0  Bangalore    GJ  600001.0  1/11/2025     NetBanking   Returned
101     1102     Pooja    Reddy   pooja.reddy@email.com       Mouse       1.0   1500.0  Bangalore    TN  560001.0  1/13/2025            COD  Cancelled
102     1103     Sneha    Mehta   sneha.mehta@email.com    Keyboard       3.0   1500.0  Bangalore    WB  500001.0  1/12/2025            UPI  Delivered
103     1104     Eswar    Verma    sita.verma@email.com      Laptop       3.0  55000.0  Hyderabad    KA  500001.0  1/13/2025    Credit Card    Pending
104     1105      Anil   Sharma   anil.sharma@email.com      Laptop       1.0   1500.0  Bangalore    MH  400001.0  1/11/2025            COD    Pending
105     1106     Vikas    Kumar   vikas.kumar@email.com      Laptop       3.0   2000.0    Kolkata    TN  500001.0  1/12/2025     NetBanking  Delivered
107     1108     Vikas      Das     vikas.das@email.com      Camera       3.0  55000.0    Chennai    KA  380001.0  1/19/2025     NetBanking    Pending
108     1109      Amit   Sharma   amit.sharma@email.com      Laptop       3.0   2000.0  Bangalore    TN  400001.0  1/14/2025     NetBanking   Returned
111     1112     Rahul    Mehta   rahul.mehta@email.com    Keyboard       3.0   2000.0  Hyderabad    KA  380001.0  1/14/2025            COD  Cancelled
112     1113     Kiran      Das     kiran.das@email.com      Tablet       1.0   1500.0  Hyderabad    GJ  500001.0  1/15/2025            COD    Pending
113     1114      Anil    Patel    anil.patel@email.com      Laptop       2.0   2000.0  Ahmedabad    TN  110001.0  1/10/2025     NetBanking  Delivered
114     1115     Pooja    Patel   pooja.patel@email.com  Headphones       1.0   2000.0    Kolkata    TN  500001.0  1/10/2025            UPI   Returned
115     1116     Pooja      Das     pooja.das@email.com       Mouse       1.0   2000.0       Pune    GJ  380001.0  1/10/2025    Credit Card    Pending
116     1117     Pooja    Singh   pooja.singh@email.com      Tablet       3.0   2000.0  Hyderabad    WB  560001.0  1/10/2025            UPI    Pending
118     1119      Amit    Reddy    amit.reddy@email.com       Mouse       2.0   2000.0  Ahmedabad    KA  400001.0  1/20/2025    Credit Card    Pending
119     1120      Ravi      Das      ravi.das@email.com      Mobile       3.0   1500.0  Ahmedabad    GJ  500001.0  1/20/2025            UPI    Pending
121     1122      Ravi    Gupta    ravi.gupta@email.com  Headphones       1.0   1500.0     Mumbai    TN  110001.0  1/18/2025     NetBanking    Pending
122     1123     Vikas    Patel   vikas.patel@email.com    Keyboard       3.0   1500.0  Hyderabad    TN  560001.0  1/17/2025     NetBanking   Returned
123     1124     Sneha    Kumar   sneha.kumar@email.com      Laptop       2.0  30000.0    Kolkata    MH  560001.0  1/17/2025            UPI  Delivered
124     1125     Eswar   Sharma   sita.sharma@email.com      Camera       2.0  55000.0     Mumbai    TN  110001.0  1/15/2025            COD  Delivered
125     1126     Rahul    Reddy   rahul.reddy@email.com  Headphones       3.0   1500.0      Delhi    TN  600001.0  1/20/2025    Credit Card  Delivered
126     1127      Anil      Das      anil.das@email.com    Keyboard       3.0   2000.0  Hyderabad    DL  400001.0  1/18/2025            UPI  Cancelled
127     1128     Pooja    Reddy   pooja.reddy@email.com      Laptop       2.0   2000.0      Delhi    TN  560001.0  1/13/2025            COD    Pending
128     1129     Kiran    Mehta   kiran.mehta@email.com     Charger       1.0   1500.0    Chennai    TN  560001.0  1/20/2025     NetBanking   Returned
129     1130     Rahul    Verma   rahul.verma@email.com  Headphones       3.0  30000.0  Ahmedabad    WB  560001.0  1/14/2025            UPI  Cancelled
130     1131     Vikas    Singh   vikas.singh@email.com      Camera       3.0  30000.0  Ahmedabad    TN  500001.0  1/16/2025            COD    Pending
131     1132      Anil   Sharma   anil.sharma@email.com  Headphones       3.0  55000.0    Kolkata    MH  500001.0  1/20/2025            UPI  Cancelled
132     1133     Pooja     Nair    pooja.nair@email.com       Mouse       1.0  55000.0    Kolkata    TS  500001.0  1/17/2025            COD  Cancelled
133     1134      Ravi    Kumar    ravi.kumar@email.com      Mobile       1.0   1500.0  Ahmedabad    TN  110001.0  1/20/2025            COD   Returned
134     1135      Amit    Reddy    amit.reddy@email.com      Laptop       1.0   1500.0  Hyderabad    KA  110001.0  1/12/2025    Credit Card   Returned
135     1136     Eswar    Singh    sita.singh@email.com      Mobile       3.0   2000.0  Bangalore    GJ  400001.0  1/16/2025            UPI    Pending
136     1137      Anil     Nair     anil.nair@email.com      Tablet       3.0   2000.0  Bangalore    DL  600001.0  1/14/2025     NetBanking   Returned
137     1138      Anil    Verma    anil.verma@email.com      Tablet       3.0  55000.0  Hyderabad    GJ  380001.0  1/15/2025     NetBanking  Cancelled
140     1141     Sneha    Verma   sneha.verma@email.com       Mouse       1.0  30000.0      Delhi    MH  380001.0  1/16/2025            COD  Cancelled
142     1143     Priya    Reddy   priya.reddy@email.com      Laptop       3.0   2000.0  Bangalore    TS  400001.0  1/16/2025            COD  Cancelled
143     1144      Ravi    Verma         eswar@gmail.com       Mouse       3.0   1500.0  Ahmedabad    TN  400001.0  1/12/2025    Credit Card  Delivered
144     1145     Kiran      Das     kiran.das@email.com      Camera       3.0   1500.0  Ahmedabad    TN  600001.0  1/15/2025            UPI    Pending
146     1147      Amit    Mehta    amit.mehta@email.com    Keyboard       3.0   1500.0  Ahmedabad    GJ  400001.0  1/12/2025            COD  Delivered
147     1148     Pooja    Singh   pooja.singh@email.com     Charger       3.0   2000.0  Hyderabad    TS  400001.0  1/20/2025     NetBanking  Delivered
148     1149      Anil    Verma    anil.verma@email.com      Laptop       3.0   2000.0    Kolkata    KA  110001.0  1/19/2025            COD    Pending
149     1150     Eswar   Sharma         eswar@gmail.com      Camera       3.0   2000.0  Hyderabad    WB  110001.0  1/20/2025            UPI    Pending
150     1151      Ravi    Singh    ravi.singh@email.com    Keyboard       3.0   1500.0       Pune    TN  110001.0  1/13/2025    Credit Card   Returned
151     1152     Eswar    Patel    sita.patel@email.com  Headphones       2.0  30000.0     Mumbai    MH  500001.0  1/14/2025    Credit Card  Cancelled
152     1153     Sneha    Kumar         eswar@gmail.com     Charger       2.0   1500.0  Hyderabad    MH  600001.0  1/20/2025            COD  Cancelled
153     1154     Sneha    Gupta   sneha.gupta@email.com  Headphones       3.0   1500.0       Pune    MH  110001.0  1/20/2025    Credit Card   Returned
155     1156     Vikas     Nair    vikas.nair@email.com     Charger       3.0   2000.0    Chennai    DL  600001.0  1/16/2025     NetBanking  Delivered
156     1157     Pooja    Mehta   pooja.mehta@email.com      Camera       3.0   1500.0    Chennai    DL  560001.0  1/10/2025    Credit Card  Cancelled

In [ ]:
print(data1.loc[3])

order_id                           1004
firstname                         Kiran
lastname                          Singh
email             kiran.singh@email.com
product                          Camera
quantity                            2.0
price                            2000.0
city                            Kolkata
state                                MH
pincode                        380001.0
order_date                    1/18/2025
payment_method                      COD
status                          Pending
Name: 3, dtype: object

In [ ]:
data1=data1.set_index(['order_id'])

In [ ]:
print(data1.to_string())

         firstname lastname                   email     product  quantity    price       city state   pincode order_date payment_method     status
order_id
1001         Eswar    Reddy             e@gmail.com      Camera       2.0   1500.0    Chennai    WB  500001.0  1/15/2025    Credit Card  Cancelled
1003         Kiran    Mehta   kiran.mehta@email.com    Keyboard       1.0  55000.0      Delhi    TS  500001.0  1/19/2025            COD  Cancelled
1004         Kiran    Singh   kiran.singh@email.com      Camera       2.0   2000.0    Kolkata    MH  380001.0  1/18/2025            COD    Pending
1005         Rahul     Nair    rahul.nair@email.com    Keyboard       2.0  30000.0  Ahmedabad    GJ  380001.0  1/18/2025     NetBanking  Cancelled
1006         Pooja    Verma   pooja.verma@email.com      Mobile       1.0  30000.0     Mumbai    TN  110001.0  1/16/2025     NetBanking    Pending
1008         Sneha    Verma   sneha.verma@email.com      Laptop       1.0  30000.0  Hyderabad    MH  380001.0  1/20/2025            Upi    Pending
1010         Eswar     Nair     sita.nair@email.com  Headphones       1.0   2000.0     Mumbai    TN  560001.0  1/14/2025     NetBanking  Delivered
1012         Priya    Kumar   priya.kumar@email.com  Headphones       2.0  30000.0     Mumbai    MH  500001.0  1/16/2025     NetBanking   Returned
1013         Eswar    Singh    sita.singh@email.com       Mouse       1.0  30000.0      Delhi    GJ  600001.0  1/14/2025            COD  Delivered
1014         Priya    Reddy   priya.reddy@email.com      Camera       1.0  30000.0       Pune    TN  110001.0  1/18/2025            COD   Returned
1016          Amit   Sharma   amit.sharma@email.com    Keyboard       2.0  55000.0  Bangalore    MH  400001.0  1/17/2025    Credit Card  Delivered
1017         Kiran   Sharma  kiran.sharma@email.com    Keyboard       3.0   1500.0    Chennai    WB  560001.0  1/10/2025            Upi    Pending
1018         Rahul    Verma   rahul.verma@email.com     Charger       3.0  55000.0  Bangalore    MH  110001.0  1/20/2025            Upi   Returned
1019         Pooja   Sharma  pooja.sharma@email.com  Headphones       1.0   2000.0      Delhi    WB  380001.0  1/17/2025     NetBanking  Delivered
1020          Anil    Singh    anil.singh@email.com      Laptop       3.0   1500.0      Delhi    KA  560001.0  1/11/2025     NetBanking   Returned
1021         Rahul    Kumar   rahul.kumar@email.com      Mobile       3.0   2000.0        Hyd    GJ  380001.0  1/17/2025    Credit Card  Delivered
1022          Amit    Verma    amit.verma@email.com    Keyboard       2.0  30000.0     Mumbai    GJ  110001.0  1/13/2025            Upi    Pending
1023         Sneha    Verma         eswar@gmail.com      Tablet       2.0  30000.0       Pune    KA  400001.0  1/15/2025            Upi    Pending
1024         Pooja   Sharma  pooja.sharma@email.com      Camera       1.0  30000.0    Chennai    KA  560001.0  1/18/2025            Upi  Delivered
1025         Kiran    Mehta   kiran.mehta@email.com      Tablet       3.0  30000.0     Mumbai    GJ  500001.0  1/15/2025            COD  Delivered
1026          Anil    Reddy    anil.reddy@email.com  Headphones       2.0   2000.0    Kolkata    GJ  400001.0  1/15/2025     NetBanking  Delivered
1027         Eswar   Sharma   sita.sharma@email.com      Laptop       2.0  55000.0       Pune    DL  400001.0  1/15/2025            COD  Cancelled
1028         Eswar    Mehta    sita.mehta@email.com     Charger       1.0   1500.0  Bangalore    WB  380001.0  1/14/2025            Upi  Delivered
1029         Sneha    Reddy   sneha.reddy@email.com      Laptop       1.0   1500.0       Pune    TS  380001.0  1/18/2025     NetBanking  Delivered
1030          Amit    Patel         eswar@gmail.com     Charger       1.0  55000.0  Ahmedabad    TS  560001.0  1/10/2025    Credit Card  Cancelled
1031         Vikas    Kumar   vikas.kumar@email.com      Tablet       3.0  55000.0     Mumbai    DL  500001.0  1/16/2025            COD    Pending
1033         Priya    Patel   priya.patel@email.com    Keyboard       2.0   1500.0      Delhi    TS  380001.0  1/19/2025            COD  Delivered
1034         Rahul    Kumar   rahul.kumar@email.com     Charger       2.0   2000.0      Delhi    GJ  560001.0  1/13/2025            Upi  Delivered
1035         Priya    Gupta         eswar@gmail.com      Tablet       3.0  30000.0       Pune    KA  380001.0  1/19/2025    Credit Card  Delivered
1036          Anil    Gupta    anil.gupta@email.com      Camera       3.0  30000.0      Delhi    MH  380001.0  1/11/2025            COD    Pending
1038          Ravi    Mehta    ravi.mehta@email.com    Keyboard       3.0  30000.0  Ahmedabad    TN  560001.0  1/15/2025     NetBanking   Returned
1039          Amit      Das      amit.das@email.com      Camera       2.0  30000.0  Ahmedabad    TN  560001.0  1/18/2025            COD  Delivered
1040          Anil    Gupta    anil.gupta@email.com      Mobile       2.0  30000.0      Delhi    GJ  600001.0  1/14/2025            Upi  Cancelled
1041         Eswar    Singh    sita.singh@email.com  Headphones       1.0   1500.0        Hyd    TS  560001.0  1/11/2025    Credit card    Pending
1042         Sneha      Das     sneha.das@email.com  Headphones       1.0   1500.0    Chennai    KA  400001.0  1/15/2025    Credit card  Cancelled
1043          Amit     Nair     amit.nair@email.com      Mobile       2.0   2000.0  Ahmedabad    TS  600001.0  1/15/2025            COD    Pending
1044         Kiran    Gupta   kiran.gupta@email.com      Tablet       3.0  55000.0  Ahmedabad    KA  110001.0  1/14/2025    Credit card   Returned
1045         Pooja   Sharma  pooja.sharma@email.com    Keyboard       3.0  30000.0  Ahmedabad    TS  500001.0  1/10/2025    Credit card  Cancelled
1046          Amit    Kumar    amit.kumar@email.com  Headphones       3.0   2000.0      Delhi    TS  500001.0  1/16/2025     NetBanking    Pending
1047         Priya      Das     priya.das@email.com      Mobile       1.0   2000.0     Mumbai    WB  380001.0  1/16/2025     NetBanking  Delivered
1048          Anil    Kumar    anil.kumar@email.com  Headphones       3.0  55000.0        Hyd    WB  500001.0  1/20/2025            UPI   Returned
1049          Amit      Das      amit.das@email.com     Charger       3.0  30000.0  Ahmedabad    MH  600001.0  1/19/2025    Credit card  Delivered
1050          Anil    Mehta    anil.mehta@email.com      Laptop       3.0  30000.0    Kolkata    WB  600001.0  1/18/2025     NetBanking  Cancelled
1052         Eswar    Gupta         eswar@gmail.com       Mouse       2.0  55000.0     Mumbai    MH  110001.0  1/14/2025     NetBanking   Returned
1053          Ravi    Singh    ravi.singh@email.com     Charger       3.0  55000.0      Delhi    WB  110001.0  1/18/2025    Credit card    Pending
1054         Rahul    Patel         eswar@gmail.com      Tablet       3.0   1500.0       Pune    GJ  560001.0  1/20/2025     NetBanking   Returned
1056          Amit     Nair         eswar@gmail.com    Keyboard       3.0  55000.0  Bangalore    GJ  500001.0  1/10/2025    Credit card  Cancelled
1057          Anil    Verma         eswar@gmail.com  Headphones       3.0  30000.0      Delhi    KA  400001.0  1/16/2025            COD  Cancelled
1058         Eswar    Mehta    sita.mehta@email.com  Headphones       2.0   1500.0      Delhi    MH  380001.0  1/19/2025     NetBanking   Returned
1059         Kiran      Das     kiran.das@email.com    Keyboard       2.0  30000.0       Pune    TS  110001.0  1/11/2025            COD  Delivered
1060         Rahul    Kumar   rahul.kumar@email.com      Laptop       1.0  30000.0  Bangalore    GJ  400001.0  1/11/2025            UPI  Delivered
1061          Ravi      Das      ravi.das@email.com      Camera       3.0   2000.0     Mumbai    GJ  500001.0  1/20/2025    Credit card    Pending
1062          Ravi    Kumar         eswar@gmail.com      Camera       3.0   1500.0  Hyderabad    MH  400001.0  1/14/2025    Credit Card    Pending
1063         Vikas    Singh   vikas.singh@email.com      Mobile       3.0  30000.0    Chennai    DL  110001.0  1/13/2025            COD    Pending
1064          Anil    Gupta    anil.gupta@email.com      Laptop       1.0  30000.0      Delhi    TS  110001.0  1/12/2025            COD  Cancelled
1065         Pooja    Singh   pooja.singh@email.com       Mouse       1.0   1500.0  Bangalore    WB  500001.0  1/18/2025            COD    Pending
1066         Pooja    Verma   pooja.verma@email.com      Mobile       2.0  30000.0       Pune    MH  500001.0  1/12/2025    Credit Card  Delivered
1067         Priya    Singh         eswar@gmail.com      Camera       3.0  30000.0       Pune    GJ  560001.0  1/12/2025     NetBanking  Delivered
1069         Vikas   Sharma  vikas.sharma@email.com       Mouse       3.0  55000.0  Hyderabad    MH  560001.0  1/16/2025     NetBanking   Returned
1070          Ravi    Reddy    ravi.reddy@email.com      Laptop       1.0  55000.0  Ahmedabad    KA  560001.0  1/17/2025     NetBanking   Returned
1071         Kiran    Kumar   kiran.kumar@email.com       Mouse       3.0  30000.0  Ahmedabad    DL  500001.0  1/10/2025            UPI  Cancelled
1072          Ravi    Mehta    ravi.mehta@email.com      Camera       3.0  30000.0      Delhi    TN  560001.0  1/15/2025     NetBanking  Delivered
1073          Ravi     Nair     ravi.nair@email.com     Charger       2.0  55000.0       Pune    MH  560001.0  1/18/2025            COD    Pending
1074         Eswar      Das      sita.das@email.com      Mobile       2.0  30000.0  Bangalore    MH  560001.0  1/10/2025     NetBanking  Delivered
1075         Vikas    Kumar   vikas.kumar@email.com    Keyboard       2.0  30000.0  Bangalore    KA  560001.0  1/15/2025            COD    Pending
1076          Amit    Patel    amit.patel@email.com      Laptop       3.0  30000.0  Bangalore    TS  500001.0  1/10/2025    Credit Card   Returned
1077         Priya    Patel   priya.patel@email.com  Headphones       2.0  30000.0       Pune    TN  560001.0  1/14/2025     NetBanking  Delivered
1078         Priya    Singh   priya.singh@email.com    Keyboard       2.0  30000.0       Pune    MH  560001.0  1/16/2025    Credit Card   Returned
1080          Amit    Mehta    amit.mehta@email.com      Camera       2.0   1500.0    Chennai    TN  400001.0  1/17/2025            COD  Cancelled
1081          Anil    Mehta    anil.mehta@email.com      Camera       2.0  55000.0  Ahmedabad    TN  400001.0  1/17/2025     NetBanking  Delivered
1084         Pooja    Singh   pooja.singh@email.com  Headphones       3.0  30000.0       Bang    TN  400001.0  1/19/2025    Credit Card    Pending
1085          Anil    Patel    anil.patel@email.com      Mobile       3.0  30000.0       Bang    DL  600001.0  1/11/2025    Credit Card   Returned
1086         Pooja    Patel   pooja.patel@email.com    Keyboard       1.0  55000.0    Chennai    MH  110001.0  1/15/2025            COD    Pending
1087         Kiran    Verma   kiran.verma@email.com      Mobile       1.0   1500.0       Bang    WB  560001.0  1/20/2025            UPI   Returned
1088         Eswar    Kumar    sita.kumar@email.com      Mobile       1.0  55000.0  Hyderabad    MH  380001.0  1/11/2025    Credit Card   Returned
1089         Sneha    Singh         eswar@gmail.com    Keyboard       1.0  30000.0      Delhi    MH  600001.0  1/16/2025            COD   Returned
1090          Amit    Mehta    amit.mehta@email.com     Charger       2.0   1500.0  Ahmedabad    TS  380001.0  1/15/2025    Credit Card  Cancelled
1091         Pooja    Kumar   pooja.kumar@email.com       Mouse       2.0   1500.0    Kolkata    TN  560001.0  1/15/2025            COD  Delivered
1092          Anil    Mehta    anil.mehta@email.com  Headphones       2.0   1500.0       Bang    KA  380001.0  1/20/2025            UPI  Cancelled
1093         Kiran   Sharma  kiran.sharma@email.com     Charger       2.0   1500.0       Bang    DL  110001.0  1/17/2025            COD    Pending
1094         Kiran    Kumar   kiran.kumar@email.com      Tablet       1.0  30000.0       Pune    TN  110001.0  1/19/2025            COD  Delivered
1096         Kiran    Reddy   kiran.reddy@email.com    Keyboard       1.0  30000.0  Hyderabad    WB  500001.0  1/14/2025            COD    Pending
1097         Kiran    Kumar         eswar@gmail.com      Tablet       1.0  55000.0    Kolkata    TS  560001.0  1/20/2025            COD    Pending
1099          Amit    Verma    amit.verma@email.com      Camera       1.0  30000.0       Bang    WB  380001.0  1/20/2025            UPI  Delivered
1100         Sneha   Sharma  sneha.sharma@email.com      Laptop       3.0  55000.0  Bangalore    GJ  600001.0  1/11/2025     NetBanking   Returned
1102         Pooja    Reddy   pooja.reddy@email.com       Mouse       1.0   1500.0  Bangalore    TN  560001.0  1/13/2025            COD  Cancelled
1103         Sneha    Mehta   sneha.mehta@email.com    Keyboard       3.0   1500.0  Bangalore    WB  500001.0  1/12/2025            UPI  Delivered
1104         Eswar    Verma    sita.verma@email.com      Laptop       3.0  55000.0  Hyderabad    KA  500001.0  1/13/2025    Credit Card    Pending
1105          Anil   Sharma   anil.sharma@email.com      Laptop       1.0   1500.0  Bangalore    MH  400001.0  1/11/2025            COD    Pending
1106         Vikas    Kumar   vikas.kumar@email.com      Laptop       3.0   2000.0    Kolkata    TN  500001.0  1/12/2025     NetBanking  Delivered
1108         Vikas      Das     vikas.das@email.com      Camera       3.0  55000.0    Chennai    KA  380001.0  1/19/2025     NetBanking    Pending
1109          Amit   Sharma   amit.sharma@email.com      Laptop       3.0   2000.0  Bangalore    TN  400001.0  1/14/2025     NetBanking   Returned
1112         Rahul    Mehta   rahul.mehta@email.com    Keyboard       3.0   2000.0  Hyderabad    KA  380001.0  1/14/2025            COD  Cancelled
1113         Kiran      Das     kiran.das@email.com      Tablet       1.0   1500.0  Hyderabad    GJ  500001.0  1/15/2025            COD    Pending
1114          Anil    Patel    anil.patel@email.com      Laptop       2.0   2000.0  Ahmedabad    TN  110001.0  1/10/2025     NetBanking  Delivered
1115         Pooja    Patel   pooja.patel@email.com  Headphones       1.0   2000.0    Kolkata    TN  500001.0  1/10/2025            UPI   Returned
1116         Pooja      Das     pooja.das@email.com       Mouse       1.0   2000.0       Pune    GJ  380001.0  1/10/2025    Credit Card    Pending
1117         Pooja    Singh   pooja.singh@email.com      Tablet       3.0   2000.0  Hyderabad    WB  560001.0  1/10/2025            UPI    Pending
1119          Amit    Reddy    amit.reddy@email.com       Mouse       2.0   2000.0  Ahmedabad    KA  400001.0  1/20/2025    Credit Card    Pending
1120          Ravi      Das      ravi.das@email.com      Mobile       3.0   1500.0  Ahmedabad    GJ  500001.0  1/20/2025            UPI    Pending
1122          Ravi    Gupta    ravi.gupta@email.com  Headphones       1.0   1500.0     Mumbai    TN  110001.0  1/18/2025     NetBanking    Pending
1123         Vikas    Patel   vikas.patel@email.com    Keyboard       3.0   1500.0  Hyderabad    TN  560001.0  1/17/2025     NetBanking   Returned
1124         Sneha    Kumar   sneha.kumar@email.com      Laptop       2.0  30000.0    Kolkata    MH  560001.0  1/17/2025            UPI  Delivered
1125         Eswar   Sharma   sita.sharma@email.com      Camera       2.0  55000.0     Mumbai    TN  110001.0  1/15/2025            COD  Delivered
1126         Rahul    Reddy   rahul.reddy@email.com  Headphones       3.0   1500.0      Delhi    TN  600001.0  1/20/2025    Credit Card  Delivered
1127          Anil      Das      anil.das@email.com    Keyboard       3.0   2000.0  Hyderabad    DL  400001.0  1/18/2025            UPI  Cancelled
1128         Pooja    Reddy   pooja.reddy@email.com      Laptop       2.0   2000.0      Delhi    TN  560001.0  1/13/2025            COD    Pending
1129         Kiran    Mehta   kiran.mehta@email.com     Charger       1.0   1500.0    Chennai    TN  560001.0  1/20/2025     NetBanking   Returned
1130         Rahul    Verma   rahul.verma@email.com  Headphones       3.0  30000.0  Ahmedabad    WB  560001.0  1/14/2025            UPI  Cancelled
1131         Vikas    Singh   vikas.singh@email.com      Camera       3.0  30000.0  Ahmedabad    TN  500001.0  1/16/2025            COD    Pending
1132          Anil   Sharma   anil.sharma@email.com  Headphones       3.0  55000.0    Kolkata    MH  500001.0  1/20/2025            UPI  Cancelled
1133         Pooja     Nair    pooja.nair@email.com       Mouse       1.0  55000.0    Kolkata    TS  500001.0  1/17/2025            COD  Cancelled
1134          Ravi    Kumar    ravi.kumar@email.com      Mobile       1.0   1500.0  Ahmedabad    TN  110001.0  1/20/2025            COD   Returned
1135          Amit    Reddy    amit.reddy@email.com      Laptop       1.0   1500.0  Hyderabad    KA  110001.0  1/12/2025    Credit Card   Returned
1136         Eswar    Singh    sita.singh@email.com      Mobile       3.0   2000.0  Bangalore    GJ  400001.0  1/16/2025            UPI    Pending
1137          Anil     Nair     anil.nair@email.com      Tablet       3.0   2000.0  Bangalore    DL  600001.0  1/14/2025     NetBanking   Returned
1138          Anil    Verma    anil.verma@email.com      Tablet       3.0  55000.0  Hyderabad    GJ  380001.0  1/15/2025     NetBanking  Cancelled
1141         Sneha    Verma   sneha.verma@email.com       Mouse       1.0  30000.0      Delhi    MH  380001.0  1/16/2025            COD  Cancelled
1143         Priya    Reddy   priya.reddy@email.com      Laptop       3.0   2000.0  Bangalore    TS  400001.0  1/16/2025            COD  Cancelled
1144          Ravi    Verma         eswar@gmail.com       Mouse       3.0   1500.0  Ahmedabad    TN  400001.0  1/12/2025    Credit Card  Delivered
1145         Kiran      Das     kiran.das@email.com      Camera       3.0   1500.0  Ahmedabad    TN  600001.0  1/15/2025            UPI    Pending
1147          Amit    Mehta    amit.mehta@email.com    Keyboard       3.0   1500.0  Ahmedabad    GJ  400001.0  1/12/2025            COD  Delivered
1148         Pooja    Singh   pooja.singh@email.com     Charger       3.0   2000.0  Hyderabad    TS  400001.0  1/20/2025     NetBanking  Delivered
1149          Anil    Verma    anil.verma@email.com      Laptop       3.0   2000.0    Kolkata    KA  110001.0  1/19/2025            COD    Pending
1150         Eswar   Sharma         eswar@gmail.com      Camera       3.0   2000.0  Hyderabad    WB  110001.0  1/20/2025            UPI    Pending
1151          Ravi    Singh    ravi.singh@email.com    Keyboard       3.0   1500.0       Pune    TN  110001.0  1/13/2025    Credit Card   Returned
1152         Eswar    Patel    sita.patel@email.com  Headphones       2.0  30000.0     Mumbai    MH  500001.0  1/14/2025    Credit Card  Cancelled
1153         Sneha    Kumar         eswar@gmail.com     Charger       2.0   1500.0  Hyderabad    MH  600001.0  1/20/2025            COD  Cancelled
1154         Sneha    Gupta   sneha.gupta@email.com  Headphones       3.0   1500.0       Pune    MH  110001.0  1/20/2025    Credit Card   Returned
1156         Vikas     Nair    vikas.nair@email.com     Charger       3.0   2000.0    Chennai    DL  600001.0  1/16/2025     NetBanking  Delivered
1157         Pooja    Mehta   pooja.mehta@email.com      Camera       3.0   1500.0    Chennai    DL  560001.0  1/10/2025    Credit Card  Cancelled
1158         Priya    Mehta   priya.mehta@email.com     Charger       1.0   1500.0      Delhi    TN  600001.0  1/20/2025     NetBanking  Cancelled
1159         Sneha    Mehta   sneha.mehta@email.com       Mouse       1.0  55000.0  Bangalore    GJ  500001.0  1/18/2025    Credit Card    Pending
1160         Pooja    Kumar   pooja.kumar@email.com      Laptop       1.0  55000.0       Pune    WB  110001.0  1/16/2025     NetBanking   Returned

In [ ]:
print(data1.loc['1001'])

firstname               Eswar
lastname                Reddy
email             e@gmail.com
product                Camera
quantity                  2.0
price                  1500.0
city                  Chennai
state                      WB
pincode              500001.0
order_date          1/15/2025
payment_method    Credit Card
status              Cancelled
Name: 1001, dtype: object

In [ ]:
data1.dtypes

firstname          object
lastname           object
email              object
product            object
quantity          float64
price             float64
city               object
state              object
pincode           float64
order_date         object
payment_method     object
status             object
dtype: object

In [ ]:
print(data1)

         firstname lastname                  email     product  quantity  \
order_id
1001         Eswar    Reddy            e@gmail.com      Camera       2.0
1003         Kiran    Mehta  kiran.mehta@email.com    Keyboard       1.0
1004         Kiran    Singh  kiran.singh@email.com      Camera       2.0
1005         Rahul     Nair   rahul.nair@email.com    Keyboard       2.0
1006         Pooja    Verma  pooja.verma@email.com      Mobile       1.0
...            ...      ...                    ...         ...       ...
1198         Vikas    Kumar        eswar@gmail.com      Camera       1.0
1199          Amit    Reddy   amit.reddy@email.com      Camera       2.0
1200         Pooja    Gupta  pooja.gupta@email.com      Tablet       2.0
1042         Sneha      Das    sneha.das@email.com  Headphones       1.0
1028         Eswar    Mehta   sita.mehta@email.com     Charger       1.0

            price       city state   pincode order_date payment_method  \
order_id
1001       1500.0    Chennai    WB  500001.0  1/15/2025    Credit Card
1003      55000.0      Delhi    TS  500001.0  1/19/2025            COD
1004       2000.0    Kolkata    MH  380001.0  1/18/2025            COD
1005      30000.0  Ahmedabad    GJ  380001.0  1/18/2025     NetBanking
1006      30000.0     Mumbai    TN  110001.0  1/16/2025     NetBanking
...           ...        ...   ...       ...        ...            ...
1198      55000.0  Hyderabad    KA  560001.0  1/16/2025     NetBanking
1199      30000.0  Hyderabad    KA  600001.0  1/11/2025            COD
1200      30000.0  Ahmedabad    KA  600001.0  1/15/2025            UPI
1042       1500.0    Chennai    KA  400001.0  1/15/2025    Credit Card
1028       1500.0  Bangalore    WB  380001.0  1/14/2025            UPI

             status
order_id
1001      Cancelled
1003      Cancelled
1004        Pending
1005      Cancelled
1006        Pending
...             ...
1198      Delivered
1199        Pending
1200      Delivered
1042      Cancelled
1028      Delivered

[169 rows x 12 columns]

In [ ]:
data1=data1.reset_index()

In [ ]:
print(data1)

    order_id firstname lastname                  email     product  quantity  \
0       1001     Eswar    Reddy            e@gmail.com      Camera       2.0
1       1003     Kiran    Mehta  kiran.mehta@email.com    Keyboard       1.0
2       1004     Kiran    Singh  kiran.singh@email.com      Camera       2.0
3       1005     Rahul     Nair   rahul.nair@email.com    Keyboard       2.0
4       1006     Pooja    Verma  pooja.verma@email.com      Mobile       1.0
..       ...       ...      ...                    ...         ...       ...
164     1198     Vikas    Kumar        eswar@gmail.com      Camera       1.0
165     1199      Amit    Reddy   amit.reddy@email.com      Camera       2.0
166     1200     Pooja    Gupta  pooja.gupta@email.com      Tablet       2.0
167     1042     Sneha      Das    sneha.das@email.com  Headphones       1.0
168     1028     Eswar    Mehta   sita.mehta@email.com     Charger       1.0

       price       city state   pincode order_date payment_method     status
0     1500.0    Chennai    WB  500001.0  1/15/2025    Credit Card  Cancelled
1    55000.0      Delhi    TS  500001.0  1/19/2025            COD  Cancelled
2     2000.0    Kolkata    MH  380001.0  1/18/2025            COD    Pending
3    30000.0  Ahmedabad    GJ  380001.0  1/18/2025     NetBanking  Cancelled
4    30000.0     Mumbai    TN  110001.0  1/16/2025     NetBanking    Pending
..       ...        ...   ...       ...        ...            ...        ...
164  55000.0  Hyderabad    KA  560001.0  1/16/2025     NetBanking  Delivered
165  30000.0  Hyderabad    KA  600001.0  1/11/2025            COD    Pending
166  30000.0  Ahmedabad    KA  600001.0  1/15/2025            UPI  Delivered
167   1500.0    Chennai    KA  400001.0  1/15/2025    Credit Card  Cancelled
168   1500.0  Bangalore    WB  380001.0  1/14/2025            UPI  Delivered

[169 rows x 13 columns]

In [ ]:
print(data1.to_string())

    order_id firstname lastname                   email     product  quantity    price       city state   pincode order_date payment_method     status
0       1001     Eswar    Reddy             e@gmail.com      Camera       2.0   1500.0    Chennai    WB  500001.0  1/15/2025    Credit Card  Cancelled
1       1003     Kiran    Mehta   kiran.mehta@email.com    Keyboard       1.0  55000.0      Delhi    TS  500001.0  1/19/2025            COD  Cancelled
2       1004     Kiran    Singh   kiran.singh@email.com      Camera       2.0   2000.0    Kolkata    MH  380001.0  1/18/2025            COD    Pending
3       1005     Rahul     Nair    rahul.nair@email.com    Keyboard       2.0  30000.0  Ahmedabad    GJ  380001.0  1/18/2025     NetBanking  Cancelled
4       1006     Pooja    Verma   pooja.verma@email.com      Mobile       1.0  30000.0     Mumbai    TN  110001.0  1/16/2025     NetBanking    Pending
5       1008     Sneha    Verma   sneha.verma@email.com      Laptop       1.0  30000.0  Hyderabad    MH  380001.0  1/20/2025            Upi    Pending
6       1010     Eswar     Nair     sita.nair@email.com  Headphones       1.0   2000.0     Mumbai    TN  560001.0  1/14/2025     NetBanking  Delivered
7       1012     Priya    Kumar   priya.kumar@email.com  Headphones       2.0  30000.0     Mumbai    MH  500001.0  1/16/2025     NetBanking   Returned
8       1013     Eswar    Singh    sita.singh@email.com       Mouse       1.0  30000.0      Delhi    GJ  600001.0  1/14/2025            COD  Delivered
9       1014     Priya    Reddy   priya.reddy@email.com      Camera       1.0  30000.0       Pune    TN  110001.0  1/18/2025            COD   Returned
10      1016      Amit   Sharma   amit.sharma@email.com    Keyboard       2.0  55000.0  Bangalore    MH  400001.0  1/17/2025    Credit Card  Delivered
11      1017     Kiran   Sharma  kiran.sharma@email.com    Keyboard       3.0   1500.0    Chennai    WB  560001.0  1/10/2025            Upi    Pending
12      1018     Rahul    Verma   rahul.verma@email.com     Charger       3.0  55000.0  Bangalore    MH  110001.0  1/20/2025            Upi   Returned
13      1019     Pooja   Sharma  pooja.sharma@email.com  Headphones       1.0   2000.0      Delhi    WB  380001.0  1/17/2025     NetBanking  Delivered
14      1020      Anil    Singh    anil.singh@email.com      Laptop       3.0   1500.0      Delhi    KA  560001.0  1/11/2025     NetBanking   Returned
15      1021     Rahul    Kumar   rahul.kumar@email.com      Mobile       3.0   2000.0        Hyd    GJ  380001.0  1/17/2025    Credit Card  Delivered
16      1022      Amit    Verma    amit.verma@email.com    Keyboard       2.0  30000.0     Mumbai    GJ  110001.0  1/13/2025            Upi    Pending
17      1023     Sneha    Verma         eswar@gmail.com      Tablet       2.0  30000.0       Pune    KA  400001.0  1/15/2025            Upi    Pending
18      1024     Pooja   Sharma  pooja.sharma@email.com      Camera       1.0  30000.0    Chennai    KA  560001.0  1/18/2025            Upi  Delivered
19      1025     Kiran    Mehta   kiran.mehta@email.com      Tablet       3.0  30000.0     Mumbai    GJ  500001.0  1/15/2025            COD  Delivered
20      1026      Anil    Reddy    anil.reddy@email.com  Headphones       2.0   2000.0    Kolkata    GJ  400001.0  1/15/2025     NetBanking  Delivered
21      1027     Eswar   Sharma   sita.sharma@email.com      Laptop       2.0  55000.0       Pune    DL  400001.0  1/15/2025            COD  Cancelled
22      1028     Eswar    Mehta    sita.mehta@email.com     Charger       1.0   1500.0  Bangalore    WB  380001.0  1/14/2025            Upi  Delivered
23      1029     Sneha    Reddy   sneha.reddy@email.com      Laptop       1.0   1500.0       Pune    TS  380001.0  1/18/2025     NetBanking  Delivered
24      1030      Amit    Patel         eswar@gmail.com     Charger       1.0  55000.0  Ahmedabad    TS  560001.0  1/10/2025    Credit Card  Cancelled
25      1031     Vikas    Kumar   vikas.kumar@email.com      Tablet       3.0  55000.0     Mumbai    DL  500001.0  1/16/2025            COD    Pending
26      1033     Priya    Patel   priya.patel@email.com    Keyboard       2.0   1500.0      Delhi    TS  380001.0  1/19/2025            COD  Delivered
27      1034     Rahul    Kumar   rahul.kumar@email.com     Charger       2.0   2000.0      Delhi    GJ  560001.0  1/13/2025            Upi  Delivered
28      1035     Priya    Gupta         eswar@gmail.com      Tablet       3.0  30000.0       Pune    KA  380001.0  1/19/2025    Credit Card  Delivered
29      1036      Anil    Gupta    anil.gupta@email.com      Camera       3.0  30000.0      Delhi    MH  380001.0  1/11/2025            COD    Pending
30      1038      Ravi    Mehta    ravi.mehta@email.com    Keyboard       3.0  30000.0  Ahmedabad    TN  560001.0  1/15/2025     NetBanking   Returned
31      1039      Amit      Das      amit.das@email.com      Camera       2.0  30000.0  Ahmedabad    TN  560001.0  1/18/2025            COD  Delivered
32      1040      Anil    Gupta    anil.gupta@email.com      Mobile       2.0  30000.0      Delhi    GJ  600001.0  1/14/2025            Upi  Cancelled
33      1041     Eswar    Singh    sita.singh@email.com  Headphones       1.0   1500.0        Hyd    TS  560001.0  1/11/2025    Credit card    Pending
34      1042     Sneha      Das     sneha.das@email.com  Headphones       1.0   1500.0    Chennai    KA  400001.0  1/15/2025    Credit card  Cancelled
35      1043      Amit     Nair     amit.nair@email.com      Mobile       2.0   2000.0  Ahmedabad    TS  600001.0  1/15/2025            COD    Pending
36      1044     Kiran    Gupta   kiran.gupta@email.com      Tablet       3.0  55000.0  Ahmedabad    KA  110001.0  1/14/2025    Credit card   Returned
37      1045     Pooja   Sharma  pooja.sharma@email.com    Keyboard       3.0  30000.0  Ahmedabad    TS  500001.0  1/10/2025    Credit card  Cancelled
38      1046      Amit    Kumar    amit.kumar@email.com  Headphones       3.0   2000.0      Delhi    TS  500001.0  1/16/2025     NetBanking    Pending
39      1047     Priya      Das     priya.das@email.com      Mobile       1.0   2000.0     Mumbai    WB  380001.0  1/16/2025     NetBanking  Delivered
40      1048      Anil    Kumar    anil.kumar@email.com  Headphones       3.0  55000.0        Hyd    WB  500001.0  1/20/2025            UPI   Returned
41      1049      Amit      Das      amit.das@email.com     Charger       3.0  30000.0  Ahmedabad    MH  600001.0  1/19/2025    Credit card  Delivered
42      1050      Anil    Mehta    anil.mehta@email.com      Laptop       3.0  30000.0    Kolkata    WB  600001.0  1/18/2025     NetBanking  Cancelled
43      1052     Eswar    Gupta         eswar@gmail.com       Mouse       2.0  55000.0     Mumbai    MH  110001.0  1/14/2025     NetBanking   Returned
44      1053      Ravi    Singh    ravi.singh@email.com     Charger       3.0  55000.0      Delhi    WB  110001.0  1/18/2025    Credit card    Pending
45      1054     Rahul    Patel         eswar@gmail.com      Tablet       3.0   1500.0       Pune    GJ  560001.0  1/20/2025     NetBanking   Returned
46      1056      Amit     Nair         eswar@gmail.com    Keyboard       3.0  55000.0  Bangalore    GJ  500001.0  1/10/2025    Credit card  Cancelled
47      1057      Anil    Verma         eswar@gmail.com  Headphones       3.0  30000.0      Delhi    KA  400001.0  1/16/2025            COD  Cancelled
48      1058     Eswar    Mehta    sita.mehta@email.com  Headphones       2.0   1500.0      Delhi    MH  380001.0  1/19/2025     NetBanking   Returned
49      1059     Kiran      Das     kiran.das@email.com    Keyboard       2.0  30000.0       Pune    TS  110001.0  1/11/2025            COD  Delivered
50      1060     Rahul    Kumar   rahul.kumar@email.com      Laptop       1.0  30000.0  Bangalore    GJ  400001.0  1/11/2025            UPI  Delivered
51      1061      Ravi      Das      ravi.das@email.com      Camera       3.0   2000.0     Mumbai    GJ  500001.0  1/20/2025    Credit card    Pending
52      1062      Ravi    Kumar         eswar@gmail.com      Camera       3.0   1500.0  Hyderabad    MH  400001.0  1/14/2025    Credit Card    Pending
53      1063     Vikas    Singh   vikas.singh@email.com      Mobile       3.0  30000.0    Chennai    DL  110001.0  1/13/2025            COD    Pending
54      1064      Anil    Gupta    anil.gupta@email.com      Laptop       1.0  30000.0      Delhi    TS  110001.0  1/12/2025            COD  Cancelled
55      1065     Pooja    Singh   pooja.singh@email.com       Mouse       1.0   1500.0  Bangalore    WB  500001.0  1/18/2025            COD    Pending
56      1066     Pooja    Verma   pooja.verma@email.com      Mobile       2.0  30000.0       Pune    MH  500001.0  1/12/2025    Credit Card  Delivered
57      1067     Priya    Singh         eswar@gmail.com      Camera       3.0  30000.0       Pune    GJ  560001.0  1/12/2025     NetBanking  Delivered
58      1069     Vikas   Sharma  vikas.sharma@email.com       Mouse       3.0  55000.0  Hyderabad    MH  560001.0  1/16/2025     NetBanking   Returned
59      1070      Ravi    Reddy    ravi.reddy@email.com      Laptop       1.0  55000.0  Ahmedabad    KA  560001.0  1/17/2025     NetBanking   Returned
60      1071     Kiran    Kumar   kiran.kumar@email.com       Mouse       3.0  30000.0  Ahmedabad    DL  500001.0  1/10/2025            UPI  Cancelled
61      1072      Ravi    Mehta    ravi.mehta@email.com      Camera       3.0  30000.0      Delhi    TN  560001.0  1/15/2025     NetBanking  Delivered
62      1073      Ravi     Nair     ravi.nair@email.com     Charger       2.0  55000.0       Pune    MH  560001.0  1/18/2025            COD    Pending
63      1074     Eswar      Das      sita.das@email.com      Mobile       2.0  30000.0  Bangalore    MH  560001.0  1/10/2025     NetBanking  Delivered
64      1075     Vikas    Kumar   vikas.kumar@email.com    Keyboard       2.0  30000.0  Bangalore    KA  560001.0  1/15/2025            COD    Pending
65      1076      Amit    Patel    amit.patel@email.com      Laptop       3.0  30000.0  Bangalore    TS  500001.0  1/10/2025    Credit Card   Returned
66      1077     Priya    Patel   priya.patel@email.com  Headphones       2.0  30000.0       Pune    TN  560001.0  1/14/2025     NetBanking  Delivered
67      1078     Priya    Singh   priya.singh@email.com    Keyboard       2.0  30000.0       Pune    MH  560001.0  1/16/2025    Credit Card   Returned
68      1080      Amit    Mehta    amit.mehta@email.com      Camera       2.0   1500.0    Chennai    TN  400001.0  1/17/2025            COD  Cancelled
69      1081      Anil    Mehta    anil.mehta@email.com      Camera       2.0  55000.0  Ahmedabad    TN  400001.0  1/17/2025     NetBanking  Delivered
70      1084     Pooja    Singh   pooja.singh@email.com  Headphones       3.0  30000.0       Bang    TN  400001.0  1/19/2025    Credit Card    Pending
71      1085      Anil    Patel    anil.patel@email.com      Mobile       3.0  30000.0       Bang    DL  600001.0  1/11/2025    Credit Card   Returned
72      1086     Pooja    Patel   pooja.patel@email.com    Keyboard       1.0  55000.0    Chennai    MH  110001.0  1/15/2025            COD    Pending
73      1087     Kiran    Verma   kiran.verma@email.com      Mobile       1.0   1500.0       Bang    WB  560001.0  1/20/2025            UPI   Returned
74      1088     Eswar    Kumar    sita.kumar@email.com      Mobile       1.0  55000.0  Hyderabad    MH  380001.0  1/11/2025    Credit Card   Returned
75      1089     Sneha    Singh         eswar@gmail.com    Keyboard       1.0  30000.0      Delhi    MH  600001.0  1/16/2025            COD   Returned
76      1090      Amit    Mehta    amit.mehta@email.com     Charger       2.0   1500.0  Ahmedabad    TS  380001.0  1/15/2025    Credit Card  Cancelled
77      1091     Pooja    Kumar   pooja.kumar@email.com       Mouse       2.0   1500.0    Kolkata    TN  560001.0  1/15/2025            COD  Delivered
78      1092      Anil    Mehta    anil.mehta@email.com  Headphones       2.0   1500.0       Bang    KA  380001.0  1/20/2025            UPI  Cancelled
79      1093     Kiran   Sharma  kiran.sharma@email.com     Charger       2.0   1500.0       Bang    DL  110001.0  1/17/2025            COD    Pending
80      1094     Kiran    Kumar   kiran.kumar@email.com      Tablet       1.0  30000.0       Pune    TN  110001.0  1/19/2025            COD  Delivered
81      1096     Kiran    Reddy   kiran.reddy@email.com    Keyboard       1.0  30000.0  Hyderabad    WB  500001.0  1/14/2025            COD    Pending
82      1097     Kiran    Kumar         eswar@gmail.com      Tablet       1.0  55000.0    Kolkata    TS  560001.0  1/20/2025            COD    Pending
83      1099      Amit    Verma    amit.verma@email.com      Camera       1.0  30000.0       Bang    WB  380001.0  1/20/2025            UPI  Delivered
84      1100     Sneha   Sharma  sneha.sharma@email.com      Laptop       3.0  55000.0  Bangalore    GJ  600001.0  1/11/2025     NetBanking   Returned
85      1102     Pooja    Reddy   pooja.reddy@email.com       Mouse       1.0   1500.0  Bangalore    TN  560001.0  1/13/2025            COD  Cancelled
86      1103     Sneha    Mehta   sneha.mehta@email.com    Keyboard       3.0   1500.0  Bangalore    WB  500001.0  1/12/2025            UPI  Delivered
87      1104     Eswar    Verma    sita.verma@email.com      Laptop       3.0  55000.0  Hyderabad    KA  500001.0  1/13/2025    Credit Card    Pending
88      1105      Anil   Sharma   anil.sharma@email.com      Laptop       1.0   1500.0  Bangalore    MH  400001.0  1/11/2025            COD    Pending
89      1106     Vikas    Kumar   vikas.kumar@email.com      Laptop       3.0   2000.0    Kolkata    TN  500001.0  1/12/2025     NetBanking  Delivered
90      1108     Vikas      Das     vikas.das@email.com      Camera       3.0  55000.0    Chennai    KA  380001.0  1/19/2025     NetBanking    Pending
91      1109      Amit   Sharma   amit.sharma@email.com      Laptop       3.0   2000.0  Bangalore    TN  400001.0  1/14/2025     NetBanking   Returned
92      1112     Rahul    Mehta   rahul.mehta@email.com    Keyboard       3.0   2000.0  Hyderabad    KA  380001.0  1/14/2025            COD  Cancelled
93      1113     Kiran      Das     kiran.das@email.com      Tablet       1.0   1500.0  Hyderabad    GJ  500001.0  1/15/2025            COD    Pending
94      1114      Anil    Patel    anil.patel@email.com      Laptop       2.0   2000.0  Ahmedabad    TN  110001.0  1/10/2025     NetBanking  Delivered
95      1115     Pooja    Patel   pooja.patel@email.com  Headphones       1.0   2000.0    Kolkata    TN  500001.0  1/10/2025            UPI   Returned
96      1116     Pooja      Das     pooja.das@email.com       Mouse       1.0   2000.0       Pune    GJ  380001.0  1/10/2025    Credit Card    Pending
97      1117     Pooja    Singh   pooja.singh@email.com      Tablet       3.0   2000.0  Hyderabad    WB  560001.0  1/10/2025            UPI    Pending
98      1119      Amit    Reddy    amit.reddy@email.com       Mouse       2.0   2000.0  Ahmedabad    KA  400001.0  1/20/2025    Credit Card    Pending
99      1120      Ravi      Das      ravi.das@email.com      Mobile       3.0   1500.0  Ahmedabad    GJ  500001.0  1/20/2025            UPI    Pending
100     1122      Ravi    Gupta    ravi.gupta@email.com  Headphones       1.0   1500.0     Mumbai    TN  110001.0  1/18/2025     NetBanking    Pending
101     1123     Vikas    Patel   vikas.patel@email.com    Keyboard       3.0   1500.0  Hyderabad    TN  560001.0  1/17/2025     NetBanking   Returned
102     1124     Sneha    Kumar   sneha.kumar@email.com      Laptop       2.0  30000.0    Kolkata    MH  560001.0  1/17/2025            UPI  Delivered
103     1125     Eswar   Sharma   sita.sharma@email.com      Camera       2.0  55000.0     Mumbai    TN  110001.0  1/15/2025            COD  Delivered
104     1126     Rahul    Reddy   rahul.reddy@email.com  Headphones       3.0   1500.0      Delhi    TN  600001.0  1/20/2025    Credit Card  Delivered
105     1127      Anil      Das      anil.das@email.com    Keyboard       3.0   2000.0  Hyderabad    DL  400001.0  1/18/2025            UPI  Cancelled
106     1128     Pooja    Reddy   pooja.reddy@email.com      Laptop       2.0   2000.0      Delhi    TN  560001.0  1/13/2025            COD    Pending
107     1129     Kiran    Mehta   kiran.mehta@email.com     Charger       1.0   1500.0    Chennai    TN  560001.0  1/20/2025     NetBanking   Returned
108     1130     Rahul    Verma   rahul.verma@email.com  Headphones       3.0  30000.0  Ahmedabad    WB  560001.0  1/14/2025            UPI  Cancelled
109     1131     Vikas    Singh   vikas.singh@email.com      Camera       3.0  30000.0  Ahmedabad    TN  500001.0  1/16/2025            COD    Pending
110     1132      Anil   Sharma   anil.sharma@email.com  Headphones       3.0  55000.0    Kolkata    MH  500001.0  1/20/2025            UPI  Cancelled
111     1133     Pooja     Nair    pooja.nair@email.com       Mouse       1.0  55000.0    Kolkata    TS  500001.0  1/17/2025            COD  Cancelled
112     1134      Ravi    Kumar    ravi.kumar@email.com      Mobile       1.0   1500.0  Ahmedabad    TN  110001.0  1/20/2025            COD   Returned
113     1135      Amit    Reddy    amit.reddy@email.com      Laptop       1.0   1500.0  Hyderabad    KA  110001.0  1/12/2025    Credit Card   Returned
114     1136     Eswar    Singh    sita.singh@email.com      Mobile       3.0   2000.0  Bangalore    GJ  400001.0  1/16/2025            UPI    Pending
115     1137      Anil     Nair     anil.nair@email.com      Tablet       3.0   2000.0  Bangalore    DL  600001.0  1/14/2025     NetBanking   Returned
116     1138      Anil    Verma    anil.verma@email.com      Tablet       3.0  55000.0  Hyderabad    GJ  380001.0  1/15/2025     NetBanking  Cancelled
117     1141     Sneha    Verma   sneha.verma@email.com       Mouse       1.0  30000.0      Delhi    MH  380001.0  1/16/2025            COD  Cancelled
118     1143     Priya    Reddy   priya.reddy@email.com      Laptop       3.0   2000.0  Bangalore    TS  400001.0  1/16/2025            COD  Cancelled
119     1144      Ravi    Verma         eswar@gmail.com       Mouse       3.0   1500.0  Ahmedabad    TN  400001.0  1/12/2025    Credit Card  Delivered
120     1145     Kiran      Das     kiran.das@email.com      Camera       3.0   1500.0  Ahmedabad    TN  600001.0  1/15/2025            UPI    Pending
121     1147      Amit    Mehta    amit.mehta@email.com    Keyboard       3.0   1500.0  Ahmedabad    GJ  400001.0  1/12/2025            COD  Delivered
122     1148     Pooja    Singh   pooja.singh@email.com     Charger       3.0   2000.0  Hyderabad    TS  400001.0  1/20/2025     NetBanking  Delivered
123     1149      Anil    Verma    anil.verma@email.com      Laptop       3.0   2000.0    Kolkata    KA  110001.0  1/19/2025            COD    Pending
124     1150     Eswar   Sharma         eswar@gmail.com      Camera       3.0   2000.0  Hyderabad    WB  110001.0  1/20/2025            UPI    Pending
125     1151      Ravi    Singh    ravi.singh@email.com    Keyboard       3.0   1500.0       Pune    TN  110001.0  1/13/2025    Credit Card   Returned
126     1152     Eswar    Patel    sita.patel@email.com  Headphones       2.0  30000.0     Mumbai    MH  500001.0  1/14/2025    Credit Card  Cancelled
127     1153     Sneha    Kumar         eswar@gmail.com     Charger       2.0   1500.0  Hyderabad    MH  600001.0  1/20/2025            COD  Cancelled
128     1154     Sneha    Gupta   sneha.gupta@email.com  Headphones       3.0   1500.0       Pune    MH  110001.0  1/20/2025    Credit Card   Returned
129     1156     Vikas     Nair    vikas.nair@email.com     Charger       3.0   2000.0    Chennai    DL  600001.0  1/16/2025     NetBanking  Delivered
130     1157     Pooja    Mehta   pooja.mehta@email.com      Camera       3.0   1500.0    Chennai    DL  560001.0  1/10/2025    Credit Card  Cancelled

In [ ]:
print(data1.at[4,'firstname'])

Pooja

In [ ]:
print(data1.iat[4,1])

Pooja

In [ ]:
data1=data1.set_index(['order_id'])

In [ ]:
print(data1)

         firstname lastname                  email     product  quantity  \
order_id
1001         Eswar    Reddy            e@gmail.com      Camera       2.0
1003         Kiran    Mehta  kiran.mehta@email.com    Keyboard       1.0
1004         Kiran    Singh  kiran.singh@email.com      Camera       2.0
1005         Rahul     Nair   rahul.nair@email.com    Keyboard       2.0
1006         Pooja    Verma  pooja.verma@email.com      Mobile       1.0
...            ...      ...                    ...         ...       ...
1198         Vikas    Kumar        eswar@gmail.com      Camera       1.0
1199          Amit    Reddy   amit.reddy@email.com      Camera       2.0
1200         Pooja    Gupta  pooja.gupta@email.com      Tablet       2.0
1042         Sneha      Das    sneha.das@email.com  Headphones       1.0
1028         Eswar    Mehta   sita.mehta@email.com     Charger       1.0

            price       city state   pincode order_date payment_method  \
order_id
1001       1500.0    Chennai    WB  500001.0  1/15/2025    Credit Card
1003      55000.0      Delhi    TS  500001.0  1/19/2025            COD
1004       2000.0    Kolkata    MH  380001.0  1/18/2025            COD
1005      30000.0  Ahmedabad    GJ  380001.0  1/18/2025     NetBanking
1006      30000.0     Mumbai    TN  110001.0  1/16/2025     NetBanking
...           ...        ...   ...       ...        ...            ...
1198      55000.0  Hyderabad    KA  560001.0  1/16/2025     NetBanking
1199      30000.0  Hyderabad    KA  600001.0  1/11/2025            COD
1200      30000.0  Ahmedabad    KA  600001.0  1/15/2025            UPI
1042       1500.0    Chennai    KA  400001.0  1/15/2025    Credit Card
1028       1500.0  Bangalore    WB  380001.0  1/14/2025            UPI

             status
order_id
1001      Cancelled
1003      Cancelled
1004        Pending
1005      Cancelled
1006        Pending
...             ...
1198      Delivered
1199        Pending
1200      Delivered
1042      Cancelled
1028      Delivered

[169 rows x 12 columns]

In [ ]:
print(data1.at['1006','firstname'])

Pooja

In [ ]:
print(data1.iat[4,1])

Verma