In [77]:
import pandas as pd

In [78]:
data=pd.read_csv("/content/Orders_2024_Jan_Jun.csv")

In [79]:
data

,OrderID,OrderDate,CustomerID,CustomerName,Region,ProductID,ProductName,Category,Quantity,Price,TotalAmount,PaymentMethod
0,1001,5/21/2024,2,Customer_2,E,9,Product_9,Grocery,9,1047,9423,UPI
1,1002,1/18/2024,37,Customer_37,North,19,Product_19,Home Decor,1,1563,1563,NetBanking
2,1003,3/28/2024,9,Customer_9,South,12,Product_12,Home Decor,4,1539,6156,COD
3,1004,3/29/2024,40,Customer_40,West,14,Product_14,Grocery,3,204,612,NetBanking
4,1005,5/25/2024,40,Customer_40,West,14,Product_14,Grocery,9,204,1836,COD
...,...,...,...,...,...,...,...,...,...,...,...,...
265,1020,4/5/2024,31,Customer_31,South,2,Product_2,Home Decor,7,481,3367,NetBanking
266,1021,3/15/2024,38,Customer_38,North,8,Product_8,Home Decor,1,1924,1924,UPI
267,1022,3/3/2024,28,Customer_28,North,4,Product_4,Grocery,10,1380,13800,COD
268,1023,6/24/2024,35,Customer_35,East,9,Product_9,Grocery,2,1047,2094,Card
269,1024,1/5/2024,46,Customer_46,South,16,Product_16,Electronics,10,1948,19480,UPI

In [80]:
data.columns

Index(['OrderID', 'OrderDate', 'CustomerID', 'CustomerName', 'Region',
       'ProductID', 'ProductName', 'Category', 'Quantity', 'Price',
       'TotalAmount', 'PaymentMethod'],
      dtype='object')

In [81]:
data=data.set_index(['CustomerID'])

In [82]:
data

,OrderID,OrderDate,CustomerName,Region,ProductID,ProductName,Category,Quantity,Price,TotalAmount,PaymentMethod
CustomerID,,,,,,,,,,,
2,1001,5/21/2024,Customer_2,E,9,Product_9,Grocery,9,1047,9423,UPI
37,1002,1/18/2024,Customer_37,North,19,Product_19,Home Decor,1,1563,1563,NetBanking
9,1003,3/28/2024,Customer_9,South,12,Product_12,Home Decor,4,1539,6156,COD
40,1004,3/29/2024,Customer_40,West,14,Product_14,Grocery,3,204,612,NetBanking
40,1005,5/25/2024,Customer_40,West,14,Product_14,Grocery,9,204,1836,COD
...,...,...,...,...,...,...,...,...,...,...,...
31,1020,4/5/2024,Customer_31,South,2,Product_2,Home Decor,7,481,3367,NetBanking
38,1021,3/15/2024,Customer_38,North,8,Product_8,Home Decor,1,1924,1924,UPI
28,1022,3/3/2024,Customer_28,North,4,Product_4,Grocery,10,1380,13800,COD
35,1023,6/24/2024,Customer_35,East,9,Product_9,Grocery,2,1047,2094,Card
46,1024,1/5/2024,Customer_46,South,16,Product_16,Electronics,10,1948,19480,UPI

In [83]:
data=data.reset_index()

In [84]:
data

,CustomerID,OrderID,OrderDate,CustomerName,Region,ProductID,ProductName,Category,Quantity,Price,TotalAmount,PaymentMethod
0,2,1001,5/21/2024,Customer_2,E,9,Product_9,Grocery,9,1047,9423,UPI
1,37,1002,1/18/2024,Customer_37,North,19,Product_19,Home Decor,1,1563,1563,NetBanking
2,9,1003,3/28/2024,Customer_9,South,12,Product_12,Home Decor,4,1539,6156,COD
3,40,1004,3/29/2024,Customer_40,West,14,Product_14,Grocery,3,204,612,NetBanking
4,40,1005,5/25/2024,Customer_40,West,14,Product_14,Grocery,9,204,1836,COD
...,...,...,...,...,...,...,...,...,...,...,...,...
265,31,1020,4/5/2024,Customer_31,South,2,Product_2,Home Decor,7,481,3367,NetBanking
266,38,1021,3/15/2024,Customer_38,North,8,Product_8,Home Decor,1,1924,1924,UPI
267,28,1022,3/3/2024,Customer_28,North,4,Product_4,Grocery,10,1380,13800,COD
268,35,1023,6/24/2024,Customer_35,East,9,Product_9,Grocery,2,1047,2094,Card
269,46,1024,1/5/2024,Customer_46,South,16,Product_16,Electronics,10,1948,19480,UPI

In [85]:
data=data.drop_duplicates()

In [86]:
data

,CustomerID,OrderID,OrderDate,CustomerName,Region,ProductID,ProductName,Category,Quantity,Price,TotalAmount,PaymentMethod
0,2,1001,5/21/2024,Customer_2,E,9,Product_9,Grocery,9,1047,9423,UPI
1,37,1002,1/18/2024,Customer_37,North,19,Product_19,Home Decor,1,1563,1563,NetBanking
2,9,1003,3/28/2024,Customer_9,South,12,Product_12,Home Decor,4,1539,6156,COD
3,40,1004,3/29/2024,Customer_40,West,14,Product_14,Grocery,3,204,612,NetBanking
4,40,1005,5/25/2024,Customer_40,West,14,Product_14,Grocery,9,204,1836,COD
...,...,...,...,...,...,...,...,...,...,...,...,...
255,39,1010,2/11/2024,Customer_39,East,5,Product_5,Electronics,1,632,632,NetBanking
258,45,1013,5/22/2024,Customer_45,East,1,Product_1,Grocery,1,574,574,Card
261,26,1016,5/29/2024,Customer_26,East,8,Product_8,Home Decor,8,1924,15392,COD
262,25,1017,4/26/2024,Customer_25,East,8,Product_8,Home Decor,6,1924,11544,Card
268,35,1023,6/24/2024,Customer_35,East,9,Product_9,Grocery,2,1047,2094,Card

In [87]:
data=data.set_index(['CustomerID'])

In [88]:
data

,OrderID,OrderDate,CustomerName,Region,ProductID,ProductName,Category,Quantity,Price,TotalAmount,PaymentMethod
CustomerID,,,,,,,,,,,
2,1001,5/21/2024,Customer_2,E,9,Product_9,Grocery,9,1047,9423,UPI
37,1002,1/18/2024,Customer_37,North,19,Product_19,Home Decor,1,1563,1563,NetBanking
9,1003,3/28/2024,Customer_9,South,12,Product_12,Home Decor,4,1539,6156,COD
40,1004,3/29/2024,Customer_40,West,14,Product_14,Grocery,3,204,612,NetBanking
40,1005,5/25/2024,Customer_40,West,14,Product_14,Grocery,9,204,1836,COD
...,...,...,...,...,...,...,...,...,...,...,...
39,1010,2/11/2024,Customer_39,East,5,Product_5,Electronics,1,632,632,NetBanking
45,1013,5/22/2024,Customer_45,East,1,Product_1,Grocery,1,574,574,Card
26,1016,5/29/2024,Customer_26,East,8,Product_8,Home Decor,8,1924,15392,COD
25,1017,4/26/2024,Customer_25,East,8,Product_8,Home Decor,6,1924,11544,Card
35,1023,6/24/2024,Customer_35,East,9,Product_9,Grocery,2,1047,2094,Card

In [89]:
data.at[37,'CustomerName']

CustomerID
37    Customer_37
37    Customer_37
37    Customer_37
Name: CustomerName, dtype: object

In [90]:
data.iat[1,2]

'Customer_37'

In [91]:
data=data.reset_index()

In [92]:
data

,CustomerID,OrderID,OrderDate,CustomerName,Region,ProductID,ProductName,Category,Quantity,Price,TotalAmount,PaymentMethod
0,2,1001,5/21/2024,Customer_2,E,9,Product_9,Grocery,9,1047,9423,UPI
1,37,1002,1/18/2024,Customer_37,North,19,Product_19,Home Decor,1,1563,1563,NetBanking
2,9,1003,3/28/2024,Customer_9,South,12,Product_12,Home Decor,4,1539,6156,COD
3,40,1004,3/29/2024,Customer_40,West,14,Product_14,Grocery,3,204,612,NetBanking
4,40,1005,5/25/2024,Customer_40,West,14,Product_14,Grocery,9,204,1836,COD
...,...,...,...,...,...,...,...,...,...,...,...,...
249,39,1010,2/11/2024,Customer_39,East,5,Product_5,Electronics,1,632,632,NetBanking
250,45,1013,5/22/2024,Customer_45,East,1,Product_1,Grocery,1,574,574,Card
251,26,1016,5/29/2024,Customer_26,East,8,Product_8,Home Decor,8,1924,15392,COD
252,25,1017,4/26/2024,Customer_25,East,8,Product_8,Home Decor,6,1924,11544,Card
253,35,1023,6/24/2024,Customer_35,East,9,Product_9,Grocery,2,1047,2094,Card

In [93]:
data.loc[1:10:2,'CustomerName':'Category':2]

  CustomerName  ProductID     Category
1  Customer_37         19   Home Decor
3  Customer_40         14      Grocery
5  Customer_48         17  Electronics
7  Customer_30         12   Home Decor
9  Customer_39          5  Electronics

In [94]:
data.loc[2:4:1,'Category':'TotalAmount':2]

     Category  Price
2  Home Decor   1539
3     Grocery    204
4     Grocery    204

In [95]:
data

,CustomerID,OrderID,OrderDate,CustomerName,Region,ProductID,ProductName,Category,Quantity,Price,TotalAmount,PaymentMethod
0,2,1001,5/21/2024,Customer_2,E,9,Product_9,Grocery,9,1047,9423,UPI
1,37,1002,1/18/2024,Customer_37,North,19,Product_19,Home Decor,1,1563,1563,NetBanking
2,9,1003,3/28/2024,Customer_9,South,12,Product_12,Home Decor,4,1539,6156,COD
3,40,1004,3/29/2024,Customer_40,West,14,Product_14,Grocery,3,204,612,NetBanking
4,40,1005,5/25/2024,Customer_40,West,14,Product_14,Grocery,9,204,1836,COD
...,...,...,...,...,...,...,...,...,...,...,...,...
249,39,1010,2/11/2024,Customer_39,East,5,Product_5,Electronics,1,632,632,NetBanking
250,45,1013,5/22/2024,Customer_45,East,1,Product_1,Grocery,1,574,574,Card
251,26,1016,5/29/2024,Customer_26,East,8,Product_8,Home Decor,8,1924,15392,COD
252,25,1017,4/26/2024,Customer_25,East,8,Product_8,Home Decor,6,1924,11544,Card
253,35,1023,6/24/2024,Customer_35,East,9,Product_9,Grocery,2,1047,2094,Card

In [96]:
data.iloc[1:5:2,2:5:2]

   OrderDate Region
1  1/18/2024  North
3  3/29/2024   West

In [97]:
data

,CustomerID,OrderID,OrderDate,CustomerName,Region,ProductID,ProductName,Category,Quantity,Price,TotalAmount,PaymentMethod
0,2,1001,5/21/2024,Customer_2,E,9,Product_9,Grocery,9,1047,9423,UPI
1,37,1002,1/18/2024,Customer_37,North,19,Product_19,Home Decor,1,1563,1563,NetBanking
2,9,1003,3/28/2024,Customer_9,South,12,Product_12,Home Decor,4,1539,6156,COD
3,40,1004,3/29/2024,Customer_40,West,14,Product_14,Grocery,3,204,612,NetBanking
4,40,1005,5/25/2024,Customer_40,West,14,Product_14,Grocery,9,204,1836,COD
...,...,...,...,...,...,...,...,...,...,...,...,...
249,39,1010,2/11/2024,Customer_39,East,5,Product_5,Electronics,1,632,632,NetBanking
250,45,1013,5/22/2024,Customer_45,East,1,Product_1,Grocery,1,574,574,Card
251,26,1016,5/29/2024,Customer_26,East,8,Product_8,Home Decor,8,1924,15392,COD
252,25,1017,4/26/2024,Customer_25,East,8,Product_8,Home Decor,6,1924,11544,Card
253,35,1023,6/24/2024,Customer_35,East,9,Product_9,Grocery,2,1047,2094,Card

In [98]:
data.sort_values(['Region'],ascending=True)

,CustomerID,OrderID,OrderDate,CustomerName,Region,ProductID,ProductName,Category,Quantity,Price,TotalAmount,PaymentMethod
0,2,1001,5/21/2024,Customer_2,E,9,Product_9,Grocery,9,1047,9423,UPI
22,35,1023,6/24/2024,Customer_35,E,9,Product_9,Grocery,2,1047,2094,Card
5,48,1006,6/28/2024,Customer_48,E,17,Product_17,Electronics,4,1320,5280,COD
6,25,1007,2/14/2024,Customer_25,E,18,Product_18,Home Decor,1,1099,1099,Card
9,39,1010,2/11/2024,Customer_39,E,5,Product_5,Electronics,1,632,632,NetBanking
...,...,...,...,...,...,...,...,...,...,...,...,...
31,5,1032,5/20/2024,Customer_5,West,14,Product_14,Grocery,9,204,1836,NetBanking
127,29,1128,1/10/2024,Customer_29,West,9,Product_9,Grocery,7,1047,7329,COD
178,5,1179,3/3/2024,Customer_5,West,14,Product_14,Grocery,9,204,1836,COD
196,21,1197,1/1/2024,Customer_21,West,5,Product_5,Electronics,5,632,3160,Card
201,27,2008,9/7/2024,Customer_27,West,3,Product_3,Electronics,3,1214,3642,UPI

In [99]:
data.sort_index(ascending=False)

,CustomerID,OrderID,OrderDate,CustomerName,Region,ProductID,ProductName,Category,Quantity,Price,TotalAmount,PaymentMethod
253,35,1023,6/24/2024,Customer_35,East,9,Product_9,Grocery,2,1047,2094,Card
252,25,1017,4/26/2024,Customer_25,East,8,Product_8,Home Decor,6,1924,11544,Card
251,26,1016,5/29/2024,Customer_26,East,8,Product_8,Home Decor,8,1924,15392,COD
250,45,1013,5/22/2024,Customer_45,East,1,Product_1,Grocery,1,574,574,Card
249,39,1010,2/11/2024,Customer_39,East,5,Product_5,Electronics,1,632,632,NetBanking
...,...,...,...,...,...,...,...,...,...,...,...,...
4,40,1005,5/25/2024,Customer_40,West,14,Product_14,Grocery,9,204,1836,COD
3,40,1004,3/29/2024,Customer_40,West,14,Product_14,Grocery,3,204,612,NetBanking
2,9,1003,3/28/2024,Customer_9,South,12,Product_12,Home Decor,4,1539,6156,COD
1,37,1002,1/18/2024,Customer_37,North,19,Product_19,Home Decor,1,1563,1563,NetBanking
0,2,1001,5/21/2024,Customer_2,E,9,Product_9,Grocery,9,1047,9423,UPI

In [100]:
data

,CustomerID,OrderID,OrderDate,CustomerName,Region,ProductID,ProductName,Category,Quantity,Price,TotalAmount,PaymentMethod
0,2,1001,5/21/2024,Customer_2,E,9,Product_9,Grocery,9,1047,9423,UPI
1,37,1002,1/18/2024,Customer_37,North,19,Product_19,Home Decor,1,1563,1563,NetBanking
2,9,1003,3/28/2024,Customer_9,South,12,Product_12,Home Decor,4,1539,6156,COD
3,40,1004,3/29/2024,Customer_40,West,14,Product_14,Grocery,3,204,612,NetBanking
4,40,1005,5/25/2024,Customer_40,West,14,Product_14,Grocery,9,204,1836,COD
...,...,...,...,...,...,...,...,...,...,...,...,...
249,39,1010,2/11/2024,Customer_39,East,5,Product_5,Electronics,1,632,632,NetBanking
250,45,1013,5/22/2024,Customer_45,East,1,Product_1,Grocery,1,574,574,Card
251,26,1016,5/29/2024,Customer_26,East,8,Product_8,Home Decor,8,1924,15392,COD
252,25,1017,4/26/2024,Customer_25,East,8,Product_8,Home Decor,6,1924,11544,Card
253,35,1023,6/24/2024,Customer_35,East,9,Product_9,Grocery,2,1047,2094,Card

In [101]:
data.nlargest(5,'Price')

,CustomerID,OrderID,OrderDate,CustomerName,Region,ProductID,ProductName,Category,Quantity,Price,TotalAmount,PaymentMethod
23,46,1024,1/5/2024,Customer_46,South,16,Product_16,Electronics,10,1948,19480,UPI
28,27,1029,2/4/2024,Customer_27,West,16,Product_16,Electronics,5,1948,9740,Card
50,43,1051,5/15/2024,Customer_43,South,16,Product_16,Electronics,6,1948,11688,Card
56,35,1057,1/26/2024,Customer_35,East,16,Product_16,Electronics,1,1948,1948,NetBanking
59,26,1060,2/15/2024,Customer_26,East,16,Product_16,Electronics,6,1948,11688,NetBanking

In [102]:
data.nsmallest(4,'Quantity')

,CustomerID,OrderID,OrderDate,CustomerName,Region,ProductID,ProductName,Category,Quantity,Price,TotalAmount,PaymentMethod
1,37,1002,1/18/2024,Customer_37,North,19,Product_19,Home Decor,1,1563,1563,NetBanking
6,25,1007,2/14/2024,Customer_25,E,18,Product_18,Home Decor,1,1099,1099,Card
9,39,1010,2/11/2024,Customer_39,E,5,Product_5,Electronics,1,632,632,NetBanking
12,45,1013,5/22/2024,Customer_45,E,1,Product_1,Grocery,1,574,574,Card

In [103]:
data

,CustomerID,OrderID,OrderDate,CustomerName,Region,ProductID,ProductName,Category,Quantity,Price,TotalAmount,PaymentMethod
0,2,1001,5/21/2024,Customer_2,E,9,Product_9,Grocery,9,1047,9423,UPI
1,37,1002,1/18/2024,Customer_37,North,19,Product_19,Home Decor,1,1563,1563,NetBanking
2,9,1003,3/28/2024,Customer_9,South,12,Product_12,Home Decor,4,1539,6156,COD
3,40,1004,3/29/2024,Customer_40,West,14,Product_14,Grocery,3,204,612,NetBanking
4,40,1005,5/25/2024,Customer_40,West,14,Product_14,Grocery,9,204,1836,COD
...,...,...,...,...,...,...,...,...,...,...,...,...
249,39,1010,2/11/2024,Customer_39,East,5,Product_5,Electronics,1,632,632,NetBanking
250,45,1013,5/22/2024,Customer_45,East,1,Product_1,Grocery,1,574,574,Card
251,26,1016,5/29/2024,Customer_26,East,8,Product_8,Home Decor,8,1924,15392,COD
252,25,1017,4/26/2024,Customer_25,East,8,Product_8,Home Decor,6,1924,11544,Card
253,35,1023,6/24/2024,Customer_35,East,9,Product_9,Grocery,2,1047,2094,Card

In [104]:
data.query("Region=='North'")

,CustomerID,OrderID,OrderDate,CustomerName,Region,ProductID,ProductName,Category,Quantity,Price,TotalAmount,PaymentMethod
1,37,1002,1/18/2024,Customer_37,North,19,Product_19,Home Decor,1,1563,1563,NetBanking
13,16,1014,6/15/2024,Customer_16,North,8,Product_8,Home Decor,9,1924,17316,COD
18,16,1019,3/23/2024,Customer_16,North,14,Product_14,Grocery,3,204,612,NetBanking
20,38,1021,3/15/2024,Customer_38,North,8,Product_8,Home Decor,1,1924,1924,UPI
21,28,1022,3/3/2024,Customer_28,North,4,Product_4,Grocery,10,1380,13800,COD
26,4,1027,4/18/2024,Customer_4,North,2,Product_2,Home Decor,4,481,1924,UPI
33,16,1034,1/24/2024,Customer_16,North,14,Product_14,Grocery,2,204,408,UPI
35,10,1036,6/27/2024,Customer_10,North,15,Product_15,Grocery,10,976,9760,NetBanking
42,44,1043,5/15/2024,Customer_44,North,15,Product_15,Grocery,3,976,2928,COD
43,8,1044,3/30/2024,Customer_8,North,12,Product_12,Home Decor,10,1539,15390,NetBanking
45,34,1046,3/6/2024,Customer_34,North,15,Product_15,Grocery,5,976,4880,Card
51,38,1052,6/3/2024,Customer_38,North,11,Product_11,Grocery,4,1093,4372,Card
54,8,1055,1/11/2024,Customer_8,North,5,Product_5,Electronics,2,632,1264,COD
61,33,1062,5/31/2024,Customer_33,North,5,Product_5,Electronics,10,632,6320,UPI
62,44,1063,6/30/2024,Customer_44,North,20,Product_20,Electronics,5,1558,7790,COD
64,16,1065,5/3/2024,Customer_16,North,10,Product_10,Fashion,3,273,819,Card
65,28,1066,5/16/2024,Customer_28,North,13,Product_13,Home Decor,6,1267,7602,COD
66,38,1067,6/6/2024,Customer_38,North,8,Product_8,Home Decor,6,1924,11544,NetBanking
67,38,1068,4/20/2024,Customer_38,North,18,Product_18,Home Decor,3,1099,3297,NetBanking
70,8,1071,2/4/2024,Customer_8,North,13,Product_13,Home Decor,10,1267,12670,Card
77,8,1078,3/31/2024,Customer_8,North,20,Product_20,Electronics,8,1558,12464,UPI
98,44,1099,2/15/2024,Customer_44,North,2,Product_2,Home Decor,9,481,4329,UPI
99,3,1100,2/10/2024,Customer_3,North,14,Product_14,Grocery,4,204,816,UPI
104,44,1105,4/8/2024,Customer_44,North,2,Product_2,Home Decor,9,481,4329,NetBanking
111,10,1112,1/21/2024,Customer_10,North,14,Product_14,Grocery,9,204,1836,UPI
112,44,1113,3/28/2024,Customer_44,North,8,Product_8,Home Decor,8,1924,15392,Card
114,33,1115,5/14/2024,Customer_33,North,12,Product_12,Home Decor,7,1539,10773,NetBanking
117,38,1118,6/12/2024,Customer_38,North,1,Product_1,Grocery,3,574,1722,COD
125,3,1126,6/21/2024,Customer_3,North,17,Product_17,Electronics,8,1320,10560,UPI
128,16,1129,1/11/2024,Customer_16,North,14,Product_14,Grocery,7,204,1428,Card
137,38,1138,2/2/2024,Customer_38,North,2,Product_2,Home Decor,2,481,962,COD
144,8,1145,2/10/2024,Customer_8,North,18,Product_18,Home Decor,7,1099,7693,COD
148,34,1149,2/25/2024,Customer_34,North,14,Product_14,Grocery,9,204,1836,COD
156,37,1157,3/31/2024,Customer_37,North,8,Product_8,Home Decor,4,1924,7696,UPI
157,8,1158,5/3/2024,Customer_8,North,16,Product_16,Electronics,5,1948,9740,COD
158,34,1159,5/12/2024,Customer_34,North,7,Product_7,Fashion,4,1625,6500,Card
162,3,1163,2/18/2024,Customer_3,North,20,Product_20,Electronics,1,1558,1558,UPI
170,28,1171,1/19/2024,Customer_28,North,20,Product_20,Electronics,1,1558,1558,COD
175,10,1176,4/20/2024,Customer_10,North,14,Product_14,Grocery,8,204,1632,NetBanking
179,28,1180,2/5/2024,Customer_28,North,13,Product_13,Home Decor,6,1267,7602,Card
180,16,1181,5/19/2024,Customer_16,North,19,Product_19,Home Decor,6,1563,9378,COD
181,37,1182,3/23/2024,Customer_37,North,9,Product_9,Grocery,2,1047,2094,Card
186,38,1187,5/30/2024,Customer_38,North,12,Product_12,Home Decor,6,1539,9234,NetBanking
188,10,1189,1/23/2024,Customer_10,North,10,Product_10,Fashion,9,273,2457,UPI
194,16,1195,3/24/2024,Customer_16,North,11,Product_11,Grocery,5,1093,5465,NetBanking
195,10,1196,3/1/2024,Customer_10,North,18,Product_18,Home Decor,2,1099,2198,UPI
197,10,1198,4/5/2024,Customer_10,North,10,Product_10,Fashion,5,273,1365,Card
203,16,2010,12/14/2024,Customer_16,North,16,Product_16,Electronics,3,1948,5844,Card
209,33,2016,11/3/2024,Customer_33,North,20,Product_20,Electronics,10,1558,15580,NetBanking
223,20,2060,10/5/2024,Customer_20,North,15,Product_15,Grocery,4,976,3904,UPI
226,44,2063,12/24/2024,Customer_44,North,16,Product_16,Electronics,3,1948,5844,COD
229,33,2066,7/1/2024,Customer_33,North,20,Product_20,Electronics,10,1558,15580,Card
237,20,2074,9/7/2024,Customer_20,North,9,Product_9,Grocery,8,1047,8376,COD
242,3,2079,12/13/2024,Customer_3,North,4,Product_4,Grocery,3,1380,4140,NetBanking

In [105]:
data

,CustomerID,OrderID,OrderDate,CustomerName,Region,ProductID,ProductName,Category,Quantity,Price,TotalAmount,PaymentMethod
0,2,1001,5/21/2024,Customer_2,E,9,Product_9,Grocery,9,1047,9423,UPI
1,37,1002,1/18/2024,Customer_37,North,19,Product_19,Home Decor,1,1563,1563,NetBanking
2,9,1003,3/28/2024,Customer_9,South,12,Product_12,Home Decor,4,1539,6156,COD
3,40,1004,3/29/2024,Customer_40,West,14,Product_14,Grocery,3,204,612,NetBanking
4,40,1005,5/25/2024,Customer_40,West,14,Product_14,Grocery,9,204,1836,COD
...,...,...,...,...,...,...,...,...,...,...,...,...
249,39,1010,2/11/2024,Customer_39,East,5,Product_5,Electronics,1,632,632,NetBanking
250,45,1013,5/22/2024,Customer_45,East,1,Product_1,Grocery,1,574,574,Card
251,26,1016,5/29/2024,Customer_26,East,8,Product_8,Home Decor,8,1924,15392,COD
252,25,1017,4/26/2024,Customer_25,East,8,Product_8,Home Decor,6,1924,11544,Card
253,35,1023,6/24/2024,Customer_35,East,9,Product_9,Grocery,2,1047,2094,Card

In [106]:
data.query("Category=='Grocery'")

,CustomerID,OrderID,OrderDate,CustomerName,Region,ProductID,ProductName,Category,Quantity,Price,TotalAmount,PaymentMethod
0,2,1001,5/21/2024,Customer_2,E,9,Product_9,Grocery,9,1047,9423,UPI
3,40,1004,3/29/2024,Customer_40,West,14,Product_14,Grocery,3,204,612,NetBanking
4,40,1005,5/25/2024,Customer_40,West,14,Product_14,Grocery,9,204,1836,COD
11,29,1012,4/5/2024,Customer_29,West,9,Product_9,Grocery,5,1047,5235,UPI
12,45,1013,5/22/2024,Customer_45,E,1,Product_1,Grocery,1,574,574,Card
...,...,...,...,...,...,...,...,...,...,...,...,...
237,20,2074,9/7/2024,Customer_20,North,9,Product_9,Grocery,8,1047,8376,COD
242,3,2079,12/13/2024,Customer_3,North,4,Product_4,Grocery,3,1380,4140,NetBanking
246,2,1001,5/21/2024,Customer_2,East,9,Product_9,Grocery,9,1047,9423,UPI
250,45,1013,5/22/2024,Customer_45,East,1,Product_1,Grocery,1,574,574,Card
253,35,1023,6/24/2024,Customer_35,East,9,Product_9,Grocery,2,1047,2094,Card

In [107]:
data.query("Region=='East' & Category=='Grocery'")

,CustomerID,OrderID,OrderDate,CustomerName,Region,ProductID,ProductName,Category,Quantity,Price,TotalAmount,PaymentMethod
68,39,1069,4/2/2024,Customer_39,East,15,Product_15,Grocery,5,976,4880,NetBanking
87,2,1088,5/14/2024,Customer_2,East,1,Product_1,Grocery,10,574,5740,COD
94,39,1095,3/16/2024,Customer_39,East,1,Product_1,Grocery,9,574,5166,NetBanking
97,13,1098,3/16/2024,Customer_13,East,14,Product_14,Grocery,2,204,408,NetBanking
160,45,1161,2/11/2024,Customer_45,East,15,Product_15,Grocery,5,976,4880,COD
205,2,2012,9/6/2024,Customer_2,East,1,Product_1,Grocery,8,574,4592,COD
222,39,2059,10/14/2024,Customer_39,East,11,Product_11,Grocery,3,1093,3279,COD
246,2,1001,5/21/2024,Customer_2,East,9,Product_9,Grocery,9,1047,9423,UPI
250,45,1013,5/22/2024,Customer_45,East,1,Product_1,Grocery,1,574,574,Card
253,35,1023,6/24/2024,Customer_35,East,9,Product_9,Grocery,2,1047,2094,Card

In [108]:
data.query("Region=='East' & Category=='Grocery' & Quantity>8")

,CustomerID,OrderID,OrderDate,CustomerName,Region,ProductID,ProductName,Category,Quantity,Price,TotalAmount,PaymentMethod
87,2,1088,5/14/2024,Customer_2,East,1,Product_1,Grocery,10,574,5740,COD
94,39,1095,3/16/2024,Customer_39,East,1,Product_1,Grocery,9,574,5166,NetBanking
246,2,1001,5/21/2024,Customer_2,East,9,Product_9,Grocery,9,1047,9423,UPI

In [109]:
data

,CustomerID,OrderID,OrderDate,CustomerName,Region,ProductID,ProductName,Category,Quantity,Price,TotalAmount,PaymentMethod
0,2,1001,5/21/2024,Customer_2,E,9,Product_9,Grocery,9,1047,9423,UPI
1,37,1002,1/18/2024,Customer_37,North,19,Product_19,Home Decor,1,1563,1563,NetBanking
2,9,1003,3/28/2024,Customer_9,South,12,Product_12,Home Decor,4,1539,6156,COD
3,40,1004,3/29/2024,Customer_40,West,14,Product_14,Grocery,3,204,612,NetBanking
4,40,1005,5/25/2024,Customer_40,West,14,Product_14,Grocery,9,204,1836,COD
...,...,...,...,...,...,...,...,...,...,...,...,...
249,39,1010,2/11/2024,Customer_39,East,5,Product_5,Electronics,1,632,632,NetBanking
250,45,1013,5/22/2024,Customer_45,East,1,Product_1,Grocery,1,574,574,Card
251,26,1016,5/29/2024,Customer_26,East,8,Product_8,Home Decor,8,1924,15392,COD
252,25,1017,4/26/2024,Customer_25,East,8,Product_8,Home Decor,6,1924,11544,Card
253,35,1023,6/24/2024,Customer_35,East,9,Product_9,Grocery,2,1047,2094,Card

In [110]:
data.query("(Region=='East'|Region=='West') & Price>1500")

,CustomerID,OrderID,OrderDate,CustomerName,Region,ProductID,ProductName,Category,Quantity,Price,TotalAmount,PaymentMethod
7,30,1008,4/13/2024,Customer_30,West,12,Product_12,Home Decor,10,1539,15390,NetBanking
28,27,1029,2/4/2024,Customer_27,West,16,Product_16,Electronics,5,1948,9740,Card
36,49,1037,5/24/2024,Customer_49,West,7,Product_7,Fashion,3,1625,4875,NetBanking
37,23,1038,5/2/2024,Customer_23,West,8,Product_8,Home Decor,4,1924,7696,Card
41,15,1042,5/16/2024,Customer_15,West,8,Product_8,Home Decor,4,1924,7696,Card
52,49,1053,5/28/2024,Customer_49,West,12,Product_12,Home Decor,1,1539,1539,Card
56,35,1057,1/26/2024,Customer_35,East,16,Product_16,Electronics,1,1948,1948,NetBanking
58,6,1059,6/10/2024,Customer_6,West,12,Product_12,Home Decor,5,1539,7695,COD
59,26,1060,2/15/2024,Customer_26,East,16,Product_16,Electronics,6,1948,11688,NetBanking
60,23,1061,3/11/2024,Customer_23,West,8,Product_8,Home Decor,7,1924,13468,UPI
69,24,1070,3/15/2024,Customer_24,West,12,Product_12,Home Decor,6,1539,9234,Card
73,26,1074,3/18/2024,Customer_26,East,7,Product_7,Fashion,6,1625,9750,Card
76,40,1077,2/7/2024,Customer_40,West,12,Product_12,Home Decor,6,1539,9234,UPI
85,47,1086,3/25/2024,Customer_47,West,16,Product_16,Electronics,5,1948,9740,Card
100,39,1101,2/17/2024,Customer_39,East,8,Product_8,Home Decor,2,1924,3848,COD
101,23,1102,3/2/2024,Customer_23,West,8,Product_8,Home Decor,8,1924,15392,UPI
103,17,1104,2/9/2024,Customer_17,West,19,Product_19,Home Decor,5,1563,7815,Card
106,25,1107,4/7/2024,Customer_25,East,19,Product_19,Home Decor,7,1563,10941,COD
124,39,1125,4/27/2024,Customer_39,East,16,Product_16,Electronics,5,1948,9740,NetBanking
131,48,1132,6/5/2024,Customer_48,East,8,Product_8,Home Decor,6,1924,11544,Card
135,24,1136,3/14/2024,Customer_24,West,12,Product_12,Home Decor,7,1539,10773,Card
136,32,1137,5/29/2024,Customer_32,West,16,Product_16,Electronics,10,1948,19480,COD
143,21,1144,5/23/2024,Customer_21,West,20,Product_20,Electronics,9,1558,14022,NetBanking
161,45,1162,3/3/2024,Customer_45,East,20,Product_20,Electronics,6,1558,9348,Card
171,17,1172,5/11/2024,Customer_17,West,20,Product_20,Electronics,4,1558,6232,COD
173,11,1174,1/10/2024,Customer_11,West,8,Product_8,Home Decor,6,1924,11544,UPI
198,48,1199,2/22/2024,Customer_48,East,16,Product_16,Electronics,2,1948,3896,NetBanking
206,26,2013,8/12/2024,Customer_26,East,12,Product_12,Home Decor,9,1539,13851,UPI
214,15,2051,12/6/2024,Customer_15,West,19,Product_19,Home Decor,1,1563,1563,Card
217,40,2054,10/9/2024,Customer_40,West,7,Product_7,Fashion,5,1625,8125,Card
219,41,2056,7/3/2024,Customer_41,West,19,Product_19,Home Decor,4,1563,6252,COD
225,48,2062,7/17/2024,Customer_48,East,16,Product_16,Electronics,5,1948,9740,NetBanking
227,30,2064,9/5/2024,Customer_30,West,20,Product_20,Electronics,2,1558,3116,COD
228,17,2065,8/9/2024,Customer_17,West,16,Product_16,Electronics,5,1948,9740,UPI
230,2,2067,11/25/2024,Customer_2,East,16,Product_16,Electronics,3,1948,5844,UPI
231,5,2068,7/6/2024,Customer_5,West,7,Product_7,Fashion,7,1625,11375,Card
233,35,2070,11/7/2024,Customer_35,East,7,Product_7,Fashion,3,1625,4875,UPI
234,7,2071,12/28/2024,Customer_7,West,8,Product_8,Home Decor,7,1924,13468,COD
236,49,2073,11/12/2024,Customer_49,West,12,Product_12,Home Decor,4,1539,6156,NetBanking
251,26,1016,5/29/2024,Customer_26,East,8,Product_8,Home Decor,8,1924,15392,COD
252,25,1017,4/26/2024,Customer_25,East,8,Product_8,Home Decor,6,1924,11544,Card

In [111]:
data

,CustomerID,OrderID,OrderDate,CustomerName,Region,ProductID,ProductName,Category,Quantity,Price,TotalAmount,PaymentMethod
0,2,1001,5/21/2024,Customer_2,E,9,Product_9,Grocery,9,1047,9423,UPI
1,37,1002,1/18/2024,Customer_37,North,19,Product_19,Home Decor,1,1563,1563,NetBanking
2,9,1003,3/28/2024,Customer_9,South,12,Product_12,Home Decor,4,1539,6156,COD
3,40,1004,3/29/2024,Customer_40,West,14,Product_14,Grocery,3,204,612,NetBanking
4,40,1005,5/25/2024,Customer_40,West,14,Product_14,Grocery,9,204,1836,COD
...,...,...,...,...,...,...,...,...,...,...,...,...
249,39,1010,2/11/2024,Customer_39,East,5,Product_5,Electronics,1,632,632,NetBanking
250,45,1013,5/22/2024,Customer_45,East,1,Product_1,Grocery,1,574,574,Card
251,26,1016,5/29/2024,Customer_26,East,8,Product_8,Home Decor,8,1924,15392,COD
252,25,1017,4/26/2024,Customer_25,East,8,Product_8,Home Decor,6,1924,11544,Card
253,35,1023,6/24/2024,Customer_35,East,9,Product_9,Grocery,2,1047,2094,Card

In [112]:
data[['OrderID','Region']]

     OrderID Region
0       1001      E
1       1002  North
2       1003  South
3       1004   West
4       1005   West
..       ...    ...
249     1010   East
250     1013   East
251     1016   East
252     1017   East
253     1023   East

[254 rows x 2 columns]

In [113]:
data.filter(items=['OrderID','Region','Price'])

     OrderID Region  Price
0       1001      E   1047
1       1002  North   1563
2       1003  South   1539
3       1004   West    204
4       1005   West    204
..       ...    ...    ...
249     1010   East    632
250     1013   East    574
251     1016   East   1924
252     1017   East   1924
253     1023   East   1047

[254 rows x 3 columns]

In [114]:
data.filter(items=['Region','Price','Category']).query("Region=='North'&Category=='Home Decor'")

    Region  Price    Category
1    North   1563  Home Decor
13   North   1924  Home Decor
20   North   1924  Home Decor
26   North    481  Home Decor
43   North   1539  Home Decor
65   North   1267  Home Decor
66   North   1924  Home Decor
67   North   1099  Home Decor
70   North   1267  Home Decor
98   North    481  Home Decor
104  North    481  Home Decor
112  North   1924  Home Decor
114  North   1539  Home Decor
137  North    481  Home Decor
144  North   1099  Home Decor
156  North   1924  Home Decor
179  North   1267  Home Decor
180  North   1563  Home Decor
186  North   1539  Home Decor
195  North   1099  Home Decor

In [115]:
data

,CustomerID,OrderID,OrderDate,CustomerName,Region,ProductID,ProductName,Category,Quantity,Price,TotalAmount,PaymentMethod
0,2,1001,5/21/2024,Customer_2,E,9,Product_9,Grocery,9,1047,9423,UPI
1,37,1002,1/18/2024,Customer_37,North,19,Product_19,Home Decor,1,1563,1563,NetBanking
2,9,1003,3/28/2024,Customer_9,South,12,Product_12,Home Decor,4,1539,6156,COD
3,40,1004,3/29/2024,Customer_40,West,14,Product_14,Grocery,3,204,612,NetBanking
4,40,1005,5/25/2024,Customer_40,West,14,Product_14,Grocery,9,204,1836,COD
...,...,...,...,...,...,...,...,...,...,...,...,...
249,39,1010,2/11/2024,Customer_39,East,5,Product_5,Electronics,1,632,632,NetBanking
250,45,1013,5/22/2024,Customer_45,East,1,Product_1,Grocery,1,574,574,Card
251,26,1016,5/29/2024,Customer_26,East,8,Product_8,Home Decor,8,1924,15392,COD
252,25,1017,4/26/2024,Customer_25,East,8,Product_8,Home Decor,6,1924,11544,Card
253,35,1023,6/24/2024,Customer_35,East,9,Product_9,Grocery,2,1047,2094,Card

In [116]:
data[(data['Region']=='North') | (data['ProductName']=='Product_19')]

,CustomerID,OrderID,OrderDate,CustomerName,Region,ProductID,ProductName,Category,Quantity,Price,TotalAmount,PaymentMethod
1,37,1002,1/18/2024,Customer_37,North,19,Product_19,Home Decor,1,1563,1563,NetBanking
13,16,1014,6/15/2024,Customer_16,North,8,Product_8,Home Decor,9,1924,17316,COD
18,16,1019,3/23/2024,Customer_16,North,14,Product_14,Grocery,3,204,612,NetBanking
20,38,1021,3/15/2024,Customer_38,North,8,Product_8,Home Decor,1,1924,1924,UPI
21,28,1022,3/3/2024,Customer_28,North,4,Product_4,Grocery,10,1380,13800,COD
...,...,...,...,...,...,...,...,...,...,...,...,...
223,20,2060,10/5/2024,Customer_20,North,15,Product_15,Grocery,4,976,3904,UPI
226,44,2063,12/24/2024,Customer_44,North,16,Product_16,Electronics,3,1948,5844,COD
229,33,2066,7/1/2024,Customer_33,North,20,Product_20,Electronics,10,1558,15580,Card
237,20,2074,9/7/2024,Customer_20,North,9,Product_9,Grocery,8,1047,8376,COD
242,3,2079,12/13/2024,Customer_3,North,4,Product_4,Grocery,3,1380,4140,NetBanking

In [119]:
data=data[data['Price']>1500]

In [120]:
data

,CustomerID,OrderID,OrderDate,CustomerName,Region,ProductID,ProductName,Category,Quantity,Price,TotalAmount,PaymentMethod
1,37,1002,1/18/2024,Customer_37,North,19,Product_19,Home Decor,1,1563,1563,NetBanking
2,9,1003,3/28/2024,Customer_9,South,12,Product_12,Home Decor,4,1539,6156,COD
7,30,1008,4/13/2024,Customer_30,West,12,Product_12,Home Decor,10,1539,15390,NetBanking
13,16,1014,6/15/2024,Customer_16,North,8,Product_8,Home Decor,9,1924,17316,COD
15,26,1016,5/29/2024,Customer_26,E,8,Product_8,Home Decor,8,1924,15392,COD
...,...,...,...,...,...,...,...,...,...,...,...,...
234,7,2071,12/28/2024,Customer_7,West,8,Product_8,Home Decor,7,1924,13468,COD
236,49,2073,11/12/2024,Customer_49,West,12,Product_12,Home Decor,4,1539,6156,NetBanking
239,19,2076,7/15/2024,Customer_19,South,16,Product_16,Electronics,8,1948,15584,COD
251,26,1016,5/29/2024,Customer_26,East,8,Product_8,Home Decor,8,1924,15392,COD
252,25,1017,4/26/2024,Customer_25,East,8,Product_8,Home Decor,6,1924,11544,Card